In [1]:
import pandas as pd
import selfies as sf
from sklearn.preprocessing import MinMaxScaler

df_polarizability = pd.read_csv('../polygraphpy/data/polarizability_data.csv')

scaler = MinMaxScaler()
df_polarizability['static_polarizability'] = scaler.fit_transform(df_polarizability['static_polarizability'].values.reshape(-1,1)).flatten()
df_polarizability = df_polarizability[df_polarizability['chain_size'] == 0].reset_index(drop=True)

smiles_list = df_polarizability['smiles_A'].values
target = df_polarizability['static_polarizability'].values
selfies_list = []

for i in smiles_list:
    selfies_list.append(sf.encoder(i))

In [ ]:
import selfies as sf
from rdkit import Chem

# 1. Define the SMILES string
smiles_string = "COC(=O)C=C"

# 2. Encode SMILES to SELFIES
encoded_selfies = sf.encoder(smiles_string)

# 3. Decode SELFIES back to SMILES (optional)
decoded_smiles = sf.decoder(encoded_selfies)

# 4. Print the results
print(f"Original SMILES: {smiles_string}")
print(f"Encoded SELFIES: {encoded_selfies}")
print(f"Decoded SMILES: {decoded_smiles}")

# 5. Canonicalize SMILES for robust comparison
can_smiles_original = Chem.CanonSmiles(smiles_string)
can_smiles_decoded = Chem.CanonSmiles(decoded_smiles)

print(f"RDKit Canonical SMILES (Original): {can_smiles_original}")
print(f"RDKit Canonical SMILES (Decoded): {can_smiles_decoded}")
print(f"Are canonical SMILES equal? {can_smiles_original == can_smiles_decoded}")

Original SMILES: COC(=O)C=C
Encoded SELFIES: [C][O][C][=Branch1][C][=O][C][=C]
Decoded SMILES: COC(=O)C=C
RDKit Canonical SMILES (Original): C=CC(=O)OC
RDKit Canonical SMILES (Decoded): C=CC(=O)OC
Are canonical SMILES equal? True

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
import torch
import rdkit.Chem as Chem

# Data
texts = [f"polarizability: {p} selfies: {i}" for i, p in zip(selfies_list, target)]

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = AutoModelForCausalLM.from_pretrained('gpt2')
model.resize_token_embeddings(len(tokenizer))

class InChIDataset(Dataset):
    def __init__(self, texts, tokenizer, max_len=128):
        self.encodings = tokenizer(texts, truncation=True, padding=True, max_length=max_len, return_tensors='pt')

    def __len__(self):
        return len(self.encodings['input_ids'])

    def __getitem__(self, idx):
        return {k: v[idx] for k, v in self.encodings.items()}

dataset = InChIDataset(texts, tokenizer)
loader = DataLoader(dataset, batch_size=12, shuffle=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
optimizer = AdamW(model.parameters(), lr=5e-5)

aux = 1e9

# Training
model.train()
for epoch in range(100):
    epoch_loss = 0.0

    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        optimizer.zero_grad()
        outputs = model(**batch, labels=batch['input_ids'])
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item() * batch['input_ids'].size(0)
    
    total_loss = epoch_loss / len(dataset)
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    if total_loss < aux:
        torch.save(model, 'gpt_selfies.pt')
        aux = total_loss

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

Epoch 1, Loss: 0.8183
Epoch 2, Loss: 0.5479
Epoch 3, Loss: 0.5227
Epoch 4, Loss: 0.5080
Epoch 5, Loss: 0.4951
Epoch 6, Loss: 0.4847
Epoch 7, Loss: 0.4749
Epoch 8, Loss: 0.4661
Epoch 9, Loss: 0.4588
Epoch 10, Loss: 0.4514
Epoch 11, Loss: 0.4439
Epoch 12, Loss: 0.4366
Epoch 13, Loss: 0.4296
Epoch 14, Loss: 0.4214
Epoch 15, Loss: 0.4126
Epoch 16, Loss: 0.4045
Epoch 17, Loss: 0.3950
Epoch 18, Loss: 0.3858
Epoch 19, Loss: 0.3757
Epoch 20, Loss: 0.3647
Epoch 21, Loss: 0.3539
Epoch 22, Loss: 0.3426
Epoch 23, Loss: 0.3315
Epoch 24, Loss: 0.3205
Epoch 25, Loss: 0.3093
Epoch 26, Loss: 0.2982
Epoch 27, Loss: 0.2879
Epoch 28, Loss: 0.2776
Epoch 29, Loss: 0.2675
Epoch 30, Loss: 0.2570
Epoch 31, Loss: 0.2482
Epoch 32, Loss: 0.2388
Epoch 33, Loss: 0.2306
Epoch 34, Loss: 0.2220
Epoch 35, Loss: 0.2152
Epoch 36, Loss: 0.2081
Epoch 37, Loss: 0.2011
Epoch 38, Loss: 0.1947
Epoch 39, Loss: 0.1892
Epoch 40, Loss: 0.1838
Epoch 41, Loss: 0.1794
Epoch 42, Loss: 0.1739
Epoch 43, Loss: 0.1699
Epoch 44, Loss: 0.1655
Epoch 45, Loss: 0.1613
Epoch 46, Loss: 0.1574
Epoch 47, Loss: 0.1534
Epoch 48, Loss: 0.1498
Epoch 49, Loss: 0.1466
Epoch 50, Loss: 0.1430
Epoch 51, Loss: 0.1402
Epoch 52, Loss: 0.1370
Epoch 53, Loss: 0.1346
Epoch 54, Loss: 0.1315
Epoch 55, Loss: 0.1291
Epoch 56, Loss: 0.1267
Epoch 57, Loss: 0.1243
Epoch 58, Loss: 0.1224
Epoch 59, Loss: 0.1200
Epoch 60, Loss: 0.1182
Epoch 61, Loss: 0.1170
Epoch 62, Loss: 0.1147
Epoch 63, Loss: 0.1134
Epoch 64, Loss: 0.1118
Epoch 65, Loss: 0.1107
Epoch 66, Loss: 0.1094
Epoch 67, Loss: 0.1084
Epoch 68, Loss: 0.1072
Epoch 69, Loss: 0.1058
Epoch 70, Loss: 0.1049
Epoch 71, Loss: 0.1047
Epoch 72, Loss: 0.1029
Epoch 73, Loss: 0.1024
Epoch 74, Loss: 0.1018
Epoch 75, Loss: 0.1010
Epoch 76, Loss: 0.1001
Epoch 77, Loss: 0.0991
Epoch 78, Loss: 0.0988
Epoch 79, Loss: 0.0978
Epoch 80, Loss: 0.0974
Epoch 81, Loss: 0.0970
Epoch 82, Loss: 0.0963
Epoch 83, Loss: 0.0962
Epoch 84, Loss: 0.0952
Epoch 85, Loss: 0.0950
Epoch 86, Loss: 0.0944
Epoch 87, Loss: 0.0943
Epoch 88, Loss: 0.0937
Epoch 89, Loss: 0.0934
Epoch 90, Loss: 0.0928
Epoch 91, Loss: 0.0927
Epoch 92, Loss: 0.0924
Epoch 93, Loss: 0.0915
Epoch 94, Loss: 0.0913
Epoch 95, Loss: 0.0913
Epoch 96, Loss: 0.0909
Epoch 97, Loss: 0.0906
Epoch 98, Loss: 0.0903
Epoch 99, Loss: 0.0901
Epoch 100, Loss: 0.0898

In [5]:
# Generation
def generate(model, tokenizer, xlogp_val, max_len=1000):
    try:
        prompt = f"polarizability: {xlogp_val} selfies:"
        inputs = tokenizer(prompt, return_tensors='pt').to(device)
        outputs = model.generate(**inputs, max_length=max_len, num_beams=1, do_sample=True, temperature=0.9, top_p=0.9)
        gen_text = tokenizer.decode(outputs[0])
        selfies = gen_text.split("selfies:")[1].strip() if "selfies:" in gen_text else None
        selfies = selfies.split('[PAD]')[0]
        selfies = selfies.replace("\\", "/")
        smiles = sf.decoder(selfies)
        valid = smiles and Chem.MolFromSmiles(smiles) is not None
        print(f"{smiles} - Valid: {valid}")
        return smiles
    except Exception as e:
        print(e)
        return None

In [6]:
import numpy as np
from tqdm import tqdm

values_vec = np.linspace(0, df_polarizability['static_polarizability'].max(), 350)
smiles_test_df = pd.DataFrame()

for i in tqdm(values_vec):
    smiles = generate(model, tokenizer, i)
    polarizability_scaled = i

    if smiles is not None:
        smiles_test_df = pd.concat([smiles_test_df, pd.DataFrame({'smiles': smiles, 
                                                                'static_polarizability': polarizability_scaled}, index=[0])]).reset_index(drop=True)

  0%|          | 0/350 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 1/350 [00:04<28:37,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)O - Valid: True

  1%|          | 2/350 [00:09<28:23,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(C=C1)Cl - Valid: True

  1%|          | 3/350 [00:14<28:12,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)ON - Valid: True

  1%|          | 4/350 [00:19<28:07,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1] - Valid: True

  1%|▏         | 5/350 [00:24<27:59,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN - Valid: True

  2%|▏         | 6/350 [00:29<27:50,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)C#N - Valid: True

  2%|▏         | 7/350 [00:34<27:41,  4.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC(F)(F)F - Valid: True

  2%|▏         | 8/350 [00:38<27:32,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1].C=C(CN)N - Valid: True

  3%|▎         | 9/350 [00:43<27:29,  4.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OC - Valid: True

  3%|▎         | 10/350 [00:48<27:19,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C - Valid: True

  3%|▎         | 11/350 [00:53<27:14,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CN - Valid: True

  3%|▎         | 12/350 [00:58<27:11,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC(C)C#N - Valid: True

  4%|▎         | 13/350 [01:02<27:05,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C(=O)Cl - Valid: True

  4%|▍         | 14/350 [01:07<27:01,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C(F)(F)F - Valid: True

  4%|▍         | 15/350 [01:12<26:54,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1CCOC1=O - Valid: True

  5%|▍         | 16/350 [01:17<26:52,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)C#N - Valid: True

  5%|▍         | 17/350 [01:22<26:44,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CNC=O - Valid: True

  5%|▌         | 18/350 [01:27<26:41,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C(C)OC(=O)C=C - Valid: True

  5%|▌         | 19/350 [01:32<26:54,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=C - Valid: True

  6%|▌         | 20/350 [01:37<26:57,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC(=C)C(=O)OCCN - Valid: True

  6%|▌         | 21/350 [01:41<26:57,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC(C(C(F)(F)F)(F)F)(F)F - Valid: True

  6%|▋         | 22/350 [01:46<26:55,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC(F)(F)F - Valid: True

  7%|▋         | 23/350 [01:51<26:53,  4.93s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCCOC(=O)C=C - Valid: True

  7%|▋         | 24/350 [01:56<26:52,  4.95s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=CCCl - Valid: True

  7%|▋         | 25/350 [02:01<26:32,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC(C)(C)OC(=O)C(=CCF)F - Valid: True

  7%|▋         | 26/350 [02:06<26:01,  4.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CN=CN1 - Valid: True

  8%|▊         | 27/350 [02:10<25:27,  4.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CNC=C1 - Valid: True

  8%|▊         | 28/350 [02:15<25:06,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCC(C(F)F)(F)F - Valid: True

  8%|▊         | 29/350 [02:19<24:46,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCNC(=O)OCCOC(=O)C=C - Valid: True

  9%|▊         | 30/350 [02:24<24:31,  4.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=CC1=CN=CO1 - Valid: True

  9%|▉         | 31/350 [02:28<24:21,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCNC=CC(=O)[O-1] - Valid: True

  9%|▉         | 32/350 [02:33<24:15,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)COCCOCCO - Valid: True

  9%|▉         | 33/350 [02:38<24:33,  4.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)CS(=O)(=O)C1=CC=CC=C1 - Valid: True

 10%|▉         | 34/350 [02:43<25:01,  4.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCC(C(C(C(C(F)(F)F)(F)F)(F)F)F)F - Valid: True

 10%|█         | 35/350 [02:50<28:40,  5.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(C=C1)Cl - Valid: True

 10%|█         | 36/350 [02:57<31:41,  6.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CN(C)C)C1=CN=NN1 - Valid: True

 11%|█         | 37/350 [03:04<33:12,  6.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=NC=C1)F - Valid: True

 11%|█         | 38/350 [03:10<31:27,  6.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)C(C1=CC(=CC=C1)Br)O - Valid: True

 11%|█         | 39/350 [03:15<30:17,  5.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC=C1OC(=O)C=C - Valid: True

 11%|█▏        | 40/350 [03:21<29:28,  5.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=NC=C1)N - Valid: True

 12%|█▏        | 41/350 [03:26<28:50,  5.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)Cl - Valid: True

 12%|█▏        | 42/350 [03:31<28:25,  5.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C(=C)C1=CN=CC=C1 - Valid: True

 12%|█▏        | 43/350 [03:37<28:06,  5.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CNC(=O)NC1=O - Valid: True

 13%|█▎        | 44/350 [03:42<27:47,  5.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=CC=C1I - Valid: True

 13%|█▎        | 45/350 [03:47<27:35,  5.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)CCO - Valid: True

 13%|█▎        | 46/350 [03:53<27:25,  5.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC=C1Cl)N - Valid: True

 13%|█▎        | 47/350 [03:58<27:15,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)N)/C=C/C(=O)OC - Valid: True

 14%|█▎        | 48/350 [04:03<27:08,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC(=C(C=C1)C=O)OC(F)(F)F - Valid: True

 14%|█▍        | 49/350 [04:09<27:03,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC(=C(C=N1)Cl)C=O - Valid: True

 14%|█▍        | 50/350 [04:14<26:55,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=NC(=C(C=C1)C(C)C)N - Valid: True

 15%|█▍        | 51/350 [04:20<26:48,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC(=CC=C1)Cl)C#N - Valid: True

 15%|█▍        | 52/350 [04:25<26:43,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=C(C=C1)Br)[N+1](=O)[O-1] - Valid: True

 15%|█▌        | 53/350 [04:30<26:38,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C1=CC(=C(C=C1)OCOC)OC - Valid: True

 15%|█▌        | 54/350 [04:36<26:31,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1(CC(CCO1)C2=C)C=C(C=C2)OO - Valid: True

 16%|█▌        | 55/350 [04:41<26:25,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)Cl)/CN2C=NC=N2 - Valid: True

 16%|█▌        | 56/350 [04:47<26:21,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C(=C/C1=CC(=C(C=C1)F)O)C/C#N - Valid: True

 16%|█▋        | 57/350 [04:52<26:17,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC(=C(C=C1)Br)OC(F)F - Valid: True

 17%|█▋        | 58/350 [04:57<26:11,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1=CC=C(C=C1)SC2=CC=CC=C2 - Valid: True

 17%|█▋        | 59/350 [05:03<26:06,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C(C1=COC=C1CCl)P(=O)(OCC)OCC - Valid: True

 17%|█▋        | 60/350 [05:08<26:00,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=C(C=C1)OCOC)OC - Valid: True

 17%|█▋        | 61/350 [05:13<25:56,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)COC(=O)C(=C)C1=CC2=C(C=CC=N2)C=C1 - Valid: True

 18%|█▊        | 62/350 [05:19<25:54,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=COC2=C(C1=O)C=CC(=C2O)OC - Valid: True

 18%|█▊        | 63/350 [05:24<25:47,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=CC1=CC(=C(C=C1OC)OC)OC - Valid: True

 18%|█▊        | 64/350 [05:30<25:41,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C(C1=C(C=CO1)C)P(=O)(OCC)OCC - Valid: True

 19%|█▊        | 65/350 [05:35<25:35,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCC(CCCCCCCC)OC(=O)C=C - Valid: True

 19%|█▉        | 66/350 [05:40<25:29,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CN(C)C)C(=O)C1=CC=C(C=C1F)F - Valid: True

 19%|█▉        | 67/350 [05:46<25:22,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C(C)C1=CC=C(C=C1)OC2=CC(=CC=C2)F - Valid: True

 19%|█▉        | 68/350 [05:51<25:17,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC(C1=CC=CC=C1)C2=CC=CC=C2OC3=CC=CC=C3 - Valid: True

 20%|█▉        | 69/350 [05:57<25:16,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C(C1=CC(=C(C=C1Cl)Cl)F)O)C=NC2=C(C=C(C=C2)Cl)Cl - Valid: True

 20%|██        | 70/350 [06:02<25:09,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)Cl)/CNCC2=CC=CC=C2 - Valid: True

 20%|██        | 71/350 [06:07<25:05,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C=CC=C(O)Br - Valid: True

 21%|██        | 72/350 [06:13<25:00,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOP(=O)(C)OC1=CC=C(C=C1)C=CC(=O)OC(C)(C)CC - Valid: True

 21%|██        | 73/350 [06:18<24:54,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC(=C(C(=C1)OC)O)COC)/I - Valid: True

 21%|██        | 74/350 [06:24<24:50,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)O)OC2=C(C=C(C=C2)Cl)Cl - Valid: True

 21%|██▏       | 75/350 [06:29<24:45,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C#CCOC(=O)/C=C/C1=CC=C(O1)C2=CC=C(C=C2)Cl - Valid: True

 22%|██▏       | 76/350 [06:34<24:37,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C(C1=CC(=C(C=C1Cl)Cl)F)O)C=NC2=C(C=C(C=C2F)F)F - Valid: True

 22%|██▏       | 77/350 [06:40<24:31,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=CC1=CSC(=N1)N2CCOCC2C3=NN(C=N3)/C=C/C(=O)OC - Valid: True

 22%|██▏       | 78/350 [06:45<24:27,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=C(C=C1)OC2=CC(=C(C=C2)Cl)Cl - Valid: True

 23%|██▎       | 79/350 [06:51<24:21,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)OCCOC(=O)C=C.C=CC(=O)OCCCCO - Valid: True

 23%|██▎       | 80/350 [06:56<24:15,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC=C(C=C2)[N+1](=O)[O-1])C(F)F - Valid: True

 23%|██▎       | 81/350 [07:01<24:10,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)O)OCC2=CC=C(C=C2)[N+1](=O)[O-1] - Valid: True

 23%|██▎       | 82/350 [07:07<24:05,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC(C)CC(=O)OC(C)C - Valid: True

 24%|██▎       | 83/350 [07:12<23:59,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=C(C=C(C=C2)Cl)Cl)OC - Valid: True

 24%|██▍       | 84/350 [07:17<23:54,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=C(N(C2=CC=CC=C21)CC3=CC(=CC=C3)C)N)F - Valid: True

 24%|██▍       | 85/350 [07:23<23:49,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)P(C1CCCCC1)CCC=C2CC=C(C=C2)/C=C/C(=O)OC - Valid: True

 25%|██▍       | 86/350 [07:28<23:43,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(N1)C2=C(C(=CC(=C2)Cl)Cl)NC)COC(=O)C=CC - Valid: True

 25%|██▍       | 87/350 [07:34<23:38,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OC)I)OCC2=CC=C(C=C2)Br - Valid: True

 25%|██▌       | 88/350 [07:39<23:32,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=CC(=C1)/C=C/C(=O)OCI)CC2=CC(=C(C=C2)Cl)Cl - Valid: True

 25%|██▌       | 89/350 [07:44<23:26,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=CC=C(C=C1)NC(=O)COC(=O)/C=C/C2=CC=C(C=C2)OCCO - Valid: True

 26%|██▌       | 90/350 [07:50<23:21,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=C(C=C1)/C=C/C(=O)OCC#C)OCC2=CC(=CC=C2)Br - Valid: True

 26%|██▌       | 91/350 [07:55<23:15,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N(C)C2=CC=C(C=C2)OCC3=CC=CC=C3 - Valid: True

 26%|██▋       | 92/350 [08:01<23:10,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)C2=NC=C(S2)COC(=O)/C=C/C3=CC=C(C=C3)OC - Valid: True

 27%|██▋       | 93/350 [08:06<23:06,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N2C=CC3=C2C=CC(=C3)C#N - Valid: True

 27%|██▋       | 94/350 [08:12<23:08,  5.42s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(N=C1)N[C@@H1]2CCN(C2)CC3=CC=CC=C3C - Valid: True

 27%|██▋       | 95/350 [08:17<23:07,  5.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCOC1=CC2=C(C=C1)C=C(C=C2)/C=C/C(=O)OC3=CC(=CC=C3)C - Valid: True

 27%|██▋       | 96/350 [08:22<22:58,  5.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/N1C=NC(=N1)C2=CC=CC(=C2)OCC3=CC=CC=C3Cl - Valid: True

 28%|██▊       | 97/350 [08:28<22:50,  5.42s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OCC=C)Cl)OCC2=C(C=C(C=C2)Cl)Cl - Valid: True

 28%|██▊       | 98/350 [08:33<22:43,  5.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC[C@]CCC1=CC=C(S1)C2=CC=C(C=C2)CC3=CC=CC=C3C - Valid: True

 28%|██▊       | 99/350 [08:39<22:35,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C(=C1OCC2=CC=CC)C2/C=C/C=O)OCC=C[N+1]=O)[O-1] - Valid: True

 29%|██▊       | 100/350 [08:44<22:30,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC=C1C(=CC(C=C1)C2=CC=C(O2)/C=C/C(=O)OCNC)C=O - Valid: True

 29%|██▉       | 101/350 [08:49<22:25,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N=C(C=C1CN2C=O)C3=CC=CC=C3C=N2)CNC(=O)OC - Valid: True

 29%|██▉       | 102/350 [08:55<22:18,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=N1)N[C@@H1]2CCN(C2)CC3=CC=CC=C3Cl - Valid: True

 29%|██▉       | 103/350 [09:00<22:13,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CN=CC(=C1C=CC(=O)OCCOC)C2C=CC=CC2)CCC#N - Valid: True

 30%|██▉       | 104/350 [09:06<22:07,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@@H1]1CC=C([C@H1](N1CC=C)C2=CC=C(C=C2)/C=C/C(=O)OC)NC3=CC=CC(=C3)C(C)CC - Valid: True

 30%|███       | 105/350 [09:11<22:01,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C2=C(C=C(C=C2)Br)C3=COC(=N3)CCCCCCO - Valid: True

 30%|███       | 106/350 [09:16<21:54,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)COC1=CC=C(C=C1)NC(=O)C(COCN)C(=O)C2=CC(=C(C=C2)Cl)Cl - Valid: True

 31%|███       | 107/350 [09:22<21:50,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OC2C3=CC=CC=C3)CC(C)CC(=O)NC=C2 - Valid: True

 31%|███       | 108/350 [09:27<21:45,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/NC1=C(C=C(C=C1)[N+1](=O)[O-1])NC)C=O - Valid: True

 31%|███       | 109/350 [09:32<21:39,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C=NC1=C(C=CS1)C2=CC=C(C=C2)Cl)/C=C/C(=O)OCC3=CC=C(C=C3)CCl - Valid: True

 31%|███▏      | 110/350 [09:38<21:35,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C(/NC1=NC=C(S1)C(=O)NC2=CC=CC=C2SC=N)C/C)N - Valid: True

 32%|███▏      | 111/350 [09:43<21:31,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OC2=C(SC3=C2C=CC(=C3)O)C)SCC4=NC(=N)C=N4 - Valid: True

 32%|███▏      | 112/350 [09:49<21:23,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CSC(=N1)NC(=O)NC2=C(C=C(C=C2)Cl)C(=O)C=CC3=CSC=C3 - Valid: True

 32%|███▏      | 113/350 [09:54<21:18,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCNC(=O)N(C)C1=CC=CC(=C1)C2=CC(=C(C=C2)C(F)(F)F)CC(=O)OCC - Valid: True

 33%|███▎      | 114/350 [09:59<21:13,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)CC2=CC=C(C=C2)OC3=CC=C(C=C3)CN - Valid: True

 33%|███▎      | 115/350 [10:05<21:06,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)C=C(C=C2)C(=O)NC3=CC(=CC=C3)C(F)(F)F - Valid: True

 33%|███▎      | 116/350 [10:10<21:02,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=CC(=C1)/C2=C/C(=O)C3=C(C=CC=C3S)C2=O - Valid: True

[11:41:43] Conflicting single bond directions around double bond at index 24.
[11:41:43]   BondStereo set to STEREONONE and single bond directions set to NONE.
 33%|███▎      | 117/350 [10:16<20:56,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCNC(=O)N(CC)C1=CC=CC(=C1)C2=CC=C(C=C2)/C=C(/C(=O)OC)/OCCC(=C)CC(C)CN - Valid: True

 34%|███▎      | 118/350 [10:21<20:50,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)NC(=O)C(=CC=CC=CC2=C)C=C(C=C2)C#N - Valid: True

 34%|███▍      | 119/350 [10:26<20:46,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C(=CC=C1)OCC2=CC=CC=C2)C3=NN(C=C3C=CC=CC=CCl)Cl - Valid: True

 34%|███▍      | 120/350 [10:32<20:42,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C][=C][S][C][=Branch1][Ring2][=N][Ring1][Branch1][N][C][=N][C][=C][Branch2][Ring1][=Branch1][C][=Branch1][Ring2][=C][Ring1][=Branch1][O][C][=C][C][=C][C][=C][C][=C][Ring1][=Branch1][/C][=Branch1][Ring2][=C][/O][C][/C][=Branch1][C][=O][O][C][C][C][C]C][=C][C][=C]

 35%|███▍      | 121/350 [10:37<20:35,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(S1)NC(=O)NC2=C(C=C(C=C2)/C=C/C(=O)OC)Br - Valid: True

 35%|███▍      | 122/350 [10:43<20:29,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C(=C1)OCC2=CC=CC=C2)OCOCC(=O)C=CC=CC=CC=C - Valid: True

 35%|███▌      | 123/350 [10:48<20:24,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC(CC)COC(=O)C=C.CC(=C)C(=O)OCCOC(=O)C1=CC=CC=C1C=C(C=C)C=CCC(Cl)Cl - Valid: True

 35%|███▌      | 124/350 [10:53<20:18,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C=CC=C(N(C1=CC=CC=C1)C2=CC=C(C=C2)OCC3=CC=CC)C3N - Valid: True

 36%|███▌      | 125/350 [10:59<20:11,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1(CC2=C(O1)C=C(C=C2)/C=C/C(=O)OC)C3=C(C=C(C=C3)Cl)CCl - Valid: True

 36%|███▌      | 126/350 [11:04<20:06,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@H1]1[C@@H1][C@H1][C@H1][C@@H1](O1)OC2[C@@H1][C@H1][C@@H1]O[C@@H1]2COC(O)C=O - Valid: True

 36%|███▋      | 127/350 [11:10<20:03,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(N=C(C=C1)NC2CCNCC2)CC3=CC=NC=C3 - Valid: True

 37%|███▋      | 128/350 [11:15<19:56,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)N(C)C2=C(SC3=C2C=CC(=C3)O)CC(F)(F)F - Valid: True

 37%|███▋      | 129/350 [11:20<19:51,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)CCNC2=C(C=C(C=C2)CNC=O)CCN(C)CC - Valid: True

 37%|███▋      | 130/350 [11:26<19:46,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=CC2=C1C=C(C=C2)CN(C)CC3=CC=C(C=C3)CC[N+1](=O)CC=CC(C)CC - Valid: True

 37%|███▋      | 131/350 [11:31<19:40,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=CC2=C1C3=C(S2)C=C(C=C3)OCO)C(=O)/C=C/C4=CC=C5C=C4NC=C5C=CCC - Valid: True

 38%|███▊      | 132/350 [11:37<19:35,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=CC=C1N2CCN(CC2)C3=NC=C(C=C3)CNC(=O)C4=CC=CC=C4 - Valid: True

 38%|███▊      | 133/350 [11:42<19:31,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)N/C=C/C1=CC=C(C=C1)O[C@H1](CO2)COC(=O)/C=C/C=CC=C(NC=C2)SCl - Valid: True

 38%|███▊      | 134/350 [11:47<19:24,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'Cl]'
	SELFIES: [C][C][O][C][=Branch1][C][=O][/C][=C][/C][=Branch1][=N][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][Br][C][=C][Branch1][#Branch2][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][Br][C][=C][Branch1][C][C][C][C][C][=C][C][=C][Branch1][Branch1][Branch1][C][=C][C][=C][Ring1][=Branch1][C]Cl]

 39%|███▊      | 135/350 [11:53<19:18,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NCC3=C4C(=C(C=C3)C4)Cl - Valid: True

 39%|███▉      | 136/350 [11:58<19:13,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)C2(CCC2)NC(=O)OC(C)(C)CC - Valid: True

 39%|███▉      | 137/350 [12:04<19:08,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1=C(C(=CC=C1)OC(=O)/C=C/C2=CC=C(C=C2)O)OOCCC(=O)OC(C)CCC - Valid: True

 39%|███▉      | 138/350 [12:09<19:02,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=C(SC3=C2C=CC(=C3)OC)OC/C=C/C(C)OOC - Valid: True

 40%|███▉      | 139/350 [12:14<18:58,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol ']]'
	SELFIES: [C][C][Branch1][C][C][Branch1][C][C][O][C][=Branch1][C][=O][N][/C][=Branch2][Ring2][=C][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O][C@H1][Branch1][Branch1][C][O][Ring1][Branch2][C][=Branch1][C][=O][C][O][C][=Branch1][C][=Branch1][C][=C][C][C][=C][C][C][=C][C][=C][Ring1][=Branch1][N][C][=Branch1][=C][C][N][Branch1][Branch1][C][C][C][C][C][C][C]]]][C]]

 40%|████      | 140/350 [12:20<18:52,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N([C@@H1]2CCN(C2)CC3=CC=C(C=C3)Cl)CF - Valid: True

 40%|████      | 141/350 [12:25<18:45,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1/C=C/C(=O)OCCC2=C(C(=C(C=C2)Cl)Cl)Cl - Valid: True

 41%|████      | 142/350 [12:30<18:40,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/C1=CC=C(C=C1)C2=C(SC3=C2C=CC(=C3)OC/4)NC(=O)C=CS4C=C5C=CC(=N)N5CN - Valid: True

 41%|████      | 143/350 [12:36<18:36,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C(C)C1=CC=C(C=C1)C2=CC=C(C=C2)C(=O)N/N=C/C3=C(C=CC(=C3)C)C#CC - Valid: True

 41%|████      | 144/350 [12:41<18:30,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)S)Cl - Valid: True

 41%|████▏     | 145/350 [12:47<18:25,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(S1)NC(=O)OC(C)(C)CC)C=O - Valid: True

 42%|████▏     | 146/350 [12:52<18:20,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C][C][Branch2][=Branch1][S][C][Branch2][Branch1][O][C][Branch2][=Branch1][=Branch1][C][Branch1][Ring2][O][Ring1][=Branch1][O][C][C][Branch2][Branch1][=Branch1][O][C][Ring1][=Branch2][O][C][C][Branch2][Ring1][=Branch1][O][C][Branch1][=Branch1][C][C][Branch1][C][C][C][C][C][=C][O][C][=Branch1][C][=C][C][=C][C][C][=Branch1][C][C][=Branch1][C][C][=C][C][C][C]C][C]C][C]C]

 42%|████▏     | 147/350 [12:57<18:14,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CC(=O)NCCC.C=CC(=O)OCC1=CC=CC=C1 - Valid: True

 42%|████▏     | 148/350 [13:03<18:09,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 43%|████▎     | 149/350 [13:08<18:04,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=CC=C1)C2=CN=C(S2)C=C(C=C)OC=CC3=C(C=CC=C3)F - Valid: True

 43%|████▎     | 150/350 [13:14<17:59,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)C)S(=O)(=O)NC(=S)SC=C(C=CC(=O)C(F)(F)F)CF - Valid: True

 43%|████▎     | 151/350 [13:19<17:51,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)C=CC(=CN2CC3=CC=C(C=C3)C=CCC=CF)F - Valid: True

 43%|████▎     | 152/350 [13:24<17:46,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C@H1][C][C@@H1][Branch2][=Branch1][P][C@H1][Branch2][=Branch1][N][C@H1][Branch2][=Branch1][#Branch1][C@@H1][Branch1][Ring2][O][Ring1][=Branch1][O][C@@H1][C@H1][Branch2][Branch1][#Branch1][C@@H1][Branch2][Ring2][O][C@@H1][Branch2][Ring2][P][C@@H1][C][=C][Branch2][Ring2][Ring1][#Branch1][C][=C][C][=Branch2][C][C][=Branch1][C][C][=Branch1][C][C][C][C][=Branch1][C][C][C][C][C][C][C][C][C]C]C]C]C][=C]=C][C][C][=C][C][=C][C]C][=Branch1][C][C][=C][C][C][C][=C][C][C][C][=C][Ring1][C][Ring1][=Branch1][C][C][Ring1][=C][C][C]O]

 44%|████▎     | 153/350 [13:30<17:41,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '014]'
	SELFIES: [C][C][=C][C][=Branch2][Branch1][=Branch2][=C][Branch1][Branch1][C][=N][Ring1][=Branch1][N][Branch2][Ring1][=Branch2][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][N][C][=Branch2][Ring1][=Branch1][C][=C][Branch1][=C][C][C][=Branch1][C][C][=C][C][C][=C][C][=C][C][=C][Ring1][=C][=Branch1][C][=N][/C][=C][/C][=C][=C][/C][=C][/C][=C][=Branch1][C][C][=C][C][=C][Ring1][=Branch1][#Branch1][C][C]014][=C]

 44%|████▍     | 154/350 [13:35<17:34,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC1=C2C3=C(C=C1)C=C(C=C3)C(=O)NC=CC(=C2C4=CC=CC(=N4)CC)CCC - Valid: True

 44%|████▍     | 155/350 [13:41<17:29,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC=CN(C1=CC=CC(=C1C)C=O)CC(C)(C)F - Valid: True

 45%|████▍     | 156/350 [13:46<17:25,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=CC(=C(C=C3C)CC4)CC4N - Valid: True

 45%|████▍     | 157/350 [13:51<17:19,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)/C=C/C(=O)OC2=C(C=C(C=C2)/C=C/C(=O)NC3=CC=CC=C3S4C=CCC=C4)C - Valid: True

 45%|████▌     | 158/350 [13:57<17:15,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@H1]1[C@@H1][C@H1][C@H1][C@@H1](O1)OC=C(OC2=CC(=C(C=C2)OCOCC)/C)C/C(=O)CCC - Valid: True

 45%|████▌     | 159/350 [14:02<17:09,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC=CC1=CC=CC(=C12)C=C3C4=CC2=C(C=C4C=CC=CC=C3)C - Valid: True

 46%|████▌     | 160/350 [14:07<17:03,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C3=C(C=C2)C=C(C=C3)OCOC=CC=CCC)CCF - Valid: True

 46%|████▌     | 161/350 [14:13<16:58,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC1=CC=C(C=C1)/C=C/C(=O)OC2=CC=C(C=C2)/C=C/C(=O)OCC=CC=CC=CC=C - Valid: True

 46%|████▋     | 162/350 [14:18<16:53,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=CC2=C1OC(C2CO)C3=CC(=C(C=C3)O)OC/C=C/C=CC(=C=CC)F - Valid: True

 47%|████▋     | 163/350 [14:24<16:48,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)CN2CC)N(CC2)C3=NC=C(C=C3)C=NC4=CC=CC=C4 - Valid: True

 47%|████▋     | 164/350 [14:29<16:42,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCOC(=O)C(=C)C1=CC=C(C=C1)OCOC(=O)C=C - Valid: True

 47%|████▋     | 165/350 [14:34<16:37,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)C3=CC=CC=C3)CCC - Valid: True

[11:46:07] Conflicting single bond directions around double bond at index 2.
[11:46:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
 47%|████▋     | 166/350 [14:40<16:32,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C(=C(/C1=CC=C(C=C1)/C=C/C(=O)OCC)/C2=CC=C(C=C2)C3=NC=CC=C3/C=C/C(=O)O)C - Valid: True

 48%|████▊     | 167/350 [14:45<16:28,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=C.CC(C)OC(=O)C(=C)C.CC(C)OC(=O)/C=C/C=C/C(=O)OCCC(C)CCC - Valid: True

 48%|████▊     | 168/350 [14:51<16:22,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCNC(=O)N(CCC1=CC=CC(=C1)C2=C)C=C(C=C2)/C=C/C(=O)OCCC - Valid: True

 48%|████▊     | 169/350 [14:56<16:15,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol ']Ring1]'
	SELFIES: [C][C][Branch1][C][C][Branch1][C][C][O][C][=Branch1][C][=O][/C][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][/C][=C][/C][=Branch1][C][=O][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=C][C][=C][C][=C][C][=C][Ring1][=Branch1][O][C][=C][C][C][C][=C][Ring1][=Branch1][C][=C][Ring1][C][=C][C][=C]]Ring1]

 49%|████▊     | 170/350 [15:01<16:10,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=CC=C(C=C1)C(=O)CCC(=O)N(C2=CC=C3C=C2C=C(C=C3)OCC(=N)C=C)C=CC(=N)C#CF - Valid: True

 49%|████▉     | 171/350 [15:07<16:04,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=CC=C(C=C1)S(=O)(=O)NC2=C(C=C(C=C2)/C=C(/C=CC(=O)OCF)CCCC)CC - Valid: True

 49%|████▉     | 172/350 [15:12<15:59,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)NC1=C(C=CC(=C1)C(=O)NC2=C(C=C(C=C2)C=C(C)CCCF)C=CCF)CF - Valid: True

 49%|████▉     | 173/350 [15:18<15:54,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC2=C(C=C(C=C2)CCCNC)C=O - Valid: True

 50%|████▉     | 174/350 [15:23<15:49,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC1=CC=C(C=C1)C2=C(C3=C(S2)C=C(C=C3)OC(=O)C)CC=CC4=C(C=CC=C4)F - Valid: True

 50%|█████     | 175/350 [15:28<15:43,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCOC(=O)C=CC.CCCCCOC(=O)C(=C)C.C=CC1=CC=C(C=C1)CF - Valid: True

 50%|█████     | 176/350 [15:34<15:38,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCOC(=O)C=CC.CCCCCOC(=O)C=C - Valid: True

 51%|█████     | 177/350 [15:39<15:32,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)C=C3NNS=C3CC4=CC=CC=C4C - Valid: True

 51%|█████     | 178/350 [15:45<15:28,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)C2=CN=C(N2)CCC3=CC=C(C=C3)C=C(C)F - Valid: True

 51%|█████     | 179/350 [15:50<15:22,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 51%|█████▏    | 180/350 [15:55<15:15,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=CC(=NOC)C1=CC=CC=C12)C=CC=C(O2)C3=CC=CC=C3/C=C/C=C/C4=C5C=CC=C4C=C5CC - Valid: True

 52%|█████▏    | 181/350 [16:01<15:11,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)Cl)CNC(=O)C2=CC=C(C=C2)C(F)(F)F - Valid: True

 52%|█████▏    | 182/350 [16:06<15:05,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C3=CC=C(C=C3)C#N - Valid: True

 52%|█████▏    | 183/350 [16:11<14:59,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCOC(=O)C(=C)C.C=CC1=CC=C(S1)CCCCC - Valid: True

 53%|█████▎    | 184/350 [16:17<14:54,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCN(CCCC1)CC=C(C=C1)/C=C/C(=O)OCC - Valid: True

 53%|█████▎    | 185/350 [16:22<14:50,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C1/C=CC(C=C1)C=NOC=C(C=N)C2=CC=C(C=C2)CCCN - Valid: True

[11:47:55] Conflicting single bond directions around double bond at index 2.
[11:47:55]   BondStereo set to STEREONONE and single bond directions set to NONE.
 53%|█████▎    | 186/350 [16:28<14:45,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C(=C(/C1=CC=C(C=C1)/C=C/C(=O)OCC)/C2=CC=C(C=C2)C(F)(F)F)N=CC=C(F)F - Valid: True

 53%|█████▎    | 187/350 [16:33<14:40,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=C(C=C(C=C1)NC=O)COC(=O)C=CNC2=CC=C(C=C2)S(=O)C(C)F - Valid: True

 54%|█████▎    | 188/350 [16:39<14:35,  5.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC(=C(C=C1/C=C/C(=O)OCC2=CN(N=N2)CCCO)CCCC)C3=CC=CC=C3C=CC - Valid: True

 54%|█████▍    | 189/350 [16:44<14:29,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C(=O)NCCC1=CC(=CC(=C1)C(F)(F)F)C2=CC=C(C=C2)/C=C/C(=O)OCCC(C)CCC - Valid: True

[11:48:17] Conflicting single bond directions around double bond at index 2.
[11:48:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
 54%|█████▍    | 190/350 [16:49<14:23,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C=C(/C1=CC=C(C=C1)/C=C/C(=O)OCC)/C2=CC=C(C=C2)OC/C=C/C(=O)OCC - Valid: True

 55%|█████▍    | 191/350 [16:55<14:19,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N2C=C(C=C2CC3=CC=CC=C3/C)C(/C(=O)OC)/CBr - Valid: True

 55%|█████▍    | 192/350 [17:00<14:13,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCCOC(=O)C(=C)C.C=CC=CC(=O)Cl - Valid: True

 55%|█████▌    | 193/350 [17:05<14:07,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)C=C(C=CCC=C)F - Valid: True

 55%|█████▌    | 194/350 [17:11<14:01,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC2=C(SC3=C2C=CC(=C3)OC)SCCC4=C=CNC4C=CC=CC - Valid: True

 56%|█████▌    | 195/350 [17:16<13:56,  5.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC=C1C2=NN(C=N2)C3=C(C=C(C=C3)Cl)C(F)(F)F - Valid: True

 56%|█████▌    | 196/350 [17:22<13:50,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C2=C1)C=CN=C2 - Valid: True

 56%|█████▋    | 197/350 [17:27<13:44,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC(=C(C1=NC=C(N1)C2=CC=CC=C2)C(C3=CC=CC=C3)C4=CC=C)C=C4 - Valid: True

 57%|█████▋    | 198/350 [17:32<13:39,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCN(C1=C(C=CC(=C1)C=CC=O)OCC2=CC=C(C=C2)/C=C/C(=O)OC)CC[N+1](C)OCCCCN - Valid: True

 57%|█████▋    | 199/350 [17:38<13:29,  5.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/C1=CC=C(C=C1)C=C(C2=CC3=C(C=C2)F)C(=O)C4=CC=CC=C4SC=C3 - Valid: True

 57%|█████▋    | 200/350 [17:43<13:04,  5.23s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C=CC(=C2)C)CC(=O)OCCC=CC=C(C=CCF)C=CF - Valid: True

 57%|█████▋    | 201/350 [17:48<12:47,  5.15s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol ']]'
	SELFIES: [C][=C][C][=Branch1][C][=O][O][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][S][=Branch1][C][=O][=Branch1][C][=O][N][Branch1][S][C][C][C][=N][N][C][=C][C][=C][C][=C][Ring1][=Branch1][Ring1][=Branch2][C][=Branch1][C][=O][C][=Branch1][C][=C][C][=C][C][=C][C][Ring1][=Branch1][Ring1][=Branch1]]]]

 58%|█████▊    | 202/350 [17:53<12:34,  5.10s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=CC=C1)CNC(=O)C2=CC=C(C=C2)C3=CC=C(C=C3)CCCCC - Valid: True

 58%|█████▊    | 203/350 [17:58<12:22,  5.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)C3=CC=CC=C4NSCC4(N)CC=C3 - Valid: True

 58%|█████▊    | 204/350 [18:03<12:14,  5.03s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=C(C=C(C=C1)/C=C/C(=O)OCCC=CNC2=CC=C(C=C2)Cl)Cl - Valid: True

 59%|█████▊    | 205/350 [18:08<12:09,  5.03s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCOC(=O)/C=C/C1=CC=C(C(=C1)C(C)(C)C)C/C=C/C=C/C=CC2=CO2 - Valid: True

 59%|█████▉    | 206/350 [18:13<12:00,  5.00s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCC1C(C2=CC=CC=C2)C3=CC=C(C=C3)C=C1C4=CC=C(C=C4)COC - Valid: True

 59%|█████▉    | 207/350 [18:17<11:51,  4.98s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC(=C1C=NC2=CC=CC=C2C1(C)CC(=O)OCCOC=O)C=CC - Valid: True

 59%|█████▉    | 208/350 [18:22<11:46,  4.97s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1COC(=O)C=CC2=C(C=C(C=C23)N4C(=O)OC=C3C5=CC=CC=C5C=C4OC6)CC=CC=C61 - Valid: True

 60%|█████▉    | 209/350 [18:27<11:41,  4.97s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC(=C1)C(=CC(=O)OCC2)CC=C(C=C2)NC(=O)C3=CC=CC=C3C - Valid: True

 60%|██████    | 210/350 [18:32<11:34,  4.96s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(N=C(C=C1)Br)NC(=O)C2=CC=C(C=C2)CC=CCC=C(C=CF)C=NF - Valid: True

 60%|██████    | 211/350 [18:37<11:30,  4.97s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)C3=CC=C(C=C3)C(C)CC - Valid: True

 61%|██████    | 212/350 [18:42<11:28,  4.99s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=CC(=C1)C(=O)C(C)(C)CC=NNCCC=CC=CC(=C)F - Valid: True

 61%|██████    | 213/350 [18:47<11:24,  5.00s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(C2=C1Cl)Cl)F)O)C=NC=CC=C(C=C2)F - Valid: True

 61%|██████    | 214/350 [18:52<11:19,  5.00s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCC1CCC(CC1)C(=O)C2=CC3=CC(=CC=C3)C=C2C=CNC=CC(C)C(C4=CCCC)=C4F - Valid: True

 61%|██████▏   | 215/350 [18:57<11:01,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C(=CC=C1)C)NOC[C@H1](C)C2=CC=C(C=C2)/C=C/C(=O)OC - Valid: True

 62%|██████▏   | 216/350 [19:02<10:43,  4.80s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCOC(=O)C=C.CC(C)CCCCCCCCCCOC(=O)C(=C)C=CCOCC - Valid: True

 62%|██████▏   | 217/350 [19:06<10:26,  4.71s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC=NC1=C(C=C(C=C12)NC3=CC=CC=C3)C2=O - Valid: True

 62%|██████▏   | 218/350 [19:11<10:14,  4.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '=C]'
	SELFIES: [C][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][S][=Branch1][C][=O][=Branch1][C][=O][O][C][C][Branch2][Ring2][#Branch1][C][O][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=C][Branch1][Branch1][C][=C][Ring1][Branch2][O][C][O][C][=Branch1][C][=O][C][C][=Branch1][C][C][C][C][C][C][C]=C]

 63%|██████▎   | 219/350 [19:15<10:17,  4.71s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC1=NN(C=C1)C2=C(C=C)C=C(C=C2)C3=CC=C(C=C3)C(C=NC=C4C=O)(C)CC4CF - Valid: True

 63%|██████▎   | 220/350 [19:20<10:13,  4.72s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C(=C)CC1=CC=CC=N1 - Valid: True

 63%|██████▎   | 221/350 [19:25<10:02,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(CCC=C(C1(C(C(=CC(=C1F)F)F)C2=CC=CC=C2)F)C=CC)=O.CCCF.CC=C - Valid: True

 63%|██████▎   | 222/350 [19:29<09:58,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)/C=C/C(=O)OC(C)(C)COCC=C - Valid: True

 64%|██████▎   | 223/350 [19:34<09:47,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC1CC2=CC=CC=C2C=C1 - Valid: True

 64%|██████▍   | 224/350 [19:38<09:38,  4.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CSC(=N1)Br - Valid: True

 64%|██████▍   | 225/350 [19:43<09:37,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC1=NC(=C(C=C1)/C=C/C(=O)OCC2=NN(C=N2)CC3=CC=CC=C3)N - Valid: True

 65%|██████▍   | 226/350 [19:48<09:31,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)O.CC(=C)C(=O)OCCO - Valid: True

 65%|██████▍   | 227/350 [19:52<09:29,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCCCCCCS - Valid: True

 65%|██████▌   | 228/350 [19:57<09:20,  4.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=C(C=C1)Br)O - Valid: True

 65%|██████▌   | 229/350 [20:01<09:12,  4.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)NC23CCN(CC2)C(=CC(=O)C=C3CC=CC(=C)CN)CF - Valid: True

 66%|██████▌   | 230/350 [20:06<09:05,  4.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC=NC=NC=CN - Valid: True

 66%|██████▌   | 231/350 [20:10<08:58,  4.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C=C3C(=C2)C(=CC=C3)C#N)OC - Valid: True

 66%|██████▋   | 232/350 [20:15<08:53,  4.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(C=C1)C(C)(C)C - Valid: True

 67%|██████▋   | 233/350 [20:19<08:47,  4.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)C)SCNC(=O)C=CC2=CN=C(C=C2)C(CF)N - Valid: True

 67%|██████▋   | 234/350 [20:24<08:42,  4.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/NCC1=CC=CC=C1 - Valid: True

 67%|██████▋   | 235/350 [20:28<08:37,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCC1CCC(CC1)C(=O)OC2=CC=CC=C2/C=C/C(=O)OCC=CC=CCC(C)=C(CCCC)CCCCCCl - Valid: True

 67%|██████▋   | 236/350 [20:33<08:32,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=CC(=O)NC1=CC=C(C=C1)S(=O)(=O)NC(=O)C2=CC=C(C=C2)OCSC(C)CCC)CCC - Valid: True

 68%|██████▊   | 237/350 [20:37<08:28,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCC1CCC(CC1)C(=O)OC=CC2=CC=C(C=C2)NC=C3C=C(C=C3)OCC=N - Valid: True

 68%|██████▊   | 238/350 [20:42<08:23,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(F)F)C=C1C(C2=C(S1)C=C(C=C2)C3=CC=CC=C3)F - Valid: True

 68%|██████▊   | 239/350 [20:46<08:19,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=NC=C1)N=C=NC=CC(=C)C(F)(F)F - Valid: True

 69%|██████▊   | 240/350 [20:51<08:17,  4.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)Cl)/C(=O)C2=CC=CC=C2 - Valid: True

 69%|██████▉   | 241/350 [20:56<08:19,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)C=O - Valid: True

 69%|██████▉   | 242/350 [21:00<08:18,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=C(C=C1)O)OC2=CC=CC=C2C=CC(=O)OC - Valid: True

 69%|██████▉   | 243/350 [21:05<08:16,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1COC(=O)C1=CNC2=CC=C(C=C2)OCC=CC=CC=C - Valid: True

 70%|██████▉   | 244/350 [21:10<08:16,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CSC(=N1)NC2=NC=C(C(=C2)OC3=CC=CC4=CC=CC=C43)OC(=O)C=C - Valid: True

 70%|███████   | 245/350 [21:15<08:18,  4.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC1=CC=CC(=C1C(C2=CC=CC=C2)OCOC=O)C=CC(C)(C)CCCC - Valid: True

 70%|███████   | 246/350 [21:19<08:11,  4.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC1=NC=C(N1C)C2=CC=CC=C2 - Valid: True

 71%|███████   | 247/350 [21:24<08:02,  4.69s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC1=CC=C(C=C1)OC(=O)C=C - Valid: True

 71%|███████   | 248/350 [21:29<07:57,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C(/C1=CC=C(C=C1)C#N)CC=C(C=C)OC/C(=O)OCC - Valid: True

 71%|███████   | 249/350 [21:33<07:52,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C1=CC(=CC=C1)C(=O)C(=CO)CC2=CC(=C(C=C2Br)F)Cl - Valid: True

 71%|███████▏  | 250/350 [21:38<07:48,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=CN=C(S2)CC3=CC=CC=C3 - Valid: True

 72%|███████▏  | 251/350 [21:43<07:38,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)OC(C)(C)CC - Valid: True

 72%|███████▏  | 252/350 [21:47<07:29,  4.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC=CC3=CC=C)C=C32 - Valid: True

 72%|███████▏  | 253/350 [21:52<07:25,  4.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C(F)(F)F)C2=CC=C(C=C2)C - Valid: True

 73%|███████▎  | 254/350 [21:56<07:17,  4.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=CC=C(C=C1)N - Valid: True

 73%|███████▎  | 255/350 [22:01<07:11,  4.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N([C@@H1]2CCN(C2)C(=O)C3=CC=C(C=C3)OCCSC)OC - Valid: True

 73%|███████▎  | 256/350 [22:05<07:08,  4.55s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=CC1=C(C(=C(C=C1)OC)C)OCC(=O)OCCNC(=O)CC)C=CCCCC - Valid: True

 73%|███████▎  | 257/350 [22:10<07:07,  4.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCSCCOC(=O)C=C.C=CC(=O)OCCOC(=O)C=C.C=CC(=O)OC1CCCO1 - Valid: True

 74%|███████▎  | 258/350 [22:15<07:03,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=COC=C1 - Valid: True

 74%|███████▍  | 259/350 [22:19<07:00,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1CCCOC(=O)C=C.CC(=C)C(=O)OC=C.C=CC(=O)OCCOC(=O)C=C.C=CC(=O)OCCC=CC=CC2C=C21 - Valid: True

 74%|███████▍  | 260/350 [22:24<06:55,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C(=O)C2=CC=C(C=C2)Br - Valid: True

 75%|███████▍  | 261/350 [22:28<06:49,  4.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC=NCCN(C)CCOC(=O)C=CC1=CC=C(C=C1)C2=CC=C(C=C2)F - Valid: True

 75%|███████▍  | 262/350 [22:33<06:44,  4.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C1=CC=CC=C1C=C(C#N)OC)COC(=O)C=CC2=CC=C(C=C2)OC - Valid: True

 75%|███████▌  | 263/350 [22:37<06:38,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=C(C=C1)S(=O)(=O)NC2=CC(=C(C=C2)OC)COCC)C - Valid: True

 75%|███████▌  | 264/350 [22:42<06:37,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=CC=C(C=C1)OC)CO/NC(=O)C2=CC=C(C=C2)OC - Valid: True

 76%|███████▌  | 265/350 [22:47<06:35,  4.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@@H1]1CC=C([C@H1](N1CC(C)(C)F)C2=CC=C(C=C2Cl)/C=C/C(=O)OCC)OC - Valid: True

 76%|███████▌  | 266/350 [22:52<06:45,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC(C)COC(=O)C=C.C=CC(=O)O - Valid: True

 76%|███████▋  | 267/350 [22:57<06:50,  4.95s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N=CN=C1NCCC2=CC=CC=C2)NC(=O)CSC - Valid: True

 77%|███████▋  | 268/350 [23:03<06:54,  5.06s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=CSC(=N2)C=CN(C)CC - Valid: True

 77%|███████▋  | 269/350 [23:08<06:56,  5.14s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1=CC(=CC2=C1N(C3=C2C=C(C=C3)I)CCO)C(=O)C=C - Valid: True

 77%|███████▋  | 270/350 [23:13<06:53,  5.17s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=C(SC3=C2C=CC(=C3)O)C - Valid: True

 77%|███████▋  | 271/350 [23:18<06:49,  5.18s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=CC(=C1)OCCC#N - Valid: True

 78%|███████▊  | 272/350 [23:24<06:45,  5.20s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC(COC(=O)C=C)OC(=O)C=C - Valid: True

 78%|███████▊  | 273/350 [23:29<06:41,  5.21s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C(C)C)[N+1](=O)[O-1] - Valid: True

 78%|███████▊  | 274/350 [23:34<06:36,  5.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)OC(=O)C=CC2=CC(=C(C(=C2)O)O[N+1])C=O - Valid: True

 79%|███████▊  | 275/350 [23:39<06:30,  5.21s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)N - Valid: True

[11:55:12] Conflicting single bond directions around double bond at index 2.
[11:55:12]   BondStereo set to STEREONONE and single bond directions set to NONE.
 79%|███████▉  | 276/350 [23:44<06:13,  5.04s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C=C(/C1=CC=C(C=C1)/C=C/C(=O)OCC)/C2=CC=C(C=C2)F - Valid: True

 79%|███████▉  | 277/350 [23:49<05:56,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+1](=O)[O-1])/C#N - Valid: True

 79%|███████▉  | 278/350 [23:53<05:43,  4.77s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCCCCCCCCCCCF - Valid: True

 80%|███████▉  | 279/350 [23:58<05:33,  4.69s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CNC1=CC=C(C=C1)C)C(=O)OCC2=CC=CC=C2 - Valid: True

 80%|████████  | 280/350 [24:02<05:24,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(N=C1N)CN - Valid: True

 80%|████████  | 281/350 [24:07<05:17,  4.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCN(CC)CC(=O)OC(=C)C(=O)OCC - Valid: True

 81%|████████  | 282/350 [24:11<05:11,  4.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1CN(CCC1C2=CC=CC=C2)CC(=C)C(=O)OC - Valid: True

[11:55:43] Conflicting single bond directions around double bond at index 9.
[11:55:43]   BondStereo set to STEREONONE and single bond directions set to NONE.
 81%|████████  | 283/350 [24:16<05:05,  4.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC1=CC(=CC=C1)N/C=C(/C#N)/C(=O)OCC - Valid: True

 81%|████████  | 284/350 [24:20<04:59,  4.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)OC(C)(C)CC - Valid: True

 81%|████████▏ | 285/350 [24:25<04:54,  4.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(O1)C2=CC=C(C=C2)Br)/C#N - Valid: True

 82%|████████▏ | 286/350 [24:29<04:49,  4.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC(=O)N(C)C=CC(=O)OC - Valid: True

 82%|████████▏ | 287/350 [24:34<04:45,  4.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CC#N - Valid: True

 82%|████████▏ | 288/350 [24:38<04:40,  4.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=CC1=C(C=C(C=C1)C#N)OCCN)C(=O)OC - Valid: True

 83%|████████▎ | 289/350 [24:43<04:36,  4.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CNC1=CC(=CC=C1)C(F)(F)F)N2C(=O)C3=CC=CC=C3C2 - Valid: True

 83%|████████▎ | 290/350 [24:47<04:31,  4.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=C.C=CC(=O)O.C=CC(=O)OCCO - Valid: True

 83%|████████▎ | 291/350 [24:52<04:32,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCSCC(C(C(C(F)(F)F)F)F)F - Valid: True

 83%|████████▎ | 292/350 [24:57<04:29,  4.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCSC1=CC=CC=N1 - Valid: True

 84%|████████▎ | 293/350 [25:01<04:25,  4.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC=CC(=CC)OCC(=C)C(=O)OC - Valid: True

 84%|████████▍ | 294/350 [25:06<04:19,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C(C)(C)C - Valid: True

 84%|████████▍ | 295/350 [25:11<04:16,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C=CC1=CC=CC=C1N2CCN(C2=O)C3=CC=C(C=C3)C(F)F - Valid: True

 85%|████████▍ | 296/350 [25:15<04:12,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C(=O)NC1=NC=CC(=C1)C2=NC(=CS2)C3=CN=C(N=C3)CC=CC(=O)OC - Valid: True

 85%|████████▍ | 297/350 [25:20<04:07,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C#N - Valid: True

 85%|████████▌ | 298/350 [25:25<04:00,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OC(=O)C - Valid: True

 85%|████████▌ | 299/350 [25:29<03:55,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCC(OC(=O)C=C)O.CCCCCOC(=O)C=C.CC(=C)C(=O)OC - Valid: True

 86%|████████▌ | 300/350 [25:34<03:56,  4.74s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=C(C=C1)OCC=O)C2=CC=C(C=C2)OCOC - Valid: True

 86%|████████▌ | 301/350 [25:39<03:52,  4.74s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)NCCOC(=O)C=C.C=CC(=O)OCC(F)(F)F - Valid: True

 86%|████████▋ | 302/350 [25:44<03:46,  4.71s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=CC=CS1/C2)CC=C(C=C2)C - Valid: True

 87%|████████▋ | 303/350 [25:48<03:42,  4.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)OC)/NC(=O)C2=CC=CC=C2 - Valid: True

 87%|████████▋ | 304/350 [25:53<03:35,  4.69s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC1=CC(=CC(=C1)C(F)(F)F)C(=O)OC - Valid: True

 87%|████████▋ | 305/350 [25:58<03:30,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)COC(=O)/C=C/C2=C(C=C(C=C2)O)Cl - Valid: True

 87%|████████▋ | 306/350 [26:02<03:24,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)C1=CC=C(C=C1)S(=O)(=O)NCC2=CC=CC=C2NC(=O)C=CC=CN - Valid: True

 88%|████████▊ | 307/350 [26:07<03:19,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C#N - Valid: True

 88%|████████▊ | 308/350 [26:11<03:14,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCCCOOC=C2)PC=C(C=N2)C(F)(F)F - Valid: True

 88%|████████▊ | 309/350 [26:16<03:10,  4.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=C(C(=C(C=C2)Cl)C3)NC=CC=C3 - Valid: True

 89%|████████▊ | 310/350 [26:21<03:04,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '#Br]'
	SELFIES: [C][=C][C][=Branch1][C][=O][O][C][C][C][C][C][C][Branch2][Branch2][#Branch1][C][Branch2][Branch1][#C][C][Branch2][Branch1][#Branch1][C][Branch2][Ring2][#C][C][Branch2][Ring2][#Branch1][C][Branch2][Ring1][#C][C][Branch2][Ring1][#Branch1][C][Branch1][C][C][Branch1][C][C][C][C][C][C][=C][Branch2][Ring1][=Branch1][C][C][C][=C][Branch1][C][C][C][C][C][C]#Br]

[11:57:53] Conflicting single bond directions around double bond at index 7.
[11:57:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
 89%|████████▉ | 311/350 [26:25<03:00,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)/C=C(/C#N)/C(=O)OCC2=CC=C(C=N2)C(F)(F)F)F - Valid: True

 89%|████████▉ | 312/350 [26:30<02:55,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CC1=CC=CC=C1.C=CC(=O)OC2=CC=C(C=C2)O - Valid: True

 89%|████████▉ | 313/350 [26:35<02:51,  4.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOP(=O)(CCC(=C)C(=O)O)COCC.C=CC(=O)OCC(F)(F)F - Valid: True

[11:58:07] Conflicting single bond directions around double bond at index 3.
[11:58:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
 90%|████████▉ | 314/350 [26:39<02:47,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN(C)/C(=C(/C#N)/C(=O)OCC)C/C(=O)OC - Valid: True

[11:58:12] Conflicting single bond directions around double bond at index 5.
[11:58:12]   BondStereo set to STEREONONE and single bond directions set to NONE.
 90%|█████████ | 315/350 [26:44<02:44,  4.71s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C(/C1=CC=CN=C1)/O)/C(=O)C2=CC=CC=C2 - Valid: True

 90%|█████████ | 316/350 [26:49<02:38,  4.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC1=CC=C(C=C1)N/C=C/C(=O)OCC/C2=CC=C(C=C2)C#N - Valid: True

 91%|█████████ | 317/350 [26:53<02:33,  4.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)OC.C=CC1=CC=CC=C1.C2=CC(=O)OC2=O - Valid: True

 91%|█████████ | 318/350 [26:58<02:27,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C2=C(C3=C(S2)C=C(C=C3)OC)C=O - Valid: True

 91%|█████████ | 319/350 [27:02<02:22,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 91%|█████████▏| 320/350 [27:07<02:18,  4.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC2=C(O1)C=CC(=C2)C#N)CC=C(C=C)C(F)F - Valid: True

 92%|█████████▏| 321/350 [27:12<02:14,  4.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1=CC=C(C=C1)OC(=O)/C=C/C2=CC(=C(C=C2)O)O - Valid: True

 92%|█████████▏| 322/350 [27:17<02:11,  4.69s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC(=O)N(C)CC1=CC(=CC=C1)C(F)(F)F - Valid: True

 92%|█████████▏| 323/350 [27:21<02:06,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCC(CC)COC(=O)C=C - Valid: True

 93%|█████████▎| 324/350 [27:26<02:03,  4.76s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)Br)F - Valid: True

 93%|█████████▎| 325/350 [27:31<02:01,  4.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC(C=C1C=C(C=CN1O)C(F)F)F - Valid: True

 93%|█████████▎| 326/350 [27:36<01:57,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CNC2=C1C=CN=C2 - Valid: True

 93%|█████████▎| 327/350 [27:43<02:06,  5.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CC2=CC=C(C=C2)O - Valid: True

 94%|█████████▎| 328/350 [27:49<02:00,  5.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC1=NN(C(=C1/C=C/C(=O)OCCCN)C2=CC=C(C=C2)C(F)F)F - Valid: True

 94%|█████████▍| 329/350 [27:55<02:03,  5.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC=C(C2=CC=CC(=C2)OCO)C - Valid: True

[11:59:35] Conflicting single bond directions around double bond at index 5.
[11:59:35]   BondStereo set to STEREONONE and single bond directions set to NONE.
 94%|█████████▍| 330/350 [28:08<02:36,  7.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/N)/NC1=CC=C(C=C1)OC=C(C=C)OC(=O)C2=CC=C(C=C2)OCN - Valid: True

 95%|█████████▍| 331/350 [28:14<02:16,  7.20s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOCCOC1=CC=C(C=C1)C2=CC(=C(C=C2)N(CC(F)F)F)C=O - Valid: True

 95%|█████████▍| 332/350 [28:19<02:01,  6.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)F)Cl - Valid: True

 95%|█████████▌| 333/350 [28:26<01:53,  6.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)NC1=C(C=NC=C1)/C=C/C(=O)OC - Valid: True

 95%|█████████▌| 334/350 [28:31<01:39,  6.21s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C(=C)C1=CC2=C(C=C1)OCO2 - Valid: True

 96%|█████████▌| 335/350 [28:36<01:29,  5.95s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[==C]'
	SELFIES: [C][O][C][=Branch1][C][=O][/C][=C][/C][=C][Branch1][=Branch1][S][C][=C][Ring1][Branch1][C][=C][C][==C][Branch1][Branch1][C][=C][Ring1][=Branch1][C]

 96%|█████████▌| 336/350 [28:42<01:20,  5.78s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C=CC(=C(C)CC=O)N(C=O)C1=CC=C(C=C1)OCCC(=C)C(C)CF - Valid: True

 96%|█████████▋| 337/350 [28:47<01:13,  5.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(SC=C1)C=O - Valid: True

[12:00:20] Conflicting single bond directions around double bond at index 8.
[12:00:20]   BondStereo set to STEREONONE and single bond directions set to NONE.
 97%|█████████▋| 338/350 [28:52<01:06,  5.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)/C=C(/C#N)/C(=O)OCC - Valid: True

 97%|█████████▋| 339/350 [28:58<01:00,  5.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C(=O)C - Valid: True

 97%|█████████▋| 340/350 [29:03<00:54,  5.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=CC1=CC(=CC=C1)C(F)(F)F - Valid: True

 97%|█████████▋| 341/350 [29:08<00:48,  5.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CNC(=C1)C(=O)NC2=CC=C(C=C2C(=O)CC=CC3(C)CCCC3)F - Valid: True

 98%|█████████▊| 342/350 [29:14<00:43,  5.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCOC1=CC=CC=C1 - Valid: True

 98%|█████████▊| 343/350 [29:19<00:37,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC1=CC=C(C=C1)O - Valid: True

 98%|█████████▊| 344/350 [29:24<00:32,  5.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OCC=C(SC(=CC=C)C2=C(C=C(C=C2)F)F)Cl - Valid: True

 99%|█████████▊| 345/350 [29:30<00:26,  5.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=CC=C1)OCC=CC=CC=CCCC=CCCC(=C)CF - Valid: True

 99%|█████████▉| 346/350 [29:35<00:21,  5.33s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[]'
	SELFIES: [C][C][Branch1][C][C][Branch1][C][C][O][C][=Branch1][C][=O][C][=C][].[C][C][Branch1][C][C][Branch1][C][C][O][C][=Branch1][C][=O][C][=C].[C][C][=Branch1][C][=C][C][=Branch1][C][=O][O][C][C][C][C][O][Ring1][Ring1].[C][=C][C][=Branch1][C][=N][C][C][=Branch1][C][=O][C][C][C][Ring1][Ring1][=Branch1][C]

 99%|█████████▉| 347/350 [29:40<00:15,  5.33s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)C(C)C - Valid: True

 99%|█████████▉| 348/350 [29:46<00:10,  5.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)COC(=O)C=C.C1=CC=CC=C1 - Valid: True

100%|█████████▉| 349/350 [29:51<00:05,  5.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CSC(=N1)C - Valid: True

100%|██████████| 350/350 [29:56<00:00,  5.13s/it]

C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)COCC(C)O)CCC=C - Valid: True

In [7]:
smiles_test_df

                                                smiles  static_polarizability
0                                            C=CC(=O)O               0.000000
1                           CCOC(=O)C=CC1=CN=C(C=C1)Cl               0.000889
2                                           C=CC(=O)ON               0.001779
3                                        C=CC(=O)[O-1]               0.002668
4                                         C=CC(=O)OCCN               0.003557
..                                                 ...                    ...
330  CCOC(=O)C=CC1=CC(=CC=C1)OCC=CC=CC=CCCC=CCCC(=C)CF               0.305910
331                CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)C(C)C               0.307689
332                        CC(C)COC(=O)C=C.C1=CC=CC=C1               0.308578
333                          CCOC(=O)/C=C/C1=CSC(=N1)C               0.309468
334  C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)CO...               0.310357

[335 rows x 2 columns]

In [14]:
acrylate_smarts = "C=C[C](=O)O"
acrylate_mol = Chem.MolFromSmarts(acrylate_smarts)

def is_mixed_neutral_smiles(smiles: str) -> bool:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False  # or True if you want to discard invalid SMILES
    
    fragments = Chem.GetMolFrags(mol, asMols=True)
    
    if len(fragments) == 1:
        return False  # single molecule, keep
    
    all_neutral = all(sum(atom.GetFormalCharge() for atom in frag.GetAtoms()) == 0 for frag in fragments)
    
    return all_neutral  # True → multiple neutral fragments → discard

def is_acrylate(smi):
    mol = Chem.MolFromSmiles(smi)
    return mol.HasSubstructMatch(acrylate_mol) if mol else False

df_filtered = smiles_test_df[~smiles_test_df["smiles"].apply(is_mixed_neutral_smiles)].reset_index(drop=True)
df_filtered["is_acrylate"] = df_filtered["smiles"].apply(is_acrylate)

[12:04:52] Conflicting single bond directions around double bond at index 24.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 9.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 7.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 3.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 5.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 5.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 8.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 24.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 2.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 9.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 7.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 3.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 5.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 5.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:04:52] Conflicting single bond directions around double bond at index 8.
[12:04:52]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [15]:
(1 - df_filtered['smiles'].isin(df_polarizability['smiles_A']).sum()/len(df_filtered))*100

np.float64(85.94249201277955)

In [16]:
df_filtered = df_filtered.rename(columns={'smiles': 'smiles_A'})
df_filtered['chain_size'] = 0
df_filtered['id_A'] = df_filtered.index
df_filtered.to_csv('gpt_generation.csv', index=False)

# Predict

In [29]:
import torch
import pandas as pd

import sys
sys.path.append("/Users/gabriel/Documents/Apps/PolyGraphPy/")
from polygraphpy.gnn.pre_processing_old import PreProcess

# Setup
preprocess = PreProcess(
    input_csv='../polygraphpy/data/polarizability_data.csv',
    train_input_data_path='prediction_test',
    polymer_type='monomer',
    target='static_polarizability',
    gnn_output_path='./'
)

atoms_list, bonds_list = preprocess.extract_atoms_and_bonds_features_from_monomer_smiles()
atom_encoder = preprocess.make_encoder(pd.DataFrame(atoms_list).drop_duplicates().reset_index(drop=True))
bond_encoder = preprocess.make_encoder(pd.DataFrame(bonds_list).drop_duplicates().reset_index(drop=True))

model = torch.load('../polygraphpy/data/gnn_output/model_gcn.pt', weights_only=False)
print(model)

Reading GNN input file.
Extracting unique features from atoms and bonds.

100%|██████████| 26582/26582 [00:09<00:00, 2920.72it/s]

Making feature encoder.
Making feature encoder.
GCN(
  (conv1): GCNConv(75, 225)
  (conv2): GCNConv(225, 225)
  (conv3): GCNConv(225, 225)
  (lin1): Linear(in_features=225, out_features=225, bias=True)
  (lin2): Linear(in_features=225, out_features=225, bias=True)
  (lin3): Linear(in_features=225, out_features=225, bias=True)
  (output): Linear(in_features=225, out_features=1, bias=True)
)

In [31]:
from torch_geometric.data import Data

def mol_to_data(smiles):
    atoms = []
    bonds = []
    m1 = Chem.MolFromSmiles(smiles, sanitize=True)
    if m1 is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    m1 = Chem.AddHs(m1)
    
    atoms = preprocess.get_nodes_information(m1, [], chain_size=0)

    if not atoms:
        print(f"No atoms extracted for SMILES: {smiles}")
        return None
    
    df_nodes = pd.DataFrame(atoms)
    nodes_features = pd.DataFrame(atom_encoder.transform(df_nodes.drop(['idx'], axis=1)).toarray())
    x = torch.tensor(nodes_features.astype('float32').values)
    
    bonds = preprocess.get_bonds_information(m1, [])
    if not bonds:
        print(f"No bonds extracted for SMILES: {smiles}")
        return None
    df_bonds = pd.DataFrame(bonds)
    edge_index = torch.tensor([
        df_bonds.begin_idx.to_list() + df_bonds.end_idx.to_list(),
        df_bonds.end_idx.to_list() + df_bonds.begin_idx.to_list()
    ])
    
    edge_attrs = df_bonds[['type', 'is_conjugated', 'is_aromatic']]
    edge_attrs = pd.concat([edge_attrs, edge_attrs.sort_index(ascending=False)])
    edge_attr = torch.tensor(bond_encoder.transform(edge_attrs).toarray(), dtype=torch.float32)
    
    edge_weight = torch.tensor([1.0] * edge_index.shape[1], dtype=torch.float32)
    
    mol_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, edge_weight=edge_weight)
    mol_data.validate()

    return mol_data
    
df_results = pd.DataFrame()

for i in df_filtered.itertuples():
    mol_data = mol_to_data(i.smiles_A)

    with torch.no_grad():
        pred = model(mol_data.x, mol_data.edge_index, mol_data.edge_weight, torch.tensor([0])).numpy()[0][0]
    
    df_results = pd.concat([df_results, pd.DataFrame({'smiles_A': i.smiles_A, 'y': i.static_polarizability, 'pred': pred}, index=[0])]).reset_index(drop=True)

[12:14:35] Conflicting single bond directions around double bond at index 24.
[12:14:35]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:36] Conflicting single bond directions around double bond at index 2.
[12:14:36]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:36] Conflicting single bond directions around double bond at index 2.
[12:14:36]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:36] Conflicting single bond directions around double bond at index 2.
[12:14:36]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 2.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 9.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 7.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 3.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 5.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 5.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:14:37] Conflicting single bond directions around double bond at index 8.
[12:14:37]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [32]:
df_results['error'] = abs(df_results['y'] - df_results['pred'])/(df_results['y'] + 1e-12)

In [33]:
df_results

,smiles_A,y,pred,error
0,C=CC(=O)O,0.000000,0.093452,9.345245e+10
1,CCOC(=O)C=CC1=CN=C(C=C1)Cl,0.000889,0.092205,1.026857e+02
2,C=CC(=O)ON,0.001779,0.089331,4.922710e+01
3,C=CC(=O)[O-1],0.002668,0.047790,1.691341e+01
4,C=CC(=O)OCCN,0.003557,0.053466,1.403081e+01
...,...,...,...,...
308,CCOC(=O)/C=C/C1=CC=C(C=C1)OCC=C(SC(=CC=C)C2=C(...,0.305021,0.251301,1.761211e-01
309,CCOC(=O)C=CC1=CC(=CC=C1)OCC=CC=CC=CCCC=CCCC(=C)CF,0.305910,0.200039,3.460873e-01
310,CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)C(C)C,0.307689,0.144332,5.309149e-01
311,CCOC(=O)/C=C/C1=CSC(=N1)C,0.309468,0.108868,6.482093e-01
312,C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)CO...,0.310357,0.082354,7.346490e-01

In [34]:
df_results.to_csv('predict_results_from_gpt.csv', index=False)