# Train

In [8]:
import pandas as pd
import selfies as sf
from sklearn.preprocessing import MinMaxScaler

df_polarizability = pd.read_csv('../polygraphpy/data/polarizability_data.csv')

df_polarizability = df_polarizability[df_polarizability['chain_size'] == 0].reset_index(drop=True)

scaler = MinMaxScaler()
target = scaler.fit_transform(df_polarizability['static_polarizability'].values.reshape(-1,1)).flatten()

smiles_list = df_polarizability['smiles_A'].values
selfies_list = []

for i in smiles_list:
    selfies_list.append(sf.encoder(i))

In [ ]:
import selfies as sf
from rdkit import Chem

# 1. Define the SMILES string
smiles_string = "COC(=O)C=C"

# 2. Encode SMILES to SELFIES
encoded_selfies = sf.encoder(smiles_string)

# 3. Decode SELFIES back to SMILES (optional)
decoded_smiles = sf.decoder(encoded_selfies)

# 4. Print the results
print(f"Original SMILES: {smiles_string}")
print(f"Encoded SELFIES: {encoded_selfies}")
print(f"Decoded SMILES: {decoded_smiles}")

# 5. Canonicalize SMILES for robust comparison
can_smiles_original = Chem.CanonSmiles(smiles_string)
can_smiles_decoded = Chem.CanonSmiles(decoded_smiles)

print(f"RDKit Canonical SMILES (Original): {can_smiles_original}")
print(f"RDKit Canonical SMILES (Decoded): {can_smiles_decoded}")
print(f"Are canonical SMILES equal? {can_smiles_original == can_smiles_decoded}")

Original SMILES: COC(=O)C=C
Encoded SELFIES: [C][O][C][=Branch1][C][=O][C][=C]
Decoded SMILES: COC(=O)C=C
RDKit Canonical SMILES (Original): C=CC(=O)OC
RDKit Canonical SMILES (Decoded): C=CC(=O)OC
Are canonical SMILES equal? True

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
import torch
import rdkit.Chem as Chem

# Data
texts = [f"polarizability: {p} selfies: {i}" for i, p in zip(selfies_list, target)]

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = AutoModelForCausalLM.from_pretrained('gpt2')
model.resize_token_embeddings(len(tokenizer))

class InChIDataset(Dataset):
    def __init__(self, texts, tokenizer, max_len=128):
        self.encodings = tokenizer(texts, truncation=True, padding=True, max_length=max_len, return_tensors='pt')

    def __len__(self):
        return len(self.encodings['input_ids'])

    def __getitem__(self, idx):
        return {k: v[idx] for k, v in self.encodings.items()}

dataset = InChIDataset(texts, tokenizer)
loader = DataLoader(dataset, batch_size=12, shuffle=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
optimizer = AdamW(model.parameters(), lr=5e-5)

aux = 1e9

# Training
model.train()
for epoch in range(150):
    epoch_loss = 0.0

    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        optimizer.zero_grad()
        outputs = model(**batch, labels=batch['input_ids'])
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item() * batch['input_ids'].size(0)
    
    total_loss = epoch_loss / len(dataset)
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    if total_loss < aux:
        torch.save(model, 'gpt_selfies.pt')
        aux = total_loss

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

KeyboardInterrupt:

# Generate

In [1]:
from transformers import AutoTokenizer
import selfies as sf
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

model = torch.load('gpt_selfies.pt', weights_only=False)
model = model.to(device)

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from rdkit import Chem

def generate(model, tokenizer, xlogp_val, max_len=1000):
    try:
        prompt = f"polarizability: {xlogp_val} selfies:"
        inputs = tokenizer(prompt, return_tensors='pt').to(device)
        outputs = model.generate(**inputs, max_length=max_len, num_beams=1, do_sample=True, temperature=0.9, top_p=0.9)
        gen_text = tokenizer.decode(outputs[0])
        selfies = gen_text.split("selfies:")[1].strip() if "selfies:" in gen_text else None
        selfies = selfies.split('[PAD]')[0]
        selfies = selfies.replace("\\", "/")
        smiles = sf.decoder(selfies)
        valid = smiles and Chem.MolFromSmiles(smiles) is not None
        print(f"{smiles} - Valid: {valid}")
        return smiles
    except Exception as e:
        print(e)
        return None

In [3]:
import numpy as np
from tqdm import tqdm
import pandas as pd

values_vec = np.linspace(0, 1, 350)
smiles_test_df = pd.DataFrame()

for i in tqdm(values_vec):
    smiles = generate(model, tokenizer, i)
    polarizability_scaled = i

    if smiles is not None:
        smiles_test_df = pd.concat([smiles_test_df, pd.DataFrame({'smiles': smiles, 
                                                                'static_polarizability': polarizability_scaled}, index=[0])]).reset_index(drop=True)

  0%|          | 0/350 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 1/350 [00:05<29:44,  5.11s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)O - Valid: True

  1%|          | 2/350 [00:09<28:35,  4.93s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1] - Valid: True

  1%|          | 3/350 [00:14<28:02,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)ONC=O - Valid: True

  1%|          | 4/350 [00:19<27:43,  4.81s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC(CCl)(C(F)(F)F)C(F)(F)F - Valid: True

  1%|▏         | 5/350 [00:23<26:54,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN1CCOC1 - Valid: True

  2%|▏         | 6/350 [00:28<26:17,  4.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)ON1C(=O)CCC1=O - Valid: True

  2%|▏         | 7/350 [00:32<26:19,  4.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)ON1C=CC=C1 - Valid: True

  2%|▏         | 8/350 [00:37<26:40,  4.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CNC=C1 - Valid: True

  3%|▎         | 9/350 [00:42<26:52,  4.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1CC(C1)(C(F)(F)F)C(F)(F)F - Valid: True

  3%|▎         | 10/350 [00:47<26:56,  4.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC=O - Valid: True

  3%|▎         | 11/350 [00:52<26:56,  4.77s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=C - Valid: True

  3%|▎         | 12/350 [00:57<26:59,  4.79s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CN - Valid: True

  4%|▎         | 13/350 [01:01<26:59,  4.80s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C(F)(F)F - Valid: True

  4%|▍         | 14/350 [01:06<26:57,  4.81s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OC(=O)C=C - Valid: True

  4%|▍         | 15/350 [01:11<26:56,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCNC(=O)C=C - Valid: True

  5%|▍         | 16/350 [01:16<26:54,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CN.Cl - Valid: True

  5%|▍         | 17/350 [01:21<26:48,  4.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC(C(F)(F)F)(C(F)(F)F)C(F)(F)F - Valid: True

  5%|▌         | 18/350 [01:26<26:47,  4.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC(F)(F)F - Valid: True

  5%|▌         | 19/350 [01:30<26:45,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC(OC(=O)C=C)Br - Valid: True

  6%|▌         | 20/350 [01:35<26:43,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCOCCN - Valid: True

  6%|▌         | 21/350 [01:40<26:39,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C(=C)C(=O)OC)OC(=O)C=C - Valid: True

  6%|▋         | 22/350 [01:45<26:35,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=C)C(=O)OC - Valid: True

  7%|▋         | 23/350 [01:50<26:31,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN(C)CCOC(=O)C=C.Cl - Valid: True

  7%|▋         | 24/350 [01:55<26:25,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1C(C)(CCC1O)C(=O)C=C - Valid: True

  7%|▋         | 25/350 [02:00<26:22,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C1/C(C1C)N - Valid: True

  7%|▋         | 26/350 [02:05<26:18,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCOC(=O)C=CN=N - Valid: True

  8%|▊         | 27/350 [02:09<26:15,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)COC(=O)/C=C/C1CO1 - Valid: True

  8%|▊         | 28/350 [02:14<26:11,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/N(C)C)/C(=O)CC - Valid: True

  8%|▊         | 29/350 [02:19<26:07,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN1CCCCC1 - Valid: True

  9%|▊         | 30/350 [02:24<26:02,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=CC=C1 - Valid: True

  9%|▉         | 31/350 [02:29<25:59,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(COC(=O)C=C)COC(=O)C=C - Valid: True

  9%|▉         | 32/350 [02:34<25:54,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=NC=C1 - Valid: True

  9%|▉         | 33/350 [02:39<25:49,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)NC(=C)C(=O)OC - Valid: True

 10%|▉         | 34/350 [02:44<25:45,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=NC=C1 - Valid: True

 10%|█         | 35/350 [02:49<25:41,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCS(=O)(=O)CC(C(C(C(C(C(F)(F)F)(F)F)F)F)CF)F - Valid: True

 10%|█         | 36/350 [02:54<25:39,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=CC1=C(C=CC(=C1)F)[N+1](=O)[O-1] - Valid: True

 11%|█         | 37/350 [02:58<25:35,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC1=CC=C(C=C1)C=O - Valid: True

 11%|█         | 38/350 [03:03<25:32,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=CC=C1Br - Valid: True

 11%|█         | 39/350 [03:08<25:27,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=CC=C1C#N - Valid: True

 11%|█▏        | 40/350 [03:13<25:23,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(N=C1N)OC - Valid: True

 12%|█▏        | 41/350 [03:18<25:17,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CC1=C(C=CS1)C - Valid: True

 12%|█▏        | 42/350 [03:23<25:11,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1CC2CC1C3C2CC(C3)OC(=O)C=C - Valid: True

 12%|█▏        | 43/350 [03:28<25:02,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C1=C/C2=C(NC(=C2)C)C1 - Valid: True

 13%|█▎        | 44/350 [03:33<24:59,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)Cl)C(F)(F)F - Valid: True

 13%|█▎        | 45/350 [03:38<24:56,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC(C1=CC=CC=C1Br)(C)C(=O)OC - Valid: True

 13%|█▎        | 46/350 [03:43<24:51,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC=C1Cl)C(F)(F)F - Valid: True

 13%|█▎        | 47/350 [03:48<24:46,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(Cl)Cl)C1=CC(=C(C=C1)Cl)OC - Valid: True

 14%|█▎        | 48/350 [03:52<24:38,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)O)Cl - Valid: True

 14%|█▍        | 49/350 [03:57<24:33,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=CC(=C1)C=CC(=O)OC)C#N - Valid: True

 14%|█▍        | 50/350 [04:02<24:28,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=N1)Br)N - Valid: True

 15%|█▍        | 51/350 [04:07<24:21,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1C=CC=O)OCNC=O)COC(=O)C - Valid: True

 15%|█▍        | 52/350 [04:12<24:18,  4.89s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)C(F)(F)F)Cl - Valid: True

 15%|█▌        | 53/350 [04:17<24:15,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=C(C=C(C=C1)OC)OC - Valid: True

 15%|█▌        | 54/350 [04:22<24:13,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=CC=C1NCC2=CC=CC=C2 - Valid: True

 16%|█▌        | 55/350 [04:27<24:08,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CNC2=C1C=C(C=C2)Br - Valid: True

 16%|█▌        | 56/350 [04:32<24:02,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1CCC(CC1)C2=C(C(=CC=C2)F)F - Valid: True

 16%|█▋        | 57/350 [04:37<23:59,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=C(C=C1)OC)NC(=O)C=CC(=O)OC(C)(C)C - Valid: True

 17%|█▋        | 58/350 [04:41<23:53,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CNC1=CC(=C(C=C1)OC)C(=O)OC)C - Valid: True

 17%|█▋        | 59/350 [04:46<23:49,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(C(=O)C1=CC=C(C=C1Cl)C(F)F)F - Valid: True

 17%|█▋        | 60/350 [04:51<23:42,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N2CCCC2 - Valid: True

 17%|█▋        | 61/350 [04:56<23:39,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/N(C)C)/C(=O)C1=C(C=CC(=C1)I)F - Valid: True

 18%|█▊        | 62/350 [05:01<23:34,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=C(C=C1)C(C)C)NC(=O)C - Valid: True

 18%|█▊        | 63/350 [05:06<23:28,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C(C)C)OC - Valid: True

 18%|█▊        | 64/350 [05:11<23:23,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)C(=C)C1=CC2=C(C=C1)N=CS2 - Valid: True

 19%|█▊        | 65/350 [05:16<23:20,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1=CC=C(S1)C=C(C(=O)OC)S(=O)(=O)C=CC(=O)C - Valid: True

 19%|█▉        | 66/350 [05:21<23:13,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/N(C)C)/C(=O)C1=CC(=C(C=C1F)Cl)F - Valid: True

 19%|█▉        | 67/350 [05:26<23:08,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=CC=C1)OCC2=CC=CC=C2 - Valid: True

 19%|█▉        | 68/350 [05:31<23:04,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C(C)C - Valid: True

[13:23:15] Conflicting single bond directions around double bond at index 5.
[13:23:15]   BondStereo set to STEREONONE and single bond directions set to NONE.
 20%|█▉        | 69/350 [05:35<23:01,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=C(C=CC(=C1)OC)OC)/NCC(=O)N - Valid: True

 20%|██        | 70/350 [05:40<22:55,  4.91s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=C(C=C1)O[C@H1][C@@H1]([C@H1]([C@@H1]([C@H1](O)CO)O)O)OO - Valid: True

 20%|██        | 71/350 [05:45<22:51,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C=CC=C(NCC(=O)NC=O)C - Valid: True

 21%|██        | 72/350 [05:50<22:47,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC - Valid: True

 21%|██        | 73/350 [05:55<22:42,  4.92s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)Br)NC(=O)OC(C)(C)C - Valid: True

 21%|██        | 74/350 [06:00<22:32,  4.90s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(N=C1)OC)C2=CC=C(C=C2)C(F)(F)F - Valid: True

 21%|██▏       | 75/350 [06:05<22:20,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC(=CC=C2)F)Cl - Valid: True

 22%|██▏       | 76/350 [06:10<22:14,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=CC=CC3=C2C(=O)CC3 - Valid: True

 22%|██▏       | 77/350 [06:15<22:11,  4.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C2=CC=C(C=C2)OC - Valid: True

 22%|██▏       | 78/350 [06:19<22:05,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC=C(C=C2)Br)Cl - Valid: True

 23%|██▎       | 79/350 [06:24<21:58,  4.87s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C2=CC=CC=C2OCC)O - Valid: True

 23%|██▎       | 80/350 [06:29<21:52,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC=C(C1=CC=CC2=C1)C=C(C=C2Cl)Br - Valid: True

 23%|██▎       | 81/350 [06:34<21:46,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C(=C1)Br)OCC2=CC(=CC=C2)Br)Cl - Valid: True

 23%|██▎       | 82/350 [06:39<21:42,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC(=CC=C2)Br)Cl - Valid: True

 24%|██▎       | 83/350 [06:44<21:35,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(C=C1F)OC)Br)O)C=N[C@H1]CO - Valid: True

 24%|██▍       | 84/350 [06:49<21:29,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC=CC=C2)I - Valid: True

 24%|██▍       | 85/350 [06:53<21:27,  4.86s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)COC2=C(C=C(C=C2)/C=C/C(=O)OCC=C)Cl - Valid: True

 25%|██▍       | 86/350 [06:58<21:21,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C2=C(C=C(C=C2)[N+1](=O)[O-1])Br - Valid: True

 25%|██▍       | 87/350 [07:03<21:16,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=NN1CC2=C(C=C(C=C2)C(F)(F)F)C)Cl - Valid: True

 25%|██▌       | 88/350 [07:08<21:11,  4.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OC)I)OCC2=CC=C(C=C2)Cl - Valid: True

 25%|██▌       | 89/350 [07:12<20:36,  4.74s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/OC1=CC(=CC(=C1)C2=CC3=C(C=C2)OCO3)C=O - Valid: True

 26%|██▌       | 90/350 [07:17<20:10,  4.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C(=C/NC1=CC2=C(C=C1)OCCO2)/S(=O)(=O)C3=CC=CC=C3 - Valid: True

 26%|██▌       | 91/350 [07:21<19:50,  4.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=N1)N[C@@H1]2CCN(C2)CC3=CC=CC=C3 - Valid: True

 26%|██▋       | 92/350 [07:26<19:34,  4.55s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(O1)C2=CC(=CC=C2)C(F)(F)F)/C#N - Valid: True

 27%|██▋       | 93/350 [07:30<19:23,  4.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)NC(=O)COC(=O)/C=C/C2=CC(=C(C=C2)Cl)Cl - Valid: True

 27%|██▋       | 94/350 [07:35<19:13,  4.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C(=C1)I)OCC2=CC=C(C=C2)[N+1]=O)[O-1] - Valid: True

 27%|██▋       | 95/350 [07:39<19:04,  4.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C(=C(C=C1)O)COCC)OCC2=C(C=C(C=C2)Cl)Cl - Valid: True

 27%|██▋       | 96/350 [07:44<18:58,  4.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(N=C1)NC2CCN(CC2)CC3=CC=CC=C3Cl - Valid: True

 28%|██▊       | 97/350 [07:48<18:52,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(N=C1)N[C@@H1]2CCN(C2)CC3=CC=CC=C3CCl - Valid: True

 28%|██▊       | 98/350 [07:53<18:45,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OC2CCCO2)C(C=C(C=N)C(F)(F)F)F - Valid: True

 28%|██▊       | 99/350 [07:57<18:41,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1COC(=O)/C=C/C2=CC=C(C=C2)OCC3=CC=CC=C3[N+1](=O)O[O-1] - Valid: True

 29%|██▊       | 100/350 [08:01<18:36,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCOC(=O)/C=C/C1=CC(=C(C=C1)O)O - Valid: True

 29%|██▉       | 101/350 [08:06<18:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C=CC(C(=C1)C)OCCOCC2=CC=C(C=C2)/C=C/C(=O)OCC3=CC=CC=C3C - Valid: True

 29%|██▉       | 102/350 [08:10<18:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCC2OCCO2)C(C=C(C=N)CC(F)F)F - Valid: True

 29%|██▉       | 103/350 [08:15<18:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=CC(=C1)SCC2=C3C=CC=C2)NC=C4C(=C3CC=C4)C#N - Valid: True

 30%|██▉       | 104/350 [08:19<18:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@@H1]1CC=C([C@@H1](N1CC=C)C2=CC=C(C=C2)/C=C/C(=O)OC)NC(=O)C3C=CC=CC3C=CCCC(=O)OOCC=CC(C=C)(C=CCC)F - Valid: True

[13:26:04] Conflicting single bond directions around double bond at index 13.
[13:26:04]   BondStereo set to STEREONONE and single bond directions set to NONE.
 30%|███       | 105/350 [08:24<18:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C(/C2=CC=CC=C2)/C3=CC=CC=C3C#N - Valid: True

 30%|███       | 106/350 [08:28<18:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCCSC2=CC=CC=C2NC=O)CC(F)(F)F - Valid: True

 31%|███       | 107/350 [08:33<18:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=CC(=C1)/C=N/NC2=CC=CC=C2)Br - Valid: True

 31%|███       | 108/350 [08:37<17:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(N(C=C1)C(=O)NCC2=CC=C(C=C2)C=CC(=O)OC)CC3=CCCC=C3 - Valid: True

 31%|███       | 109/350 [08:42<17:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C2N=C(C=C1)N2[C@@H1]3CCN(C3)CCC=CC=CC=C - Valid: True

 31%|███▏      | 110/350 [08:46<17:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1CN(CCC1C2=CC=CC=C2)CC(C3=CC=C(C=C3)Cl)OC(=O)/C=C/C=CC(=CC=C4C=C4)Cl - Valid: True

 32%|███▏      | 111/350 [08:51<17:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCOC1=CC=C(C2=C1)C=CC(=C2C)N - Valid: True

 32%|███▏      | 112/350 [08:55<17:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=CC1=C(C=C(C=C1)C#N)OC2[C@H1]CC[C@H1][C@@H1]2C(C)(F)C)CF - Valid: True

 32%|███▏      | 113/350 [08:59<17:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CN=C(C2=C1SC=C2C3=CC=C(C=C3)OCC=C4C5=CC5C)C4C=O - Valid: True

 33%|███▎      | 114/350 [09:04<17:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C2C(=CC=C1)SC(=N2)NCCOC3=CC=C(C=C3)/C=C/C(=O)OCC - Valid: True

 33%|███▎      | 115/350 [09:08<17:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C2=CC=CC=C2C3CC)CC=C3CC(COCC=CC4C=CC)=CC4CC=CC5C=C5N - Valid: True

 33%|███▎      | 116/350 [09:13<17:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)NC2CCN(CC2)C(=O)C3=CC=C(C=C3)C(CF)F - Valid: True

 33%|███▎      | 117/350 [09:17<17:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=C(NC2=CC=CC=C21)C3)CC=CC=C3/C=C/C(=O)OC - Valid: True

 34%|███▎      | 118/350 [09:22<17:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCCCCCCOC(=O)C=CC1=CC=C(C=C1)Cl - Valid: True

 34%|███▍      | 119/350 [09:26<17:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CSC(=N1)NC2=NC=C(C(=C2)OC3=CC=CC4=CC=CC=C43)C=O - Valid: True

 34%|███▍      | 120/350 [09:31<17:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(N=C1)N[C@@H1]2CCN(C2)CC3=CC=CC=C3)[N+1](=O)[O-1] - Valid: True

 35%|███▍      | 121/350 [09:35<17:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C1=C(C=C(C=C1)C2=CC3=C(S2)C=C(C=C3)O)OC=CC=CC(C=O)/C/C)=O - Valid: True

 35%|███▍      | 122/350 [09:40<16:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C/C1=C(/C2=CC=C(C=C2)/C=C/C(=O)OCC)/C=CC3=NNN=C3C=CC(=C)C=CCC=O - Valid: True

 35%|███▌      | 123/350 [09:44<16:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=CC=C(C=C2C)C3(C=CC=CC3C)CCCC=O - Valid: True

 35%|███▌      | 124/350 [09:49<16:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)C1=C(C=CC(=C1)OCC2=CC=CC3=C2SC4=CC=CC=C34)OOCC(=O)/C=CCC(C)OOOOC - Valid: True

 36%|███▌      | 125/350 [09:53<16:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C(=CS1)C2=C(C=C(C=C2)Cl)OC)C(C=C(N=N)C=CCCCCCO)C - Valid: True

 36%|███▌      | 126/350 [09:57<16:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C=CC(=C2)C=CC(=O)OC)C/N=CC=CCC=CCC(C=O)C - Valid: True

 36%|███▋      | 127/350 [10:02<16:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=CC=C(C(=C)Br)OCC(=O)N/N=C/C1=CC=C(C=C1)OCOCC(=O)/C(=O)C=O)OOC - Valid: True

 37%|███▋      | 128/350 [10:06<16:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC(=O)N(C)CC1=CC(=CC=C1)C2=CC=C(C=C2)C=CC(=O)OOC - Valid: True

 37%|███▋      | 129/350 [10:11<16:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC=CC12[C@@H1][C@]3C[C@]1[C@@H1](OC3O)[C@H1][C@@H1]([C@H1](O2)OO)COC(C)O/C=CCC.C=CC(O)C=O - Valid: True

 37%|███▋      | 130/350 [10:15<16:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CN(CC2=CC=C(C=C2)C3=CC(=CC=C3)CCF)F - Valid: True

 37%|███▋      | 131/350 [10:20<16:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC=CC1=C(C=C(C=C1)C#N)OC[C@@H1](C2CCC(=O)OCC3CC=CC)C(=O)OC23OC=O - Valid: True

 38%|███▊      | 132/350 [10:24<16:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)NCCCCCCCCCCCCC(=O)O.CN(C)CCOC(=O)C=C.CCl - Valid: True

 38%|███▊      | 133/350 [10:29<16:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=C(C=CC(=C2)C)S(=O)(=O)CC3=CC=CC=C3 - Valid: True

 38%|███▊      | 134/350 [10:33<16:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC1=C(C=C(C=C1)/C=C/C(=O)OCC2=CC=C(C=C2)S(=O)(C)OCC)C(C)CF - Valid: True

 39%|███▊      | 135/350 [10:38<15:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 39%|███▉      | 136/350 [10:42<15:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(C(=N2)C(C(F)F)(F)F)CF - Valid: True

 39%|███▉      | 137/350 [10:46<15:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(OCC(=O)N(C1=CC=CC=C1)C2=CC=CC=C2C3=CC=C(C=C3)C#N)(C)CCOCC(C)CC=O - Valid: True

 39%|███▉      | 138/350 [10:51<15:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C2=CC=CC=C2CNC)C3=CC(=NC=N3)CCC(F)(F)F - Valid: True

 40%|███▉      | 139/350 [10:55<15:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC(=CC=C1/C=C/C(=O)OC[C@]C[C@H1][C@@H1]O[C@H1]NO[C@@H1][C@@H1]CC(CCCC)C(C)CCC(C)CCCCCCC)CCCCC(CCCCC)CCCC(C)CCCCCCCCC(CCC)CCCCCCCCC(CCCCCCCCCCCCCCCCC(CCC)CCCCCCC(CCC)CCOC(O)CC)CO.OO - Valid: True

 40%|████      | 140/350 [11:00<15:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C[C@@H1]1CCC2(C1)O[C@H1]([C@@H1](O2)C3=CC=CC=C3)CCC=C4CC(=C)C)C4CCC=O - Valid: True

 40%|████      | 141/350 [11:04<15:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC(CC)COC(=O)C=C.CC(C)(C)OC(=O)/C=C/C1=CC=C(C2=C1)N=CS2N - Valid: True

 41%|████      | 142/350 [11:09<15:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)C2=CC(=C(S2)NC3=CC=CC=C3)C=CC(=O)OC - Valid: True

[13:28:53] Conflicting single bond directions around double bond at index 15.
[13:28:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
 41%|████      | 143/350 [11:13<15:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C(=CC=C1)C)OC2=CC=C(C=C2)/C=C(/C(=O)OC)/C(=O)OCC3=CC=CC=C3 - Valid: True

 41%|████      | 144/350 [11:18<15:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)N)C(=O)COC(=O)/C=C/C2=CC(=C(C=C2)Cl)OCC - Valid: True

 41%|████▏     | 145/350 [11:22<15:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)COC=CCCC=C)OOOO - Valid: True

 42%|████▏     | 146/350 [11:27<15:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(CC2=CC=CC=C2NC(=O)C3=CC=CC=C3C=N)C(=O)OOC(C)C=CCOOC=O - Valid: True

 42%|████▏     | 147/350 [11:31<15:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)CCN(CCC2=CC=C(C=C2)/C=C/C(=O)OCC)C(=C3)C3(CCCC)CC(COC)(CC)F - Valid: True

 42%|████▏     | 148/350 [11:36<15:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(S1)NC(=O)OC(C)(C)C)C2=CC=C(C=C2)NC=CC(CCCC)OO/C(=C)CC(=C)C=O - Valid: True

 43%|████▎     | 149/350 [11:40<14:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)N(C)C2=C(SC3=C2C=CC(=C3)OC)C=O - Valid: True

 43%|████▎     | 150/350 [11:44<14:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC(=C(C(=C1F)F)C(CF)=O)C)C(C)CC(CC=O)OCC(C)CCC(CCCC=O)COOO/CC(CC=NCC)O/OOOCCC(C)N.CCCN.CC=NN=NC=NCC=O - Valid: True

 43%|████▎     | 151/350 [11:49<14:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)N=C(SC2=CC=CC(=C2)OC)C(=O)/C=CC=C(O)OOOC - Valid: True

 43%|████▎     | 152/350 [11:53<14:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)C2=NN(C(=O)C3=CC=CC=C3C=C2)OC)CCC(CCCF)(F)NF - Valid: True

 44%|████▎     | 153/350 [11:58<14:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC1=CC=C(C=C1C2=C(C=C(C=C2)F)C#N)O.CCCCC(CCC=O)COOCCC(C)CCOCO.C(CCCC)CF.C(C)(F)F.CCF.C(CC)F.C(CC)(F)F.CCF.C=O - Valid: True

 44%|████▍     | 154/350 [12:02<14:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)N1C=C(C2=CC=CC=C21)C3=C(C=C(C=C3)/C=C/C(=O)OC)COC - Valid: True

 44%|████▍     | 155/350 [12:07<14:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(CC1=C(O)C=C2C(=C1)C=CC(=O)O2)=C/C3=CC=CC=C3C=CC(=O)NO - Valid: True

 45%|████▍     | 156/350 [12:11<14:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(N=C1CO)CCNC2=CC=CC=C2C3=NC=CC=N3)OC - Valid: True

 45%|████▍     | 157/350 [12:16<14:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC2)C(C=C(C=C2)COC=CC=C)CC(F)C(F)F - Valid: True

 45%|████▌     | 158/350 [12:20<14:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C3=CC=CC=C3C#N - Valid: True

 45%|████▌     | 159/350 [12:25<14:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=CC1=CC=C(C=C1)S=O)C=O - Valid: True

 46%|████▌     | 160/350 [12:29<14:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(C=C2)OC(=O)/C=C/C3=CC(=C(C=C3)O)OOC - Valid: True

 46%|████▌     | 161/350 [12:34<14:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=NC=C(N1CCOC(=O)/C=C/C2=CC=C(C=C2)OC)C3=CC=CC=C3Cl - Valid: True

 46%|████▋     | 162/350 [12:38<13:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=CC1=CC(=CC=C1)NC(=O)C2=CC=CC=C2C=N - Valid: True

 47%|████▋     | 163/350 [12:42<13:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=CC(=C(C=C3)OCO)C - Valid: True

 47%|████▋     | 164/350 [12:47<13:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C=C/C/1C2/C=C/CC1/C(=O)C(=O)C2/C3=C(C=CC(=C3)CC)/C(=O)OCCC/C4=CCC=CC4 - Valid: True

 47%|████▋     | 165/350 [12:51<13:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 47%|████▋     | 166/350 [12:56<13:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)CNC(=O)C2=CN=C(S2)C3=CSC(=N3)NC4=C(C=CS4)CC(CC=O)=O.C(F)F.CCCF.F.Cl.Cl.Cl.Cl - Valid: True

 48%|████▊     | 167/350 [13:00<13:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C(=C1)C)N2CCN(C2)C3=NC=C(C=C3)/C=C/C(=O)OOCC - Valid: True

 48%|████▊     | 168/350 [13:05<13:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)C(C)C)OC(=O)C(=C2)C(C3=C(C3=C(C2)C=O)CC=CCCCCC=O)C(C)CC(C)CCCC(C)CCC(CCCC)CCCCC(C)CCCCCCO.C(C)C(C)C(C)OCCOC(C)OCCCC(C)CCC=O - Valid: True

 48%|████▊     | 169/350 [13:09<13:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCNC(=O)N(C)C1=CC=CC(=C1)C2=C(C=C(C=C2)/C=C/C(=O)OC)CCN(C)CC(C)CCC - Valid: True

 49%|████▊     | 170/350 [13:14<13:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C=C2C(=C(C(=C2)C=CC(=O)OC3C)COC)C3C - Valid: True

 49%|████▉     | 171/350 [13:18<13:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)/C=C/C(=O)OCC - Valid: True

 49%|████▉     | 172/350 [13:23<13:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=CC=CC(=C1)C=CC(=O)OCCC2=C(C3=C(C=C2)N)CN=C3C=O - Valid: True

 49%|████▉     | 173/350 [13:27<13:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NCC(=O)N/N=C/C2=C(C=CC(=C2)Br)OCC(=O)/C(=O)/C=C/S(C)=O - Valid: True

 50%|████▉     | 174/350 [13:32<13:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCOC(=O)/C=C/C1=CC(=C(C(=C1)Br)OCCC(F)(F)F)F - Valid: True

 50%|█████     | 175/350 [13:36<13:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@H1][C@@H1]C1=C([C@H1]([C@H1]([C@@H1](O1)O[C@@H1]([C@@H1](CC([C@@H1](C)CCCCC)CC(C)CCC=CCCCC)CCCC)CCCCC)O)C)CC(CCCCCCCCCCC(C)CCCC(CCCC)CCC(C)CCC(C)CCC(C)(CC)C)CCCC=CC=O - Valid: True

 50%|█████     | 176/350 [13:40<12:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@@H1]C12[C@@H1](CCC(C1CC[C@@H1]2OCC3=C)C=C4C)C3C5=CC(=CC=C5)OC4=O - Valid: True

 51%|█████     | 177/350 [13:45<12:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N[C@H1](CC=C(C(=C)C(F)F)F)CF - Valid: True

 51%|█████     | 178/350 [13:49<12:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCO)COC2=C(C=C(C=N2)C(F)(F)F)F - Valid: True

 51%|█████     | 179/350 [13:54<12:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C3=CC=C(C=C3)C(CC(F)F)F.Cl - Valid: True

 51%|█████▏    | 180/350 [13:58<12:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(SC(=N1)C2=CC=C(C=C2)C)CF - Valid: True

 52%|█████▏    | 181/350 [14:03<12:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC(=C(C=C1C=CC(=O)OC2=CC=CC=C2)C=O)C(=O)C=C - Valid: True

 52%|█████▏    | 182/350 [14:07<12:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)C2=CC=C(C=C2)C#N - Valid: True

 52%|█████▏    | 183/350 [14:12<12:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)C=C.CCCCOC(=O)C(=C)C.CC(=C)CC(C)(C)CC.C=CC2=CC=CC(=C)CC(C)OOCCC2 - Valid: True

 53%|█████▎    | 184/350 [14:16<12:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C3=CC=CC=C3C - Valid: True

 53%|█████▎    | 185/350 [14:21<12:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCCS(=O)=O)COCC2=C(C=C(C=N2)CC(F)F)F - Valid: True

 53%|█████▎    | 186/350 [14:25<12:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C=C(CC=C1)C=C(C(=O)NC2=CC=C(S2)C(=O)N3C=CC=C)C=C3C(=O)CC(=O)OOC - Valid: True

 53%|█████▎    | 187/350 [14:30<12:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C2=C(C=CC=C2N1CC)N(CC3=CC=C(C=C3)/C=C/C(=O)OC)C4=CC=CC=C4 - Valid: True

 54%|█████▎    | 188/350 [14:34<12:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC=CC1=C(C=C(C=C1)C#N)OC[C@H1](CC2=CC=C(C=C2)/C=C3/C(=O)O)CCC3=O - Valid: True

 54%|█████▍    | 189/350 [14:38<11:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N=C(C=C1CC)CNC2=CC(=C(C=C2)C(F)(F)F)F)ONN(C)F - Valid: True

 54%|█████▍    | 190/350 [14:43<11:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=C(C=C1)/C=C/C(=O)OC2=COC(=CC2=O)CSC=NC3=CC=CC=C3)CCF - Valid: True

 55%|█████▍    | 191/350 [14:47<11:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)CC3=CC=CC=C3)C(C)(C=O)CF - Valid: True

 55%|█████▍    | 192/350 [14:52<11:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCOC(=O)C(=C)C.C=CC1=CC=C(C=C1)O - Valid: True

[13:32:36] Conflicting single bond directions around double bond at index 4.
[13:32:36]   BondStereo set to STEREONONE and single bond directions set to NONE.
 55%|█████▌    | 193/350 [14:56<11:39,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC/C=C(/C(=O)C1=CC(=C(C=C1Cl)Cl)F)/C(=O)OCC/C=CC2=C(CC=C2)C=NC=CCOCC - Valid: True

 55%|█████▌    | 194/350 [15:01<11:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C3=CC=CC=C3 - Valid: True

 56%|█████▌    | 195/350 [15:05<11:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)N4C=C(C(=N4)C)C(F)F - Valid: True

 56%|█████▌    | 196/350 [15:10<11:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)OC(C)C(C)CC - Valid: True

 56%|█████▋    | 197/350 [15:14<11:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C(C1=CC(=C(O1)C)CSC#N)P(=O)(OCC)OCC - Valid: True

 57%|█████▋    | 198/350 [15:19<11:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)NC(=O)C3=CC=CC=C3CC=NC=C - Valid: True

 57%|█████▋    | 199/350 [15:23<11:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C(=O)OC2=C(C=C(C=C2C3=CC=C(C=C34)SC5=CC=CC=C5)C=C4C=CCCC6=CCC=CC617)C7=N - Valid: True

 57%|█████▋    | 200/350 [15:27<11:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC1=C(C=C(C=C1)C=CC(=O)OCC2=CC)C(C=C2)OC - Valid: True

 57%|█████▋    | 201/350 [15:32<11:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCNC(=O)N(C)C1=CC=CC(=C1)C2=C(C=C(C=C2)/C=C/C(=O)OO)CCOC - Valid: True

 58%|█████▊    | 202/350 [15:36<11:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)N/C(=C/C1=CC=C(C=C1)N2C(=O)C3=CC=CC=C3C=N2)CC(=O)OOC - Valid: True

 58%|█████▊    | 203/350 [15:41<10:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C(=O)N/C(=C/C2=CC=C(C=C2)[N+1](=O)[O-1])/C(=O)OCC(=O)C - Valid: True

 58%|█████▊    | 204/350 [15:45<10:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC=C1COC2=C(C=C(C=C2Br)/C=C/C(=O)OC)C=COCC3=CC=C(C=C3)OC - Valid: True

 59%|█████▊    | 205/350 [15:50<10:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N2C3=CC=CC=C3C=C2C(=O)C(=O)C4=CC=CCS4C=CCC(=O)O - Valid: True

[13:33:34] Conflicting single bond directions around double bond at index 2.
[13:33:34]   BondStereo set to STEREONONE and single bond directions set to NONE.
 59%|█████▉    | 206/350 [15:54<10:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC/C(=C(/C1=CC=C(C=C1)/C=C/C(=O)OCC)/C2=CC3=C(C=C2)OCO3)OOC - Valid: True

 59%|█████▉    | 207/350 [15:59<10:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C3=CC=C(C=N3)C(F)(C(F)F)F.Cl - Valid: True

 59%|█████▉    | 208/350 [16:03<10:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)C2=CC=C(C=C2)C(C=O)(O3)OO3 - Valid: True

 60%|█████▉    | 209/350 [16:08<10:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)CCC(CCF)CF)F - Valid: True

 60%|██████    | 210/350 [16:12<10:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=CSC=C3 - Valid: True

 60%|██████    | 211/350 [16:17<10:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC2=C(C=C1)N(C(=C2/C=C/C(=O)OCC3=C)C=CC=C3CC4=CC(=O)N4)CCC(CCC(COC)C)F - Valid: True

 61%|██████    | 212/350 [16:21<10:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Br)N2CCC(CC2)C - Valid: True

[13:34:05] Conflicting single bond directions around double bond at index 13.
[13:34:05]   BondStereo set to STEREONONE and single bond directions set to NONE.
 61%|██████    | 213/350 [16:25<10:11,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=CC=CC=C3)C=CC(=O)O - Valid: True

 61%|██████    | 214/350 [16:30<10:07,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)C=C.C=CC(=O)O.C=CC(=O)OC1CO1.CC(=C)C(=O)OCC2=CC=CC=C2.C=CC3(C)OOOC3C=O - Valid: True

 61%|██████▏   | 215/350 [16:34<10:02,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CC(C)(C)OC(=O)CO/C=C/C=C1C(=C(C)CC1)CF - Valid: True

 62%|██████▏   | 216/350 [16:39<09:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=CC(=C1)C=C(C(=NC2=CC=CC=C2NC)C)COC(=O)/C=C/C/C=CCC=CCCC)COOC - Valid: True

 62%|██████▏   | 217/350 [16:43<09:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C(CCSCN)C(=O)C2=CC=CC=C2C=N - Valid: True

 62%|██████▏   | 218/350 [16:48<09:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC2=C1)C=C(C(=C2)CN)C(=O)C3=CC=CC=C3 - Valid: True

 63%|██████▎   | 219/350 [16:52<09:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C2=CC3=C1C=C2C(=C3)NC(=O)C=CC=CC=C)OC - Valid: True

 63%|██████▎   | 220/350 [16:57<09:39,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N([C@@H1]2CCN(C2)CC3=CC=CC=C3C)CCC4C5CC5(C)C4C=O - Valid: True

 63%|██████▎   | 221/350 [17:01<09:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC=CC1=C(C(=C(C(=C1)C(C)(C)CC)OC2=CC=C)C=C2/C=C/C(O)OOCCCO)C - Valid: True

 63%|██████▎   | 222/350 [17:06<09:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C][=Branch2][Branch1][S][=C][C][=C][Branch2][Branch1][C][=C][Branch1][Branch2][C][=Branch1][Ring2][=C][Ring1][=Branch1][C][S][=Branch1][C][=O][=Branch1][C][=O][C][=C][Branch2][Ring1][#Branch1][C][=C][Branch1][Branch1][C][C][=C][Ring1][=Branch1][/C][=Branch1][Ring1][=N][O][C][C][=C][C][C][=C][C][Branch1][Branch1][C][C][C][C][C][C][C]C][C]

 64%|██████▎   | 223/350 [17:10<09:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)Cl)Cl - Valid: True

 64%|██████▍   | 224/350 [17:15<09:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCSCC(OC(=O)C(=C)COCCCC)OC(=O)C=C(C=C(CC1=NO)C=C1CCC=C)C - Valid: True

 64%|██████▍   | 225/350 [17:19<09:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C(=CC=C1)OC2=CC=CC(=N2)/C=C)/C(=O)OC(C)(C)CCC - Valid: True

 65%|██████▍   | 226/350 [17:23<09:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)CC2=CC=CC=C2OCC3=C)C=CC=C3 - Valid: True

 65%|██████▍   | 227/350 [17:28<09:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)N3C=CN=C3C - Valid: True

 65%|██████▌   | 228/350 [17:32<09:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)NC(=O)COC(=O)/C=C/C2=CC=C(C=C2)OCC3=CC=CC=C3 - Valid: True

 65%|██████▌   | 229/350 [17:37<08:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCNC(=O)N(C)C1=CC=CC(=C1)C2=C(C=C(C=C2)/C=C/C(=O)OC3)CCC(=O)CCC=CCC(C)OC3C - Valid: True

 66%|██████▌   | 230/350 [17:41<08:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)S(=O)(=O)C2=CC)CC=C2OC(F)(F)F - Valid: True

 66%|██████▌   | 231/350 [17:46<08:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)C=C.CCC(C)(C)OC(=O)C=C.CC(=C)C(=O)OCCCC=O - Valid: True

 66%|██████▋   | 232/350 [17:50<08:47,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C1=C(C=CC(=C1)C=CC(=O)OC2C)CCCC(=O)OC2OC=CC=C3CC=C)CC3C(C)C(O)C(O)CO - Valid: True

 67%|██████▋   | 233/350 [17:55<08:42,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)N(C2=CC=C(C=C2)C3=CC=C(C=C3)CC=CC(=O)OC4)CCO4 - Valid: True

 67%|██████▋   | 234/350 [17:59<08:37,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)NC(=O)C2=CC=CC(=N2)C=C)C(=O)OCCCC - Valid: True

 67%|██████▋   | 235/350 [18:04<08:33,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=C(C=CC(=C1)/C=C/C(=O)OC)CC2=CC=C(C=C2)O - Valid: True

 67%|██████▋   | 236/350 [18:08<08:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=CC=C(C=C1)C2=CC(=CC=C2)C#N - Valid: True

 68%|██████▊   | 237/350 [18:13<08:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=CC=C1)C(=C(CCCC)NC2)CC=CC=C2 - Valid: True

 68%|██████▊   | 238/350 [18:17<08:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Br)NCCC(C2C(CC3CC2C3)O)CC - Valid: True

 68%|██████▊   | 239/350 [18:21<08:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N[C@@H1]2CCN(C2)C3CCCCC3 - Valid: True

 69%|██████▊   | 240/350 [18:26<08:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1(CC=C(C=C1N)CCC2=CC=C(C=C2)/C=C/C(=O)OCC)C - Valid: True

 69%|██████▉   | 241/350 [18:30<08:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCC2=CC=CC=C2)OC3=CC=C(C=C3)OC - Valid: True

 69%|██████▉   | 242/350 [18:35<08:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)NC(=O)C2(CCCC2)NC(=O)OC(C)(C)CC - Valid: True

 69%|██████▉   | 243/350 [18:39<07:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)N4C=CC(=NC4C)F - Valid: True

 70%|██████▉   | 244/350 [18:44<07:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=C(C=C1)C2=C(C(=NN2C3=CC=CC=C3C)N)C(=O)C=C)C(C=O)C=O - Valid: True

 70%|███████   | 245/350 [18:48<07:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1COC(=O)C=CC2=C3C(=CC(=N2)C4=CC=C(C=C4)C5=CC=CC=C5CCC1)CC3CCCC(C)C=O - Valid: True

 70%|███████   | 246/350 [18:53<07:44,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=CC(=CC=C2)OC - Valid: True

 71%|███████   | 247/350 [18:57<07:39,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=C(C=C(C=C1)/C=C/C(=O)OC)CC2=CC=C(C=C2)OC - Valid: True

 71%|███████   | 248/350 [19:02<07:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=C(C=C(O1)C(=O)CC)C)CCC/P(=O)(OCC)OCC - Valid: True

 71%|███████   | 249/350 [19:06<07:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)C1=C(C=CC2=C1SC3=CC=CC=C23)O - Valid: True

 71%|███████▏  | 250/350 [19:11<07:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=C.CC(C)(C)OC(=O)C=C.C=CC1=CC=C(C=C1)O - Valid: True

 72%|███████▏  | 251/350 [19:15<07:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCS(=O)(=O)OCC1=CC=C(C=C1)[N+1](=O)[O-1] - Valid: True

 72%|███████▏  | 252/350 [19:19<07:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)NC(=O)C(C)C(C)CC - Valid: True

 72%|███████▏  | 253/350 [19:24<07:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=CC(=CC(=C2)C(F)(F)F)C(F)F - Valid: True

 73%|███████▎  | 254/350 [19:28<07:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C=CC=CC1OCC2=CC=C(C=C2C=C(C=N)NC(=O)C3=C)C=CC=N3 - Valid: True

 73%|███████▎  | 255/350 [19:33<07:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(CC2=CC=C(C=C2)C3=CC=C(C=C3)CC#N)C=O.C(C=O)C=O.C(C)(O)CF.Cl.Cl - Valid: True

 73%|███████▎  | 256/350 [19:37<06:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC1=C(C=NC(=N1)C=C(C(=O)OC)NC(=O)C2CCN(CC2)C=CC(=O)OCNNC)CCC(C)CCC(C)CC=O - Valid: True

 73%|███████▎  | 257/350 [19:42<06:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C2=CC(CC1)C=C(C(=N2)C3=CC=C(C=C3)/C=C/C(=O)OCC4)CC4(C5=CCC5)SF - Valid: True

 74%|███████▎  | 258/350 [19:46<06:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1(CC=C(C(N1)C2=CC=C(C=C2)CC(F)(F)F)C(F)(F)F)F - Valid: True

 74%|███████▍  | 259/350 [19:51<06:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC(CC)COC(=O)/C=C/C1=CC=C(C=C1)OC.C=CC(=O)O - Valid: True

 74%|███████▍  | 260/350 [19:55<06:40,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=C(C=C(C=C1)OCCO)C(=O)C(C)C - Valid: True

 75%|███████▍  | 261/350 [20:00<06:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)C(=O)N/C(=C/C2=CC(=CC=C2)[N+1](=O)[O-1])/C(=O)OCC(=O)O - Valid: True

 75%|███████▍  | 262/350 [20:04<06:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=CC=CC=C1C2=C(C3=C(S2)C=C(C=C3)OC)OC4=CC=C(C=C4)/C=C/C(=O)OC - Valid: True

 75%|███████▌  | 263/350 [20:09<06:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OCC2=CC=C(C=C2)Br - Valid: True

 75%|███████▌  | 264/350 [20:13<06:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=CC=C(C=C1)NC(=O)COC(=O)/C=C/C2=CC=C(C=C2)OC - Valid: True

 76%|███████▌  | 265/350 [20:17<06:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(S1)NC(=O)OC(C)(C)C)C2=CC=CC=C2 - Valid: True

 76%|███████▌  | 266/350 [20:22<06:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C(=NC=C1)OCC2=CC=CC=C2)C3=NN=C(O3)C=CC(=O)C - Valid: True

 76%|███████▋  | 267/350 [20:26<06:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1OC)OC)OCC2=CC=CC=C2 - Valid: True

 77%|███████▋  | 268/350 [20:31<06:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCC2)N3C=CSC3 - Valid: True

 77%|███████▋  | 269/350 [20:35<06:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=C(C=C(C=N2)C(F)(F)F)F - Valid: True

 77%|███████▋  | 270/350 [20:40<05:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=C(C(=CC=C1)OC)C/SC=CC2=NC#CC=C2)OC - Valid: True

 77%|███████▋  | 271/350 [20:44<05:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=CC(=CC=C2)Br - Valid: True

 78%|███████▊  | 272/350 [20:49<05:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C2=NC(=C(S2)COC3=CC=C(C=C3)/C=C/C(=O)OC)OCOC - Valid: True

 78%|███████▊  | 273/350 [20:53<05:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N([C@@H1]2CCN(C2)CC3=CC(=CC=C3)Cl)CF - Valid: True

 78%|███████▊  | 274/350 [20:58<05:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=NN1CC2=C(C=C(C=C2)C(F)(F)F)Br - Valid: True

 79%|███████▊  | 275/350 [21:02<05:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC(CCCCCCCC)CCOC(=O)C=C - Valid: True

 79%|███████▉  | 276/350 [21:06<05:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)/C(=C/NC2=CC(=C(C=C2)OC)OC)/C(=O)C - Valid: True

 79%|███████▉  | 277/350 [21:11<05:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N(N=C1C)C)N2C=CC3=C2C=C(C=C3)OC - Valid: True

 79%|███████▉  | 278/350 [21:15<05:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1OC(=O)/C=C/C2=CC=C(C=C2)O[C@H1][C@@H1]([C@H1]([C@@H1]([C@H1](COOO)O)O)O)OO - Valid: True

 80%|███████▉  | 279/350 [21:20<05:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=C(C=C(C=C1)C(=O)NCC(=O)O)CC2=CC=CC=C2 - Valid: True

 80%|████████  | 280/350 [21:24<05:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(SC(=C1)C2=NC3=C(N2)C=CC=C3)CCC/C(=O)NCC - Valid: True

[13:39:09] Conflicting single bond directions around double bond at index 5.
[13:39:09]   BondStereo set to STEREONONE and single bond directions set to NONE.
 80%|████████  | 281/350 [21:29<05:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=C(OC(=C1C)C(C)(C)C)Br)/P(=O)(OCC)OCC - Valid: True

 81%|████████  | 282/350 [21:33<05:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CNCCCNC1=CC2=C(C=C1)OCO2)NC=CC=N - Valid: True

 81%|████████  | 283/350 [21:38<04:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=NC=C1OC(=O)/C=C/C2=CC3=C(C=C2)OCO3 - Valid: True

 81%|████████  | 284/350 [21:42<04:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OCC2=C(C=C(C=C2)F)Cl - Valid: True

 81%|████████▏ | 285/350 [21:47<04:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCC(=O)N(C)CC1=CC(=CC=C1)C2=CC(=C(C=C2)C(=O)OCCC)OC(C)OC(=O)C=C - Valid: True

 82%|████████▏ | 286/350 [21:51<04:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=C(C=CC(=C1)/C=C/C(=O)OC)CCN(C)C - Valid: True

 82%|████████▏ | 287/350 [21:56<04:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N2CCCC2C3=CC(=CC=C3)C(F)(F)F - Valid: True

 82%|████████▏ | 288/350 [22:00<04:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)OCC2=CC=CC=C2C(=O)OCC3=CC=CC=C3 - Valid: True

 83%|████████▎ | 289/350 [22:04<04:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=C(CC1)C=C(C=C2)OC)C=O - Valid: True

 83%|████████▎ | 290/350 [22:09<04:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=CC(=C1)/C=C/C(=O)OCCC2=CC=CC=C2)OC - Valid: True

 83%|████████▎ | 291/350 [22:13<04:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])OC(=O)/C=C/C2=CC=C(C=C2)N - Valid: True

 83%|████████▎ | 292/350 [22:18<04:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCCCCCOC1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)C=CC(=O)OC - Valid: True

 84%|████████▎ | 293/350 [22:22<04:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCNC(=O)N(C)C1=CC=CC(=C1)C=CC(=O)OC - Valid: True

 84%|████████▍ | 294/350 [22:27<04:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)N - Valid: True

 84%|████████▍ | 295/350 [22:31<04:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)OCC2=CC=C(C=C2C)CC(=O)NCCC(C)C - Valid: True

 85%|████████▍ | 296/350 [22:36<04:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[=Branchranch2]'
	SELFIES: [C][C][=C][C][=Branch2][Branch1][Branch2][=C][Branch2][Ring2][S][C][=Branchranch2][Ring2][Ring1][=C][Ring1][=Branch1][C][=C][Branch1][#Branch1][C][=Branch1][C][=O][O][C][N][C][=Branch1][C][=O][C][=C][C][=C][C][=C][Ring1][=Branch1][C][=N][Ring1][=Branch2][Cl]

 85%|████████▍ | 297/350 [22:40<03:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCNC(=O)C=CSCCCOC(=O)C=C - Valid: True

 85%|████████▌ | 298/350 [22:45<03:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCCCCCCOC1=CC=CC=C1 - Valid: True

 85%|████████▌ | 299/350 [22:49<03:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C(C)(C)C - Valid: True

 86%|████████▌ | 300/350 [22:54<03:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCNC=C(C(=O)C1=CC(=C(C=C1F)F)F)N - Valid: True

 86%|████████▌ | 301/350 [22:58<03:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=C(C(=C(C=C2)Cl)C)Cl - Valid: True

 86%|████████▋ | 302/350 [23:02<03:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC - Valid: True

 87%|████████▋ | 303/350 [23:07<03:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=C(C=C(C=N2)C(F)(F)F)F - Valid: True

 87%|████████▋ | 304/350 [23:11<03:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1C=O)CC2=CC=CC(=C2)CN3C(=O)C4=CC=CC=C4C3=O - Valid: True

 87%|████████▋ | 305/350 [23:16<03:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCOC(=O)/C=C/C1=CC=C(C=C1)OC - Valid: True

 87%|████████▋ | 306/350 [23:20<03:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=C(C2=C1)C(=O)NC3C(=N2)C=C(C=N3)CN - Valid: True

 88%|████████▊ | 307/350 [23:25<03:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=C(C=C(C=N2)C(F)(F)F)F - Valid: True

 88%|████████▊ | 308/350 [23:29<03:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=CC(=C1)C(=O)NCC2=CC3=C(C4=C2)N=C=O)C=C4C3 - Valid: True

 88%|████████▊ | 309/350 [23:34<03:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C(=C1)Br)OCC2=C(C=C(C=C2)Cl)Cl)OC - Valid: True

 89%|████████▊ | 310/350 [23:38<02:58,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C(=O)CCC2CC2C3=CC=C(C=C3)C - Valid: True

[13:41:23] Conflicting single bond directions around double bond at index 13.
[13:41:23]   BondStereo set to STEREONONE and single bond directions set to NONE.
 89%|████████▉ | 311/350 [23:43<02:54,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=C(C=C(C=C3)C)N)CCCO - Valid: True

 89%|████████▉ | 312/350 [23:47<02:49,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1(C2CCC1C(C2)OC(=O)/C=C/C3=CC=C(C=C3)Cl)C#N - Valid: True

 89%|████████▉ | 313/350 [23:52<02:45,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=NC=CN1CCOC(=O)/C=C/C2=CC=C(C=C2)F - Valid: True

 90%|████████▉ | 314/350 [23:56<02:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=C(C=C1)COC(=O)/C=C/C2=CC=C(C=C2)[N+1](=O)[O-1] - Valid: True

 90%|█████████ | 315/350 [24:00<02:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC=C(C(=O)C=CO1)CC=CC=C1 - Valid: True

 90%|█████████ | 316/350 [24:05<02:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCC2=CC=CC=C2O)C(C)C - Valid: True

 91%|█████████ | 317/350 [24:09<02:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '][C]'
	SELFIES: [C][C][=C][C][=Branch2][Ring1][=Branch1][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=Branch1][C][=O][C][=C][C][=C][C][=C][Ring1][=Branch1][C][=N][C][=Branch1][=Branch1][=C][C][=C][Ring1][=Branch1][C][=C][C][=C][C][=C][S][Ring1][=Branch1][C][C][=Branch1][C][C][=O][O][C][=Branch1][C][C][=O][C][Branch1][=Branch1][C][C][=O][O][O][O][=Branch1][O]][C][Branch1][C][=C][C][C][O][Branch1][=Branch1][=Branch1][C][C][C][F][F][F][F][F]][F].[Cl].[Cl]

 91%|█████████ | 318/350 [24:14<02:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])OC(=O)CC(C)(C)C - Valid: True

 91%|█████████ | 319/350 [24:18<02:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCOC(=O)C=C.CC(=C(C(=O)OCCOC(=O)C)CCC)CCCC - Valid: True

 91%|█████████▏| 320/350 [24:23<02:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)/C(=C/NC2=CC(=C(C=C2)F)F)/C(=O)OC - Valid: True

 92%|█████████▏| 321/350 [24:27<02:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=CC=CC=C2 - Valid: True

 92%|█████████▏| 322/350 [24:32<02:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1OC(=O)/C1=C/C2=CC=C(C=C2)NCC=CC=CC=C - Valid: True

 92%|█████████▏| 323/350 [24:36<02:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC(=C(C=C1)Cl)C2=CC=C(C=C2)CC(O)(OCC)OCC(=O)C=C - Valid: True

 93%|█████████▎| 324/350 [24:41<01:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OCC2=CC=CC=C2 - Valid: True

 93%|█████████▎| 325/350 [24:45<01:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C(=CC=C1)NC(=O)COC(=O)/C=C/C2=CC=C(C=C2)O)OO - Valid: True

 93%|█████████▎| 326/350 [24:50<01:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(C=C1)NCC(=O)OC(C)(C)C - Valid: True

 93%|█████████▎| 327/350 [24:54<01:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)I - Valid: True

 94%|█████████▎| 328/350 [24:58<01:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)C(C1=C(C=CC(=C1)[N+1](=O)[O-1])N)CC2=CC=CC=N2 - Valid: True

 94%|█████████▍| 329/350 [25:03<01:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2CCCCC2 - Valid: True

 94%|█████████▍| 330/350 [25:07<01:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=CC(=C1)COC2=CC=C(C=C2)/C=C/C(=O)OC)Cl - Valid: True

 95%|█████████▍| 331/350 [25:12<01:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C1=CC2=C(C=C1)C(=O)C3=CC=CC=C3C=C2 - Valid: True

 95%|█████████▍| 332/350 [25:16<01:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=CC=C(C=C2)N - Valid: True

 95%|█████████▌| 333/350 [25:21<01:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)N([C@@H1]2CCN(C2)CC3=CC=CC=C3)Cl - Valid: True

 95%|█████████▌| 334/350 [25:25<01:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)CCCC(C(C=CCCF)F)F)CF - Valid: True

 96%|█████████▌| 335/350 [25:30<01:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC(=C(C=NC1=CC=CC(=C1)COC(=O)C2=CC=CC=C2)C=CC(=O)O)CCC(=O)C=CCC(C)C=O - Valid: True

 96%|█████████▌| 336/350 [25:34<01:02,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=C(C=C1)[N+1](=O)[O-1])NCC2=CC=CC=C2 - Valid: True

[13:43:19] Conflicting single bond directions around double bond at index 5.
[13:43:19]   BondStereo set to STEREONONE and single bond directions set to NONE.
 96%|█████████▋| 337/350 [25:39<00:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=CC=C(C(=C1F)O)C(F)F)/C#N - Valid: True

 97%|█████████▋| 338/350 [25:43<00:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(O1)COC2=CC=C)C=C2[N+1](=O)[O-1] - Valid: True

 97%|█████████▋| 339/350 [25:47<00:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1N2)CCN(CC2)C=O)OC(C)(C)CC - Valid: True

 97%|█████████▋| 340/350 [25:52<00:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)OCC(C)(C)CC - Valid: True

 97%|█████████▋| 341/350 [25:56<00:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=C(C=C(C=N2)C(F)(F)F)Cl - Valid: True

 98%|█████████▊| 342/350 [26:01<00:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN(N=C1C(=O)NCCCC2CCCCC2C=C3C(C3C)=NCl)Cl - Valid: True

 98%|█████████▊| 343/350 [26:05<00:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=CC(=CC=C3)OCOC - Valid: True

 98%|█████████▊| 344/350 [26:10<00:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 99%|█████████▊| 345/350 [26:14<00:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CCC2=CC=C(C=C2)C - Valid: True

 99%|█████████▉| 346/350 [26:19<00:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])OC2=CC=CC=C2 - Valid: True

[13:44:03] Conflicting single bond directions around double bond at index 11.
[13:44:03]   BondStereo set to STEREONONE and single bond directions set to NONE.
 99%|█████████▉| 347/350 [26:23<00:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)/C=C(/C#N)/C(=O)OCC - Valid: True

 99%|█████████▉| 348/350 [26:28<00:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CNC1=CC=CC(=C1)C2=C(C=C(S2)C(=O)OCOC3=C)C=C(C=C3)/C=C/C(=O)OC - Valid: True

100%|█████████▉| 349/350 [26:32<00:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)NOC - Valid: True

100%|██████████| 350/350 [26:37<00:00,  4.56s/it]

C=CC(=O)OCC(CO)COCC(COC(=O)C=C)(COC(=O)C=C)COC(=O)C=C - Valid: True

In [7]:
smiles_test_df

                                                smiles  static_polarizability
0                                            C=CC(=O)O               0.000000
1                                        C=CC(=O)[O-1]               0.002865
2                                        C=CC(=O)ONC=O               0.005731
3                   C=CC(=O)OCC(CCl)(C(F)(F)F)C(F)(F)F               0.008596
4                                   C=CC(=O)OCCN1CCOC1               0.011461
..                                                 ...                    ...
339  CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])OC2=...               0.988539
340              CCCCOC1=CC=C(C=C1)/C=C(/C#N)/C(=O)OCC               0.991404
341  CNC1=CC=CC(=C1)C2=C(C=C(S2)C(=O)OCOC3=C)C=C(C=...               0.994269
342            CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)NOC               0.997135
343  C=CC(=O)OCC(CO)COCC(COC(=O)C=C)(COC(=O)C=C)COC...               1.000000

[344 rows x 2 columns]

In [5]:
acrylate_smarts = "C=C[C](=O)O"
acrylate_mol = Chem.MolFromSmarts(acrylate_smarts)

def is_mixed_neutral_smiles(smiles: str) -> bool:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False  # or True if you want to discard invalid SMILES
    
    fragments = Chem.GetMolFrags(mol, asMols=True)
    
    if len(fragments) == 1:
        return False  # single molecule, keep
    
    all_neutral = all(sum(atom.GetFormalCharge() for atom in frag.GetAtoms()) == 0 for frag in fragments)
    
    return all_neutral  # True → multiple neutral fragments → discard

def is_acrylate(smi):
    mol = Chem.MolFromSmiles(smi)
    return mol.HasSubstructMatch(acrylate_mol) if mol else False

df_filtered = smiles_test_df[~smiles_test_df["smiles"].apply(is_mixed_neutral_smiles)].reset_index(drop=True)
df_filtered["is_acrylate"] = df_filtered["smiles"].apply(is_acrylate)

[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 15.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 4.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 2.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 11.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 15.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 4.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 2.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 13.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 5.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:44:17] Conflicting single bond directions around double bond at index 11.
[13:44:17]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [9]:
(1 - df_filtered['smiles'].isin(df_polarizability['smiles_A']).sum()/len(df_filtered))*100

np.float64(84.52012383900929)

In [10]:
df_filtered = df_filtered.rename(columns={'smiles': 'smiles_A'})
df_filtered['chain_size'] = 0
df_filtered['id_A'] = df_filtered.index
df_filtered.to_csv('gpt_generation.csv', index=False)

# Predict

In [11]:
import torch
import pandas as pd

import sys
sys.path.append("/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy")
from polygraphpy.gnn.pre_processing import PreProcess

# Setup
preprocess = PreProcess(
    input_csv='../polygraphpy/data/polarizability_data.csv',
    train_input_data_path='prediction_test',
    polymer_type='monomer',
    target='static_polarizability',
    gnn_output_path='./'
)

atoms_list, bonds_list = preprocess.extract_atoms_and_bonds_features_from_monomer_smiles()
atom_encoder = preprocess.make_encoder(pd.DataFrame(atoms_list).drop_duplicates().reset_index(drop=True))
bond_encoder = preprocess.make_encoder(pd.DataFrame(bonds_list).drop_duplicates().reset_index(drop=True))

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = torch.load('../polygraphpy/data/gnn_output/model_gcn.pt', weights_only=False)
model = model.to(device)
print(model)

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_geometric/typing.py:68: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/libpyg.so: undefined symbol: _ZN2at4_ops11multinomial4callERKNS_6TensorElbSt8optionalINS_9GeneratorEE
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_sparse/_hgt_sample_cuda.so: undefined symbol: _ZN2at4_ops11multinomial4callERKNS_6TensorElbSt8optionalINS_9GeneratorEE
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "

Reading GNN input file.
Extracting unique features from atoms and bonds.

100%|██████████| 26582/26582 [00:07<00:00, 3394.49it/s]

Making feature encoder.
Making feature encoder.
GraphUNetModel(
  (unet): GraphUNet(68, 150, 150, depth=5, pool_ratios=[0.5, 0.5, 0.5, 0.5, 0.5])
  (lin1): Linear(in_features=150, out_features=150, bias=True)
  (lin2): Linear(in_features=150, out_features=150, bias=True)
  (lin3): Linear(in_features=150, out_features=150, bias=True)
  (output): Linear(in_features=150, out_features=1, bias=True)
)

In [12]:
from rdkit import Chem
from torch_geometric.data import Data

def mol_to_data(smiles):
    atoms = []
    bonds = []
    m1 = Chem.MolFromSmiles(smiles, sanitize=True)
    if m1 is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    m1 = Chem.AddHs(m1)
    
    atoms = preprocess.get_nodes_information(m1, [], chain_size=0)

    if not atoms:
        print(f"No atoms extracted for SMILES: {smiles}")
        return None
    
    df_nodes = pd.DataFrame(atoms)
    nodes_features = pd.DataFrame(atom_encoder.transform(df_nodes.drop(['idx'], axis=1)).toarray())
    x = torch.tensor(nodes_features.astype('float32').values)
    
    bonds = preprocess.get_bonds_information(m1, [])
    if not bonds:
        print(f"No bonds extracted for SMILES: {smiles}")
        return None
    df_bonds = pd.DataFrame(bonds)
    edge_index = torch.tensor([
        df_bonds.begin_idx.to_list() + df_bonds.end_idx.to_list(),
        df_bonds.end_idx.to_list() + df_bonds.begin_idx.to_list()
    ])
    
    edge_attrs = df_bonds[['type', 'is_conjugated', 'is_aromatic']]
    edge_attrs = pd.concat([edge_attrs, edge_attrs.sort_index(ascending=False)])
    edge_attr = torch.tensor(bond_encoder.transform(edge_attrs).toarray())
    
    edge_weight = torch.tensor([1.0] * edge_index.shape[1], dtype=torch.float32)
    
    mol_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, edge_weight=edge_weight)
    mol_data.validate()

    return mol_data
    
df_results = pd.DataFrame()
df_filtered = pd.read_csv('gpt_generation.csv')

for i in df_filtered.itertuples():
    mol_data = mol_to_data(i.smiles_A).to(device)

    with torch.no_grad():
        batch = torch.zeros(mol_data.x.size(0), dtype=torch.long).to(device)
        pred = model(mol_data.x, mol_data.edge_index, mol_data.edge_weight, batch)

    df_results = pd.concat([df_results, pd.DataFrame({'smiles_A': i.smiles_A, 'y': i.static_polarizability, 'pred': pred.cpu().numpy()[0][0]}, index=[0])]).reset_index(drop=True)

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_geometric/utils/sparse.py:277: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  adj = torch.sparse_csr_tensor(
[14:40:11] Conflicting single bond directions around double bond at index 5.
[14:40:11]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:12] Conflicting single bond directions around double bond at index 13.
[14:40:12]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:12] Conflicting single bond directions around double bond at index 15.
[14:40:12]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:13] Conflicting single bond directions around double bond at index 4.
[14:40:13]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:13] Conflicting single bond directions around double bond at index 2.
[14:40:13]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:13] Conflicting single bond directions around double bond at index 13.
[14:40:13]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:14] Conflicting single bond directions around double bond at index 5.
[14:40:14]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:14] Conflicting single bond directions around double bond at index 13.
[14:40:14]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:15] Conflicting single bond directions around double bond at index 5.
[14:40:15]   BondStereo set to STEREONONE and single bond directions set to NONE.
[14:40:15] Conflicting single bond directions around double bond at index 11.
[14:40:15]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [13]:
df_results['error'] = abs(df_results['y'] - df_results['pred'])/(df_results['y'] + 1e-12)

In [14]:
df_results

,smiles_A,y,pred,error
0,C=CC(=O)O,0.000000,0.042027,4.202676e+10
1,C=CC(=O)[O-1],0.002865,0.053957,1.783086e+01
2,C=CC(=O)ONC=O,0.005731,0.031390,4.477619e+00
3,C=CC(=O)OCC(CCl)(C(F)(F)F)C(F)(F)F,0.008596,0.078739,8.160023e+00
4,C=CC(=O)OCCN1CCOC1,0.011461,0.070613,5.160997e+00
...,...,...,...,...
318,CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])OC2=...,0.988539,0.188771,8.090399e-01
319,CCCCOC1=CC=C(C=C1)/C=C(/C#N)/C(=O)OCC,0.991404,0.128959,8.699229e-01
320,CNC1=CC=CC(=C1)C2=C(C=C(S2)C(=O)OCOC3=C)C=C(C=...,0.994269,0.124150,8.751346e-01
321,CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)NOC,0.997135,0.131807,8.678139e-01
322,C=CC(=O)OCC(CO)COCC(COC(=O)C=C)(COC(=O)C=C)COC...,1.000000,0.082450,9.175504e-01

In [15]:
df_results.to_csv('predict_results_from_gpt.csv', index=False)