# Train

In [ ]:
import pandas as pd
import selfies as sf
from sklearn.preprocessing import MinMaxScaler

df_polarizability = pd.read_csv('../polygraphpy/data/polarizability_data.csv')

df_polarizability = df_polarizability[df_polarizability['chain_size'] == 0].reset_index(drop=True)

scaler = MinMaxScaler()
target = scaler.fit_transform(df_polarizability['static_polarizability'].values.reshape(-1,1)).flatten()

smiles_list = df_polarizability['smiles_A'].values
selfies_list = []

for i in smiles_list:
    selfies_list.append(sf.encoder(i))

In [ ]:
import selfies as sf
from rdkit import Chem

# 1. Define the SMILES string
smiles_string = "COC(=O)C=C"

# 2. Encode SMILES to SELFIES
encoded_selfies = sf.encoder(smiles_string)

# 3. Decode SELFIES back to SMILES (optional)
decoded_smiles = sf.decoder(encoded_selfies)

# 4. Print the results
print(f"Original SMILES: {smiles_string}")
print(f"Encoded SELFIES: {encoded_selfies}")
print(f"Decoded SMILES: {decoded_smiles}")

# 5. Canonicalize SMILES for robust comparison
can_smiles_original = Chem.CanonSmiles(smiles_string)
can_smiles_decoded = Chem.CanonSmiles(decoded_smiles)

print(f"RDKit Canonical SMILES (Original): {can_smiles_original}")
print(f"RDKit Canonical SMILES (Decoded): {can_smiles_decoded}")
print(f"Are canonical SMILES equal? {can_smiles_original == can_smiles_decoded}")

Original SMILES: COC(=O)C=C
Encoded SELFIES: [C][O][C][=Branch1][C][=O][C][=C]
Decoded SMILES: COC(=O)C=C
RDKit Canonical SMILES (Original): C=CC(=O)OC
RDKit Canonical SMILES (Decoded): C=CC(=O)OC
Are canonical SMILES equal? True

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
import torch
import rdkit.Chem as Chem

# Data
texts = [f"polarizability: {p} selfies: {i}" for i, p in zip(selfies_list, target)]

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = AutoModelForCausalLM.from_pretrained('gpt2')
model.resize_token_embeddings(len(tokenizer))

class InChIDataset(Dataset):
    def __init__(self, texts, tokenizer, max_len=128):
        self.encodings = tokenizer(texts, truncation=True, padding=True, max_length=max_len, return_tensors='pt')

    def __len__(self):
        return len(self.encodings['input_ids'])

    def __getitem__(self, idx):
        return {k: v[idx] for k, v in self.encodings.items()}

dataset = InChIDataset(texts, tokenizer)
loader = DataLoader(dataset, batch_size=12, shuffle=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
optimizer = AdamW(model.parameters(), lr=5e-5)

aux = 1e9

# Training
model.train()
for epoch in range(150):
    epoch_loss = 0.0

    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        optimizer.zero_grad()
        outputs = model(**batch, labels=batch['input_ids'])
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item() * batch['input_ids'].size(0)
    
    total_loss = epoch_loss / len(dataset)
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    if total_loss < aux:
        torch.save(model, 'gpt_selfies.pt')
        aux = total_loss

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

Epoch 1, Loss: 0.8156
Epoch 2, Loss: 0.5474
Epoch 3, Loss: 0.5230
Epoch 4, Loss: 0.5076
Epoch 5, Loss: 0.4954
Epoch 6, Loss: 0.4849
Epoch 7, Loss: 0.4753
Epoch 8, Loss: 0.4667
Epoch 9, Loss: 0.4595
Epoch 10, Loss: 0.4516
Epoch 11, Loss: 0.4441
Epoch 12, Loss: 0.4373
Epoch 13, Loss: 0.4295
Epoch 14, Loss: 0.4214
Epoch 15, Loss: 0.4134
Epoch 16, Loss: 0.4043
Epoch 17, Loss: 0.3951
Epoch 18, Loss: 0.3850
Epoch 19, Loss: 0.3750
Epoch 20, Loss: 0.3645
Epoch 21, Loss: 0.3532
Epoch 22, Loss: 0.3423
Epoch 23, Loss: 0.3315
Epoch 24, Loss: 0.3191
Epoch 25, Loss: 0.3091
Epoch 26, Loss: 0.2983
Epoch 27, Loss: 0.2874
Epoch 28, Loss: 0.2766
Epoch 29, Loss: 0.2664
Epoch 30, Loss: 0.2562
Epoch 31, Loss: 0.2475
Epoch 32, Loss: 0.2382
Epoch 33, Loss: 0.2294
Epoch 34, Loss: 0.2222
Epoch 35, Loss: 0.2141
Epoch 36, Loss: 0.2070
Epoch 37, Loss: 0.2002
Epoch 38, Loss: 0.1942
Epoch 39, Loss: 0.1889
Epoch 40, Loss: 0.1832
Epoch 41, Loss: 0.1779
Epoch 42, Loss: 0.1736
Epoch 43, Loss: 0.1690
Epoch 44, Loss: 0.1646
Epoch 45, Loss: 0.1607
Epoch 46, Loss: 0.1572
Epoch 47, Loss: 0.1535
Epoch 48, Loss: 0.1497
Epoch 49, Loss: 0.1461
Epoch 50, Loss: 0.1434
Epoch 51, Loss: 0.1399
Epoch 52, Loss: 0.1375
Epoch 53, Loss: 0.1343
Epoch 54, Loss: 0.1314
Epoch 55, Loss: 0.1291
Epoch 56, Loss: 0.1268
Epoch 57, Loss: 0.1247
Epoch 58, Loss: 0.1223
Epoch 59, Loss: 0.1203
Epoch 60, Loss: 0.1190
Epoch 61, Loss: 0.1168
Epoch 62, Loss: 0.1152
Epoch 63, Loss: 0.1133
Epoch 64, Loss: 0.1123
Epoch 65, Loss: 0.1108
Epoch 66, Loss: 0.1094
Epoch 67, Loss: 0.1085
Epoch 68, Loss: 0.1071
Epoch 69, Loss: 0.1062
Epoch 70, Loss: 0.1049
Epoch 71, Loss: 0.1043
Epoch 72, Loss: 0.1030
Epoch 73, Loss: 0.1026
Epoch 74, Loss: 0.1013
Epoch 75, Loss: 0.1009
Epoch 76, Loss: 0.1002
Epoch 77, Loss: 0.0998
Epoch 78, Loss: 0.0988
Epoch 79, Loss: 0.0983
Epoch 80, Loss: 0.0979
Epoch 81, Loss: 0.0971
Epoch 82, Loss: 0.0964
Epoch 83, Loss: 0.0960
Epoch 84, Loss: 0.0956
Epoch 85, Loss: 0.0951
Epoch 86, Loss: 0.0943
Epoch 87, Loss: 0.0941
Epoch 88, Loss: 0.0935
Epoch 89, Loss: 0.0937
Epoch 90, Loss: 0.0928
Epoch 91, Loss: 0.0926
Epoch 92, Loss: 0.0928
Epoch 93, Loss: 0.0915
Epoch 94, Loss: 0.0917
Epoch 95, Loss: 0.0914
Epoch 96, Loss: 0.0909
Epoch 97, Loss: 0.0905
Epoch 98, Loss: 0.0902
Epoch 99, Loss: 0.0901
Epoch 100, Loss: 0.0897
Epoch 101, Loss: 0.0896
Epoch 102, Loss: 0.0892
Epoch 103, Loss: 0.0890
Epoch 104, Loss: 0.0891
Epoch 105, Loss: 0.0886
Epoch 106, Loss: 0.0886
Epoch 107, Loss: 0.0878
Epoch 108, Loss: 0.0883
Epoch 109, Loss: 0.0876
Epoch 110, Loss: 0.0876
Epoch 111, Loss: 0.0875
Epoch 112, Loss: 0.0874
Epoch 113, Loss: 0.0870
Epoch 114, Loss: 0.0870
Epoch 115, Loss: 0.0865
Epoch 116, Loss: 0.0863
Epoch 117, Loss: 0.0864
Epoch 118, Loss: 0.0864
Epoch 119, Loss: 0.0858
Epoch 120, Loss: 0.0858
Epoch 121, Loss: 0.0856
Epoch 122, Loss: 0.0855
Epoch 123, Loss: 0.0857
Epoch 124, Loss: 0.0853
Epoch 125, Loss: 0.0852
Epoch 126, Loss: 0.0852
Epoch 127, Loss: 0.0849
Epoch 128, Loss: 0.0849
Epoch 129, Loss: 0.0847
Epoch 130, Loss: 0.0844
Epoch 131, Loss: 0.0842
Epoch 132, Loss: 0.0846
Epoch 133, Loss: 0.0843
Epoch 134, Loss: 0.0842
Epoch 135, Loss: 0.0840
Epoch 136, Loss: 0.0838
Epoch 137, Loss: 0.0838
Epoch 138, Loss: 0.0839
Epoch 139, Loss: 0.0836
Epoch 140, Loss: 0.0837
Epoch 141, Loss: 0.0833
Epoch 142, Loss: 0.0830
Epoch 143, Loss: 0.0835
Epoch 144, Loss: 0.0832
Epoch 145, Loss: 0.0831
Epoch 146, Loss: 0.0828
Epoch 147, Loss: 0.0830
Epoch 148, Loss: 0.0830
Epoch 149, Loss: 0.0825
Epoch 150, Loss: 0.0827

In [3]:
# Generation
def generate(model, tokenizer, xlogp_val, max_len=1000):
    try:
        prompt = f"polarizability: {xlogp_val} selfies:"
        inputs = tokenizer(prompt, return_tensors='pt').to(device)
        outputs = model.generate(**inputs, max_length=max_len, num_beams=1, do_sample=True, temperature=0.9, top_p=0.9)
        gen_text = tokenizer.decode(outputs[0])
        selfies = gen_text.split("selfies:")[1].strip() if "selfies:" in gen_text else None
        selfies = selfies.split('[PAD]')[0]
        selfies = selfies.replace("\\", "/")
        smiles = sf.decoder(selfies)
        valid = smiles and Chem.MolFromSmiles(smiles) is not None
        print(f"{smiles} - Valid: {valid}")
        return smiles
    except Exception as e:
        print(e)
        return None

In [4]:
import numpy as np
from tqdm import tqdm

values_vec = np.linspace(0, df_polarizability['static_polarizability'].max(), 350)
smiles_test_df = pd.DataFrame()

for i in tqdm(values_vec):
    smiles = generate(model, tokenizer, i)
    polarizability_scaled = i

    if smiles is not None:
        smiles_test_df = pd.concat([smiles_test_df, pd.DataFrame({'smiles': smiles, 
                                                                'static_polarizability': polarizability_scaled}, index=[0])]).reset_index(drop=True)

  0%|          | 0/350 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 1/350 [00:04<27:20,  4.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)O - Valid: True

  1%|          | 2/350 [00:09<26:25,  4.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1].[NH4+1] - Valid: True

  1%|          | 3/350 [00:13<26:04,  4.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1].[K+1] - Valid: True

  1%|          | 4/350 [00:18<25:53,  4.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[=NH+1]'
	SELFIES: [C][=C][C][=Branch1][C][=O][O-1].[C][=NH+1][Branch1][C][C][C][O]

  1%|▏         | 5/350 [00:22<25:44,  4.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN - Valid: True

  2%|▏         | 6/350 [00:26<25:36,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN - Valid: True

  2%|▏         | 7/350 [00:31<25:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)COC(=O)C - Valid: True

  2%|▏         | 8/350 [00:35<25:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)[O-1].O.[Na+1] - Valid: True

  3%|▎         | 9/350 [00:40<25:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)C(F)(F)F - Valid: True

  3%|▎         | 10/350 [00:44<25:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCO - Valid: True

  3%|▎         | 11/350 [00:49<25:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC[C@@H1](C=O)O - Valid: True

  3%|▎         | 12/350 [00:53<25:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC(Cl)Cl - Valid: True

  4%|▎         | 13/350 [00:58<25:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C=C - Valid: True

  4%|▍         | 14/350 [01:02<24:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)NCl - Valid: True

  4%|▍         | 15/350 [01:07<24:52,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCS(=O)(=O)O - Valid: True

  5%|▍         | 16/350 [01:11<24:47,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C(=C)CP(=O)(O)O - Valid: True

  5%|▍         | 17/350 [01:15<24:42,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NCC(=C)C(=O)OC - Valid: True

  5%|▌         | 18/350 [01:20<24:38,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCCC#N - Valid: True

  5%|▌         | 19/350 [01:24<24:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC(=O)ON=[N+1]=[N-1] - Valid: True

  6%|▌         | 20/350 [01:29<24:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/NC - Valid: True

  6%|▌         | 21/350 [01:33<24:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN1CCOC1 - Valid: True

  6%|▋         | 22/350 [01:38<24:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCC(C(C(C(C(F)(F)F)(F)F)F)F)F - Valid: True

  7%|▋         | 23/350 [01:42<24:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN=C=O - Valid: True

  7%|▋         | 24/350 [01:47<24:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCOC(=O)C=C - Valid: True

  7%|▋         | 25/350 [01:51<24:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCN1CCCCC1 - Valid: True

  7%|▋         | 26/350 [01:56<24:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=CNC1CCCC1 - Valid: True

  8%|▊         | 27/350 [02:00<23:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCOC=C - Valid: True

  8%|▊         | 28/350 [02:05<23:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC=C(C=C1)O - Valid: True

  8%|▊         | 29/350 [02:09<23:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)CCOC(=O)C=C - Valid: True

  9%|▊         | 30/350 [02:13<23:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC(C(C(C(C(F)F)F)F)F)F - Valid: True

  9%|▉         | 31/350 [02:18<23:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCCOC(=O)C(=C)CCO - Valid: True

  9%|▉         | 32/350 [02:22<23:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=CN1 - Valid: True

  9%|▉         | 33/350 [02:27<23:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN1C=CC(=N1)C=CC(=O)OC - Valid: True

 10%|▉         | 34/350 [02:31<23:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CNC=C1 - Valid: True

 10%|█         | 35/350 [02:36<23:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)C(=C=O)NC(=C)C(=O)OC - Valid: True

 10%|█         | 36/350 [02:40<23:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)[N+1](=O)[O-1] - Valid: True

 11%|█         | 37/350 [02:45<23:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=CN1 - Valid: True

 11%|█         | 38/350 [02:49<23:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C1=CC=CC=C1)OC(=O)C=C - Valid: True

 11%|█         | 39/350 [02:54<23:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC(=CC=C1)N - Valid: True

 11%|█▏        | 40/350 [02:58<23:02,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=NC=C1)N - Valid: True

 12%|█▏        | 41/350 [03:02<22:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C(F)(F)F - Valid: True

 12%|█▏        | 42/350 [03:07<22:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C(=C/C1=CC=C(C=C1)F)/C#N - Valid: True

 12%|█▏        | 43/350 [03:11<22:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(Cl)Cl)C1=CC=C(C=C1)F - Valid: True

 13%|█▎        | 44/350 [03:16<22:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=CC(=C1)C - Valid: True

 13%|█▎        | 45/350 [03:20<22:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC(=C1)O)CO - Valid: True

 13%|█▎        | 46/350 [03:25<22:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCC(C(C(C(F)(F)F)(F)F)(F)F)(C(F)(F)F)F - Valid: True

 13%|█▎        | 47/350 [03:29<22:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)C=O - Valid: True

 14%|█▎        | 48/350 [03:34<22:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)Br - Valid: True

 14%|█▍        | 49/350 [03:38<22:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C12)CCCC2 - Valid: True

 14%|█▍        | 50/350 [03:43<22:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Br)[N+1](=O)[O-1] - Valid: True

 15%|█▍        | 51/350 [03:47<22:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)Cl)[N+1](=O)[O-1] - Valid: True

 15%|█▍        | 52/350 [03:52<22:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)Cl)N2C=NN=N2 - Valid: True

 15%|█▌        | 53/350 [03:56<22:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN(C)/C=C(/C(=O)O)C/S(=O)(=O)C1=C(C=C(C(=C1)F)O)F - Valid: True

 15%|█▌        | 54/350 [04:00<21:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)OC)/C#N - Valid: True

 16%|█▌        | 55/350 [04:05<21:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)Cl)NC(=O)C - Valid: True

 16%|█▌        | 56/350 [04:09<21:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=CO1)NC=C(C=C)C(F)(F)F - Valid: True

 16%|█▋        | 57/350 [04:14<21:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C(=C)C1=CC=C(C=C1)C=O - Valid: True

 17%|█▋        | 58/350 [04:18<21:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CN(C)C)C(=O)C1=CC(=C(C(=C1F)OC)F)F - Valid: True

 17%|█▋        | 59/350 [04:23<21:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)C(=O)OCCO - Valid: True

 17%|█▋        | 60/350 [04:27<21:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)OCC2=CC=C(C=C2)F - Valid: True

 17%|█▋        | 61/350 [04:32<21:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/[C@@]1CCCN1C(=O)C2=CC=CC=C2 - Valid: True

 18%|█▊        | 62/350 [04:36<21:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=C(C=CC(=C1)OC)OC)/C#N - Valid: True

 18%|█▊        | 63/350 [04:41<21:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CNC1=CC=C(C=C1)O)CC#N - Valid: True

 18%|█▊        | 64/350 [04:45<21:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)Br)OC(F)(F)F - Valid: True

 19%|█▊        | 65/350 [04:49<21:09,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC(=C(C=C1)OC)/C=C/C(=O)OC(C)(C)C - Valid: True

 19%|█▉        | 66/350 [04:54<21:05,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CN(C)C)C1=C(C=C(C=C1)C#N)Cl - Valid: True

 19%|█▉        | 67/350 [04:58<21:00,  4.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CSC1=CC=C(C=C1OCBr)NC)CCO - Valid: True

 19%|█▉        | 68/350 [05:03<20:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(C=C1Cl)F)F)O)C=NCCO - Valid: True

 20%|█▉        | 69/350 [05:07<20:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)C(=CCCC)SC(=N)N1CC(C1)OC(=O)/C=C/C2=CC=CO2 - Valid: True

 20%|██        | 70/350 [05:12<20:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)OCC2=C(C=C(C=C2)F)Cl - Valid: True

 20%|██        | 71/350 [05:16<20:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/C1=CC=C(C=C1)OCC2=CC=CC=C2F - Valid: True

 21%|██        | 72/350 [05:21<20:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OCC2=CC(=CC=C2)F - Valid: True

 21%|██        | 73/350 [05:25<20:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=NC=C1)C2=CC=C(C=C2)Br - Valid: True

 21%|██        | 74/350 [05:30<20:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)OCC2=C(C=C(C=C2)F)Cl - Valid: True

 21%|██▏       | 75/350 [05:34<20:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=CC=C1OC)/P(=O)(OCC)OCC - Valid: True

 22%|██▏       | 76/350 [05:39<20:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OCC2=C(C=C(C=C2)Cl)Cl - Valid: True

 22%|██▏       | 77/350 [05:43<20:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC=C1COC2=C(C=C(C=C2)/C=C/C(=O)OC)Br - Valid: True

 22%|██▏       | 78/350 [05:47<20:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCOC1=CC=C(C=C1)C2=CC=CC=C2 - Valid: True

 23%|██▎       | 79/350 [05:52<20:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C2=C(C=C(C=C2)Cl)Cl - Valid: True

 23%|██▎       | 80/350 [05:56<20:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CCOC(=O)/C=C/C1=CC=C(O1)C2=CC(=C(C=C2)Cl)Cl - Valid: True

 23%|██▎       | 81/350 [06:01<19:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C=CC(=C1)CC=C)OC(=O)/C=C/C2=CC=C(C=C2)OC - Valid: True

 23%|██▎       | 82/350 [06:05<19:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=CO1)C2=NC(=NS2)C3=CC=CC=C3C#N - Valid: True

 24%|██▎       | 83/350 [06:10<19:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C2=CN=C(O2)C3CC3 - Valid: True

 24%|██▍       | 84/350 [06:14<19:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=CC=C(C=C2)Cl)Br - Valid: True

 24%|██▍       | 85/350 [06:19<19:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(N=C1Cl)Cl)F)O)C=NC2=C(C=C(C=C2)F)F - Valid: True

 25%|██▍       | 86/350 [06:23<19:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C(=C1)Br)OCC2=CC=C(C=C2)[N+1]=O)[O-1] - Valid: True

 25%|██▍       | 87/350 [06:28<19:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OCC#C)Cl)OCC2=CC=C(C=C2)F - Valid: True

 25%|██▌       | 88/350 [06:32<19:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C2=CC=C(O2)/C=C/C(=O)OCC=C[N+1](=O)[O-1] - Valid: True

 25%|██▌       | 89/350 [06:36<19:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)C(C(=O)NC2=CC=CC=C2C=O)OC(=O)C=C - Valid: True

 26%|██▌       | 90/350 [06:41<19:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(O1)C=C(C=C2)OCC3=CC=C(C=C3)Br - Valid: True

 26%|██▌       | 91/350 [06:45<19:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C#CCOC(=O)/C=C/C1=CC(=C(C=C1)OCC2=C(C=C(C=C2)F)Cl)Cl - Valid: True

 26%|██▋       | 92/350 [06:50<19:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OCC=C)I)OCC2=CC(=CC=C2)F - Valid: True

 27%|██▋       | 93/350 [06:54<19:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)/C(=C/NC2=CC=C(C=C2)OCC=O)C=O - Valid: True

 27%|██▋       | 94/350 [06:59<19:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=C(C=C(C=C2)F)Cl - Valid: True

 27%|██▋       | 95/350 [07:03<18:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(C2=CC=C(C=C2)C3=CC=CC=C3C)C=O - Valid: True

 27%|██▋       | 96/350 [07:08<18:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCCOC)OC2=NC=C(C=C2C)NCCOC=C(C3=CCCC=C3)F - Valid: True

 28%|██▊       | 97/350 [07:12<18:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)C(=O)N/C(=C/C2=CC(=CC=C2)[N+1](=O)[O-1])/C(=O)OCC=C3CC=CC=C3 - Valid: True

 28%|██▊       | 98/350 [07:17<18:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCC(COC(C)C)O)OC2=CC=C(C=N2)CC(F)F - Valid: True

 28%|██▊       | 99/350 [07:21<18:39,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C=C1C(OC(C(=C1)I)OCC2=CC=C(C=C2)F)Cl - Valid: True

[07:17:25] Conflicting single bond directions around double bond at index 17.
[07:17:25]   BondStereo set to STEREONONE and single bond directions set to NONE.
 29%|██▊       | 100/350 [07:26<18:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C=NC=C2)/C=C(/C#N)/C(=O)OCC - Valid: True

 29%|██▉       | 101/350 [07:30<18:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=NN1CC2=C(C=C(C=C2)C(F)(F)F)O)CC=CC3=CC=CC=C3 - Valid: True

 29%|██▉       | 102/350 [07:34<18:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)COC2=C(C=C(C=C2Br)/C=C/C(=O)OCC=C)OC - Valid: True

 29%|██▉       | 103/350 [07:39<18:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)[N+1](=O)[O-1])NC(=O)C2=CC=CC=C2C=N - Valid: True

 30%|██▉       | 104/350 [07:43<18:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(O1)C2=C(C=C(C=C2)Br)OC3=C(C=C(C=N3)C(F)(F)F)F - Valid: True

 30%|███       | 105/350 [07:48<18:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC1=CC=C(C=C1)C=C.CC(C)(C)OC(=O)/C=C/C2=CC=C(C=C2)O - Valid: True

 30%|███       | 106/350 [07:52<18:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)OCC2=C(C=C3C=N2)F)C=C3F - Valid: True

 31%|███       | 107/350 [07:57<18:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=CC=C1NCC2=NC=C(C=C23)C(=O)NC(=O)C=C4CC=CC=C43 - Valid: True

 31%|███       | 108/350 [08:01<18:00,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1CCN(CC1)C2=NC3=C(S2)C=C(C=C3)OC(=O)C=CC4=CC(=CC=C4)F - Valid: True

 31%|███       | 109/350 [08:06<17:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C(CCC2=C1C(=C3C=C2)C#N)(O)/C=C/C=CC=CCC3 - Valid: True

 31%|███▏      | 110/350 [08:10<17:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C(=CS1)C2=C(C=C(C=C2)Cl)OC)C=C(C=CCC=C(C3C=CCC)C3)F - Valid: True

 32%|███▏      | 111/350 [08:15<17:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)C2=CC=C(C=C2)C3=CC=CC=C3C=CC=CCC(CC)=O - Valid: True

 32%|███▏      | 112/350 [08:19<17:42,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=N1)N([C@@H1]2CCN(C2)C3CCCCC3C4)CC=C(C=C4)OOCCCOC=C=C - Valid: True

 32%|███▏      | 113/350 [08:24<17:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SC2C3=CC=CC=C3)NC4=CC(=C(C=C24)F)OCC(F)F - Valid: True

 33%|███▎      | 114/350 [08:28<17:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)S(=O)(=O)NC(=O)NC(=O)N2C3=CC=CC=C3C=N2 - Valid: True

 33%|███▎      | 115/350 [08:32<17:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)CC1=CC=C(N1C2=C(C=C(C=C2)Cl)C(C=C(C(=O)C=CCC3=C)S)S)S3CCC(=N)C=O - Valid: True

 33%|███▎      | 116/350 [08:37<17:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCOC1=CC=C(C=C1)C2=CC(=C(C=C2)N3CCOCC3)/C=C/C(=O)OCC - Valid: True

[07:18:41] Conflicting single bond directions around double bond at index 19.
[07:18:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
 33%|███▎      | 117/350 [08:41<17:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1N(CCCC1C2=CC=CC=C2)C3=CC=C(C=C3)/C=C(/C#N)/C(=O)OCC - Valid: True

 34%|███▎      | 118/350 [08:46<17:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)OC=C(C=CCC)CC2=C(C=CC=C2)Cl - Valid: True

 34%|███▍      | 119/350 [08:50<17:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)OCF)F - Valid: True

 34%|███▍      | 120/350 [08:55<17:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)F)F - Valid: True

 35%|███▍      | 121/350 [08:59<17:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC(=C(C=C1)C=CC(=O)OCC2=CC(=CC=C2)NCCOC(=O)/C=C/C=C3C=C(CC=C3)CO)COCCCOC - Valid: True

 35%|███▍      | 122/350 [09:04<16:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)OC2=C(SC3=C2C=CC(=C3)O)C=C4C(=CC(C=N4)CC=CCCC)CCC=O - Valid: True

 35%|███▌      | 123/350 [09:08<16:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CC2CCN(CC2)CC3=CC=C(C=C3)/C=C(/C=CC=C4CCC=CC4/C=C)CCCC/C(=C)C=CCCOCO - Valid: True

 35%|███▌      | 124/350 [09:13<16:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)C(C)C)OC(=O)CC2=CC=C(C=C2C)CNC(=O)C=CCCCC(CCCC)F - Valid: True

 36%|███▌      | 125/350 [09:17<16:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C(C1=CC=CC(=C1)OCC2=CC3=CC=CC=C3N2)CC=CCC4=CC(CC=C4)CC#N - Valid: True

 36%|███▌      | 126/350 [09:22<16:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC2=C(C=C1Cl)OC(=O)C(=C2C3=CC(=CC=C3)OCOC=C4C=C)C(C=C4)COC - Valid: True

 36%|███▋      | 127/350 [09:26<16:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OCCC(F)(F)F - Valid: True

 37%|███▋      | 128/350 [09:30<16:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1COC(=O)/C(=C/C2=CC=C(C=C2)CN3CCN(CC3)CCNC(=O)C=CC=CN1)CCF - Valid: True

 37%|███▋      | 129/350 [09:35<16:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)S(=O)(=O)C2=CC=CC)C23N=CC=C3OC=CC(CCC=CC4C=CCC)C4(N)OC - Valid: True

 37%|███▋      | 130/350 [09:39<16:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)CCNC2=C(C=C(C=C2)C=CC=O)C=CCC(=CS=CS(#C3)=N3)CC(C(C)CCCCCCCCC)CC4CC4(C)CO - Valid: True

 37%|███▋      | 131/350 [09:44<16:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=CC=N1)C[C@@H1](C(=O)O)N.C(=O)NC(=O)N/N=C/C(=O)C=C2C=CC=CC2 - Valid: True

[07:19:48] Conflicting single bond directions around double bond at index 15.
[07:19:48]   BondStereo set to STEREONONE and single bond directions set to NONE.
 38%|███▊      | 132/350 [09:48<16:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)C1=CC=C(C=C1)C2=CC=C(S2)/C=C(/C#N)/C(=O)OC - Valid: True

 38%|███▊      | 133/350 [09:53<16:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1COC(=O)/C(=C/C2=CN(C3=CC=CC=C32)C4=CC=CC=C4)/C(=NC=C1C)CCC(C)NCC(CC=NCC)OC(C(C)CCC=C5CCC)CCCCC6C=CCCC56C - Valid: True

[07:19:57] Conflicting single bond directions around double bond at index 13.
[07:19:57]   BondStereo set to STEREONONE and single bond directions set to NONE.
 38%|███▊      | 134/350 [09:57<16:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=C(C=C(C=C3)F)F)F - Valid: True

 39%|███▊      | 135/350 [10:02<15:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCC=C(C1=CC=C(C=C1)CC(=O)NC2=CC=CC=C2)CC=CC(=O)OC - Valid: True

 39%|███▉      | 136/350 [10:06<15:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=CC=C(C=C1)C2=NC(=C(S2)COC3=CC=C(C=C3)S(=O)(=O)C)ONN(C)CCCCOC - Valid: True

 39%|███▉      | 137/350 [10:11<15:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)N(C)C2=CSC3=C2C=CC(=C3)O)OCC=CCCC=CCC - Valid: True

 39%|███▉      | 138/350 [10:15<15:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=C(N(C2=CC=CC=C21)CC3=CC=C(C=C3)C)C=CC4=C5C(=O)ON4CC=O)C=CCCCC5 - Valid: True

 40%|███▉      | 139/350 [10:20<15:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)/C=C/C(=O)C2=CC(=CC=C2)OOC=C(CC=CCC)CCC(C)CCC(C)CC - Valid: True

 40%|████      | 140/350 [10:24<15:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=C(C=C1)N2CCN(CC2)CCNC(=O)C=CC=C=CN=C(C#C)N(C)CSC)CF - Valid: True

 40%|████      | 141/350 [10:28<15:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1C2=CC(=O)C3=C(O2)C(=C(C=C3C)O)C=O.C=CCC(C)CC=CCC=O - Valid: True

 41%|████      | 142/350 [10:33<15:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)Cl)Cl - Valid: True

 41%|████      | 143/350 [10:37<15:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=CC(=N1)/C=C/C(=O)C2=CC=C(C=C2)/C=C(/C=NC=NC=CC3C=NCN)C3/C=CCC=CC(C)CCCCCCCC4=CCC/O4 - Valid: True

 41%|████      | 144/350 [10:42<15:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)NC3=C(C=C(C=C3)Cl)Cl - Valid: True

 41%|████▏     | 145/350 [10:46<15:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)N(CCC#N)C2CC#N)C=C2C(C)(F)F - Valid: True

 42%|████▏     | 146/350 [10:51<15:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CC1=CC=C(C=C1)N(C)COC(=O)C=C.C=CC(=O)[O-1] - Valid: True

 42%|████▏     | 147/350 [10:55<15:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)N(C)C2=C(SC3=C2C=CC(=C3)O)C=CC4=CC=C=CC4F - Valid: True

 42%|████▏     | 148/350 [11:00<15:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[/-Branch1]'
	SELFIES: [C][C][C][C][O][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=Branch1][C][=O][N][/C][=Branch1][P][=C][/C][=C][C][=Branch1][=Branch1][=C][C][=C][Ring1][=Branch1][N+1][=Branch1][C][=O][O-1][/C][=Branch1][C][=O][O][C][=C][/C][=C][C][=Branch1][=Branch1][=C][N][=C][N][N][=C][Ring1][S][S][/-Ring1][S][C][/-Branch1][C][=C][=Branch1][C][C][=O][C][=Branch1][C][C][Branch1][=N][Ring1][=N][C][=C][C]

 43%|████▎     | 149/350 [11:04<14:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(NCC1)N=CN=C2NC3=CC(=C(C=C3)NCC(=O)NC=CC(CCCC)CCCCCNCC)CCNCCCC - Valid: True

 43%|████▎     | 150/350 [11:09<14:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=C(SC3=C2C=CC(=C3)OO)C=CCCC=C(N=C(CCC=C)C)N=NOCCC=CCC4CCCC=C4CC=CCC=CCCCC=CCC(C)C=C(C)CCCC=CC(C)CCC - Valid: True

 43%|████▎     | 151/350 [11:13<14:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C2=C(C=CC(=C2)Cl)NC(=O)CCCCCCCN(CCC)CCCCC=CCCC(CC=CCC(C)C=C)CC=CCC - Valid: True

 43%|████▎     | 152/350 [11:18<14:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C=CC=CC=CSS - Valid: True

 44%|████▎     | 153/350 [11:22<14:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)C=CC3=CC=CC#C3)C=C(N)C=NC(C)CCCCCCC=CC - Valid: True

 44%|████▍     | 154/350 [11:26<14:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)CCCCCNC2=C(C=C(C=C2)CCCCC=CCCCC)CF - Valid: True

 44%|████▍     | 155/350 [11:31<14:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C(=C)C(=O)NC2=NC=C(C=C2)C3=CC=CC=C3S(=O)(=O)N(C)CC=C4CC=CC=C41 - Valid: True

 45%|████▍     | 156/350 [11:35<14:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=CC(=C1)[N+1](=O)[O-1])NC(=O)CCCCCNC(=O)C=CC(C)ON(C)C(C)F - Valid: True

 45%|████▍     | 157/350 [11:40<14:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)N(C(=O)CCCCCNC)C=O - Valid: True

 45%|████▌     | 158/350 [11:44<14:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[=Branch1=Branch1]'
	SELFIES: [C][C@H1][C@@H1][Branch2][#Branch1][P][C@H1][Branch2][#Branch1][N][C@H1][Branch2][#Branch1][#Branch1][C@@H1][Branch1][Ring2][O][Ring1][=Branch1][O][C@@H1][C@H1][Branch2][=Branch1][#Branch2][C@@H1][Branch2][=Branch1][Ring2][C@@H1][Branch1][=Branch1][O][C@@H1][C][Branch1][Ring2][O][Ring1][=Branch1][O][O][O][C][O][C@@H1][C@@H1][C][Branch2][Branch2][Branch1][Branch1][Branch1][Branch1][C][C][C][C][C][C][C][C][C][=C][=C][C][C][=C][C][C][Branch2][=Branch2][=Branch1][C][C][C][=Branch2][C][C][C][=C][=Branch1][C][=Branch1][C][=Branch1][C][C][=C][C][C][=C][C][C][C][=Branch1][C][=Branch1][C][C][=Branch1][C][=Branch1][C][C][C][=C][C][C][C][C][C][C][C][=Branch1][C][C][=Branch1][C][=Branch1][C][C][C][=Branch1][C][C][C][C][C][C][=Branch1][C][C][C][C][C][C][C][C][C][C][=Branch1][C][C][C][C][C][C][C][C][=Branch1][C][C][C][C][=Branch1][C][C][C][C][C][=Branch1][C][C][C][=Branch1][C][C][C][C][C][C][=Branch1][C][C][C][C][=Branch1=Branch1][C][C][C][C][C][C][C][C][C][C][C][=Branch1=Branch1][C][C][C][C][C][C][C][C][C][C][C][C][C]99-1][=Branch11]

 45%|████▌     | 159/350 [11:49<14:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 46%|████▌     | 160/350 [11:53<14:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCOC1=CC=C(C=C1)NC(=O)C(CCCN)NC(=O)[C@@](C[C@H1](CCCCC=CCCC(C=CCC=C)CC)CCF)F - Valid: True

 46%|████▌     | 161/350 [11:58<14:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C12)C(=O)C=CC(=CC(=N2)C3=CC=CC(=C3)C4=CCO)NC=CCC=CCC5C=C45 - Valid: True

 46%|████▋     | 162/350 [12:02<13:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C/C(=O)C=CC(=C(SNC)C2C=CCO2)C=C)C=CCCC(C)CCC(C)CCC - Valid: True

 47%|████▋     | 163/350 [12:07<13:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C(=O)N/C(=C/C2=C(C=C(C=C2)OC)OC(=O)C=CCC(=O)NNC=CC(C)CCC)CCOC=C - Valid: True

[07:22:11] Conflicting single bond directions around double bond at index 13.
[07:22:11]   BondStereo set to STEREONONE and single bond directions set to NONE.
 47%|████▋     | 164/350 [12:11<13:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C=C(/C2CCC2)/C3=C(C=C(C=C3)NNCCC)CCCO - Valid: True

[07:22:15] Conflicting single bond directions around double bond at index 14.
[07:22:15]   BondStereo set to STEREONONE and single bond directions set to NONE.
 47%|████▋     | 165/350 [12:16<13:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=CC=C(C=C1)C2=NN(C=C2/C=C(/C#N)/C(=O)OCCC3=CC=CC=C3)C=C(C)C(F)F - Valid: True

 47%|████▋     | 166/350 [12:20<13:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C@H1][C@@H1][Branch2][#Branch1][P][C@H1][Branch2][#Branch1][N][C@H1][Branch2][#Branch1][#Branch1][C@@H1][Branch1][Ring2][O][Ring1][=Branch1][O][C@@H1][C@@H1][Branch2][=Branch1][#Branch2][C@@H1][Branch2][Ring2][O][C][=C][Branch2][Ring2][Ring2][Ring2][O][C][=C][Branch2][Ring1][=Branch1][C][C][=C][Branch1][=Branch1][=C][C][C][F][Branch1][=Branch1][F][F][F][F][F][F][C][C][Branch1][Branch1][F][Branch1][C][F][F][C][F][C][C][C][Branch1][C][=C][C][C][=Branch1][=C][C][C][C][C][C][=Branch1][C][C][=Branch1][=C][C][C][=Branch1][C][=Branch1][C][C][=Branch1][C][C][=Branch1][C][=C][C][C][C][C][=C][C][C][C][=Branch1][C][C][C][C][C][C][C][C][C][C][C][=Branch1][C][C][C][=Branch1][C][C][C][=Branch1][C][C][C][=Branch1][C][C][=Branch1][=Branch1][C][C][C][=Branch1][=Branch1][C][C][=Branch1][C][=C][C][C][C][C][=C][C][C][C][C][C][C][C][C][C][C][C][=C][C][C][=Branch1][C][C][C][C][C][C][C][=Branch1][C][C][C][C][C][C][C][C][C]C]

 48%|████▊     | 167/350 [12:24<13:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCCCCOC(=O)C(=C)C - Valid: True

 48%|████▊     | 168/350 [12:29<13:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 48%|████▊     | 169/350 [12:33<13:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC(=C1C2=NC3=C(N2)C=C(C=C3)C(=O)N/4C=CC=C4C=CSS)O)NC(C)OCNN=C(CC5C(S)C6SSC=C6CC)NSC=C5CC=C(N)C(C)C=C=O - Valid: True

 49%|████▊     | 170/350 [12:38<13:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 49%|████▉     | 171/350 [12:42<13:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[=800800]'
	SELFIES: [C][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][S][=Branch1][C][=O][=Branch1][C][=O][N][C][=Branch2][Ring2][Branch2][=C][Branch1][#C][C][=Branch1][Ring2][=C][Ring1][Branch1][C][=Branch1][C][=O][N][C][=C][Branch1][C][C][C][C][C][=Branch1][C][=O][N][C][=Branch1][C][C][=Branch1][C][C][=O][C][C][C][C][=Branch1][C][C][C][=C][C][C][C][C][C][C][C][=Branch1][C][=Branch1][C][=C][C][C][C][=Branch1][C][C][=C][C][C][C][C][C][=C][C][C][C][C][=C][C][C][Ring1][=C][C][C][=C][C][C][C][C][Ring1][=C][C][=C][Ring1][=C][=800800]

[07:22:46] Conflicting single bond directions around double bond at index 13.
[07:22:46]   BondStereo set to STEREONONE and single bond directions set to NONE.
 49%|████▉     | 172/350 [12:47<13:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=C(C=C(C=C3)CNN=CC)C)OC#CC=C - Valid: True

 49%|████▉     | 173/350 [12:51<13:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(C2=CC3=C(C=C2)C=C(C=C3)OC(=C)CCC=O)CC(=C)CCCCCCC(C)CC(C)C - Valid: True

 50%|████▉     | 174/350 [12:56<13:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCOC1=CC=C(C=C1)C2=CN=C(S2)C3=CC4=C(C=C3)C=C(C=C4)OCC(=O)OC - Valid: True

 50%|█████     | 175/350 [13:00<13:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[65601]'
	SELFIES: [C][C][C][C][O][C][=Branch1][C][=O][C][=C].[C][C][=Branch1][C][=C][C][=Branch1][C][=O][O][C].[C][=C][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][=C][C][=C][C][=C][Ring1][=Branch1].[C][=C][C][C][=Branch1][C][=Branch1][C][C][=C][C][=Branch1][C][C][=O][O][C][65601]

 50%|█████     | 176/350 [13:05<12:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol 'C]'
	SELFIES: [C][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][S][=Branch1][C][=O][=Branch1][C][=O][N][C][=Branch2][Ring2][Branch2][=C][Branch1][#Branch1][C][C][C][C][Ring1][Branch1][C][=N][N][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][C][=C][Branch1][Branch1][C][=Branch1][C][C][=Branch1][C][C][C][C][C][=Branch1][C][C][C][C][=O][C][C][C][=Branch1][C][C][=Branch1][C][C][=C][C][C][C][C][C][C][C].[C][C][=Branch1][C][C][C][C][=Branch1][C][C][=Branch1][C][=C][C][C][=Branch1][C][=C][C][C][C][C][C][=Branch1][C][C][C][C][C][C][C][C].[C][=Branch1][C][C][=Branch1][C][=Branch1][C][C][=Branch1][C][C][C][C][C][C][=Branch1][C][C][C][C][C][C]C][C]C][C]C]C][=Branch1][=Branch1][C][=Branch1][=Branch1][C][=C][C][C][C][C][C][C][=Branch1][C][C][C][=Branch1][C][C][C][=Branch1][C][C][C][C][=Branch1][C][C][C][C][C][=Branch1][C][C][C]987C][C]C]C][C]C]

 51%|█████     | 177/350 [13:09<12:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCCCCOC(=O)C(=C)C(C)CC.C=CCC=CCC(C)C(C)CCCCC - Valid: True

[07:23:13] Conflicting single bond directions around double bond at index 13.
[07:23:13]   BondStereo set to STEREONONE and single bond directions set to NONE.
 51%|█████     | 178/350 [13:13<12:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=CC=CC=C3)CCCCCO - Valid: True

 51%|█████     | 179/350 [13:18<12:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[19191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919]'
	SELFIES: [C][=C][C][=Branch2][Branch1][C][=C][Branch2][Ring2][S][C][=C][Ring1][=Branch1][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O][C][=Branch1][C][=O][/C][=C][/C][=C][C][=Branch1][=Branch2][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O][O][O][O][C][S][=Branch1][C][=O][N][=C][Branch1][C][=Branch2][C][C][=O][C][C][S][S][Branch2][=Branch1][S][S][Ring2][S][=C][S][Branch2][Ring2][=N][S][S][Branch1][C][=Branch1][C][N][N][C][=C][S][=C][S][Ring2][Ring2][=Branch1][S][S][C][C][Ring2][=Branch1][C][C][C][S][=Branch1][C][S][C][Branch1][C][=C][=C][C][Branch1][S][C][=Branch1][=Branch1][C][=N][C][C][C][=C][C][=Branch1][C][=Branch1][C][C][C][=Branch1][C][C][=Branch1][C][C][C][=Branch1][C][=Branch1][C][=C][=C][C][C][C][C][=Branch1][C][=Branch1][C][=Branch1][C][C][C][=Branch1][C][C][C][=C][Branch1][=C][=Branch1][C][C][=Branch1][=Branch1][=Branch1][C][C][C][=Branch1][C][C][=Branch1][C][C][C][=C][C][=Branch1][C][=Branch1][C][C][C][C][C][=Branch1][=Branch1][C][C][C][=Branch1][C][C][=Branch1][=Branch1][=Branch1][C][C][=Branch1][=Branch1][=Branch1][C][C][C][C][C][C][=Branch1][C][C][C][=Branch1][Branch1][=Branch1][=Branch191919=Branch1][C][C][=C][C][=Branch1][C][C][C][C][=C][C][19191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919191919]1919191919191919]19041903]19190419O][C]1903 [C]190419524 [C]1903 [O][C][O][O][O][C] [C][C][

 51%|█████▏    | 180/350 [13:22<12:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)NC(=CC1=C(C=C(C=C1)C#N)OC2[C@@H1]CCC(=O)OCC=CC=CC=C2CC=C)C=CCC(C)CCCC(C)CCCCCCCCCCCCCCCCCCCCCCC=CCCCC3=C4C3(CCCC#C4)C#N.C=CCC=C=CC=O - Valid: True

 52%|█████▏    | 181/350 [13:27<12:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N(N=C1)C)C2=CC=C(C=C2)C(F)(F)F - Valid: True

 52%|█████▏    | 182/350 [13:31<12:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)C1=CC=C(C=C1)C=C(N=CC(=C(S)Br)C)C=O - Valid: True

 52%|█████▏    | 183/350 [13:36<12:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCOC(=O)C(=C)C - Valid: True

 53%|█████▎    | 184/350 [13:40<12:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCN(C(C)C)C1=C(C=C(C=C1)/C=C/C(=O)OCC2)C(C=C(C=N2)C=CCC=CCC/C)(C)C=CC=O - Valid: True

 53%|█████▎    | 185/350 [13:45<12:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CNC(=C1)C(=O)N(CCCCCCN(C)C(C)CCCCC=CC=CC)CCC=CCCCC - Valid: True

 53%|█████▎    | 186/350 [13:49<12:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCCCCCOC(=O)C(=C)C=C - Valid: True

 53%|█████▎    | 187/350 [13:54<12:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)/C=C/C=NC1=C(C=C(C=C1)NC(=O)CC2CCC2)N=O - Valid: True

 54%|█████▎    | 188/350 [13:58<12:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=CC1=CC=C(C=C1)C2(CCCC23)C=C(C(=CC3F)NC(=O)CC=C)C=CC)C(C)CCS(=C4)C4C=S(C)CC(C)CC=CCCC(C)CCC(C)CC=O - Valid: True

 54%|█████▍    | 189/350 [14:03<11:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=C(N=CC(=C1)Br)NCC2=CC=CC3=C2C(C4=CC3=CC=C4)F.C=C=CCC(CCC=CC)CCC(C)CC(C)C=CC=CCCC.C(C(C)C)(C)CCCC(C)C=O - Valid: True

 54%|█████▍    | 190/350 [14:07<11:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)C3=C(C=C2)C=C(C=C3C)CO - Valid: True

[07:24:11] Conflicting single bond directions around double bond at index 13.
[07:24:11]   BondStereo set to STEREONONE and single bond directions set to NONE.
 55%|█████▍    | 191/350 [14:11<11:50,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)/C(=C(/C2CCC2)/C3=C(C=C(C=C3)CCF)CF)C(C)C=CCCCCCCCC(C)CCC(C)F - Valid: True

 55%|█████▍    | 192/350 [14:16<11:45,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=CC=C1N=C(C=C)C=C(NC(=O)C2=CC=CC=C2C=C(CC)CCCCC)CCC=O - Valid: True

 55%|█████▌    | 193/350 [14:20<11:41,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(C=C2)NC(=O)C3(CCC3)NC(=O)C(=C)CSSC=O - Valid: True

 55%|█████▌    | 194/350 [14:25<11:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)NC(=O)C=C4C=CCC=C4 - Valid: True

 56%|█████▌    | 195/350 [14:29<11:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCOC(=O)C=C.C=CC(=O)NCCCCCCCCCCCCCC(=O)O - Valid: True

 56%|█████▌    | 196/350 [14:34<11:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CNC(=O)CCCCCNC2=C(C=C(C=C2)C(F)F)N - Valid: True

 56%|█████▋    | 197/350 [14:38<11:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)N(C2=CC=C(C=C2)C)C3=CC=CC=C3C(=O)OC - Valid: True

 57%|█████▋    | 198/350 [14:43<11:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)N(C)C(=O)C=CC(=C(C=CC=C)O)Cl - Valid: True

 57%|█████▋    | 199/350 [14:47<11:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(COC(=O)C1=CC=C(C=C1)C2=CC=CC)C2OC(=O)C3=C4C=CC=C3C=CCC(O)NC(C)OC=N4 - Valid: True

 57%|█████▋    | 200/350 [14:52<11:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCCCCCCCCCCCCCCOC(=O)C=C.CCCCCCCCOC(=O)C(=C)C.C=CCC(=C)CC(C)C=O - Valid: True

 57%|█████▋    | 201/350 [14:56<11:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)C=C(C=C2)OCC3=CC=C(C=C3)OC - Valid: True

 58%|█████▊    | 202/350 [15:01<11:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1C(=O)NC2=CC=C(C=C2)N=CC(=O)NC=CC3C=CCC=C3)CC=O)CC(=C)CC=CCC(C)C=CCCC(C)C - Valid: True

 58%|█████▊    | 203/350 [15:05<10:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=CN=C(S2)CCCC3=CC=C(C=C3)N - Valid: True

 58%|█████▊    | 204/350 [15:09<10:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)C=C3CC=CC=C3 - Valid: True

 59%|█████▊    | 205/350 [15:14<10:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C(=C1OC(=O)C(=C)C)OC2=CC=C(C=C2)OCC=CC=CC=C(CCC=CC)C)C(C)C=O - Valid: True

 59%|█████▉    | 206/350 [15:18<10:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC2=C(C=C1)N=C(C3=C2C=C(C=C3)Br)CF - Valid: True

 59%|█████▉    | 207/350 [15:23<10:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC2=C1C(=C(S2)C(=O)NN=C/C)N=C/C(F)F)F - Valid: True

 59%|█████▉    | 208/350 [15:27<10:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOCCOC=CC=C(C(=O)OCC(C(F)(F)F)C(F)(F)F)F - Valid: True

 60%|█████▉    | 209/350 [15:32<10:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 60%|██████    | 210/350 [15:36<10:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C(CC2=C1C=C(C=C2)C3=CC=CC=C3SC=CC=CC=C)CC - Valid: True

 60%|██████    | 211/350 [15:41<10:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)OC(=O)/C=C/C1=CC=C(C=C1)OC2=C(SC3=C2C=CC(=C3)OC)CCC(=O)N=C(S=CCC=C=CCCC=4)NCC=NC=4C - Valid: True

 61%|██████    | 212/350 [15:45<10:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C1/C2=CC(=CC=C2)N(C=N1)CC3=CC=C(C=C3)C(=O)CC=C4C=CC=CC4 - Valid: True

 61%|██████    | 213/350 [15:50<10:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)OC.CC(=C)C(=O)OCCOC(=O)CC(=C)CC(C)OOCC=C.C=C1C=CCCC=CCC2=CCC=CC12 - Valid: True

 61%|██████    | 214/350 [15:54<10:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC2=C1)N=C(C(=C2)C)CC(=O)N(CCCC)C - Valid: True

 61%|██████▏   | 215/350 [15:59<10:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=O)OC1=CC=CC=C1NC(=O)NC2=CC=C(C=C2)CC(CCC=CC(=C)C)C(CCCC)CCCC - Valid: True

 62%|██████▏   | 216/350 [16:03<09:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '7542]'
	SELFIES: [C][C][=C][Branch2][Branch1][=Branch1][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][C][Branch1][=Branch2][C][=Branch1][C][=O][C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O][C][=Branch1][C][=O][C][=C][C][=C][Branch1][Branch1][S][C][=C][C][=Branch1][S][C][=Branch1][C][Ring1][Ring1][=N][C][C][=C][C][C][C][=C][Branch1][C][=Branch1][C][C][C][C][Branch1][C][C][=Branch1][C][C][C][C][C][C][C][C][C][C][C][C]7542][C][C][=Branch1][C][C][=Branch1][C][C][C][=Branch1][C][C][C][C][C][=O][C]

 62%|██████▏   | 217/350 [16:07<09:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC(C(C(F)(F)F)C(F)(F)F)C1=CC=C(C=C1)CCOC(=O)CC=CCC(C)SC=NSSCC(CC=O)C - Valid: True

 62%|██████▏   | 218/350 [16:12<09:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '][/C]'
	SELFIES: [C][C][O][C][=Branch1][C][=O][C][=Branch2][Ring2][C][=C][Branch2][Ring1][=N][C][=C][C][=Branch2][Ring1][=Branch1][=C][Branch1][=Branch2][C][=Branch1][Branch1][=C][Ring1][=Branch1][F][F][N][C][C][N][Branch1][Branch1][C][C][Ring1][=Branch1][C][=O][C][=C][C][C][=C][Branch1][Branch1][Branch1][C][C][=C][C][Ring1][=Branch1][C][C][C][=C][C][C][=Branch1][C][C][C][=C][C][C][C][C]][/C][=Branch1][=Branch1][C][C][=Branch1][C][C][=Branch1][C][C][=Branch1][C][C][C][C][C][C][=O][C][C][C][C]-Branch1][=Branch1][C][=Branch1][C][C][=Branch1][C][C][=Branch1][C][C][=C][C][C][=O][C][C]

 63%|██████▎   | 219/350 [16:16<09:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CN2C=CN=C2C=CC(=C)OC3=CC=C(C=C3)C=NNC=CC(C)CCOC=CCC=C(CCCC=C)CCC(C)C=C=C(C)C(C)C - Valid: True

 63%|██████▎   | 220/350 [16:21<09:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C(=CC(=C1)O)C)N(CCC2C=CC3=CC=CC)C32 - Valid: True

 63%|██████▎   | 221/350 [16:25<09:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCC(CC)COC(=O)C=C.CC(=C)C(=O)NCCCCCCCCCCCCCCCCO - Valid: True

 63%|██████▎   | 222/350 [16:30<09:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N[C@H1](C2=CC=CC=C2)C(=O)OC - Valid: True

 64%|██████▎   | 223/350 [16:34<09:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=C(C=CC(=C1)[N+1](=O)[O-1])C2=CC=C(O2)/C=C/C(=O)OC - Valid: True

 64%|██████▍   | 224/350 [16:39<09:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC1=CC=C(C=C1)OC(=O)C2=CC(=CC=C2)NC(=O)OC3=CC=CC4=C3C=CC=C4 - Valid: True

 64%|██████▍   | 225/350 [16:43<09:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[199]'
	SELFIES: [C][O][C][=Branch1][C][=O][/C][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][199][=C][Branch1][#Branch2][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][F][F]

 65%|██████▍   | 226/350 [16:48<09:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCOC(=O)C=C.CC(=C)C(=O)OC - Valid: True

 65%|██████▍   | 227/350 [16:52<09:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=C(C=C(C=C1)F)C(=C)C(=O)OCC2=CC(=CC=C2)[N+1](=O)[O-1] - Valid: True

 65%|██████▌   | 228/350 [16:57<09:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C(=C/C1=CC=CO1)/NC(=O)C2=CC=C(C=C2)Cl - Valid: True

 65%|██████▌   | 229/350 [17:01<08:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCC(CCCCCCC)CCC1=CC=C(C=C1)/C=C/C(=O)OCC2=CC(=C(C=C2)CO)COCF - Valid: True

 66%|██████▌   | 230/350 [17:05<08:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1C(C(C(C(C1(F)F)(F)F)(F)F)F)F - Valid: True

 66%|██████▌   | 231/350 [17:10<08:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1CCOC(=O)/C=C/C2=CC(=C(C=C2)Cl)OC(C)C(C)CC - Valid: True

 66%|██████▋   | 232/350 [17:14<08:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=CC(=C1)[N+1](=O)[O-1])C2=CC(=CC=C2)F - Valid: True

 67%|██████▋   | 233/350 [17:19<08:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)[N+1](=O)[O-1] - Valid: True

 67%|██████▋   | 234/350 [17:23<08:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1=CC=C(C=C1)F - Valid: True

 67%|██████▋   | 235/350 [17:28<08:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCCCC(CCCCCCCC)CCCCOC(=O)C=C.C=CC(=O)O - Valid: True

 67%|██████▋   | 236/350 [17:32<08:28,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC(=CC=C1/C=C/C(=O)OC2=CC=C(C=C2)/C=C/C(=O)OCC3=CC=CC=C3)C=CC - Valid: True

 68%|██████▊   | 237/350 [17:37<08:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N=C2)C3=CC(=CC=C3)Cl - Valid: True

 68%|██████▊   | 238/350 [17:41<08:19,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1=CC=C(C=C1)C(=C)C(=O)OCC2=CC=C(C=C2)OC(=O)C=CC=CC3=CCC=CC3 - Valid: True

 68%|██████▊   | 239/350 [17:46<08:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=C(C=C1)[N+1](=O)[O-1])C2=CC=C(C=C2)C(=O)NC(=O)C=CC=CC34C=C3SS4(C)C=C - Valid: True

 69%|██████▊   | 240/350 [17:50<08:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C=O - Valid: True

 69%|██████▉   | 241/350 [17:54<08:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CC(=C1)SCC2=CC=CC=C2)N - Valid: True

 69%|██████▉   | 242/350 [17:59<08:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(CO)C(=O)OCC(C)(C)COC(=O)C=C.COC(=O)C=C - Valid: True

 69%|██████▉   | 243/350 [18:03<07:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC=C1C2C=CC=C1C(=O)N(C2=O)C(=O)C3=CC4=CC=CC=C4C=C3 - Valid: True

 70%|██████▉   | 244/350 [18:08<07:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)C=C(NC)C=O - Valid: True

 70%|███████   | 245/350 [18:12<07:48,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(C(=O)NC2=CC(=C(C=C2)C=O)CC(C)CCC=O)OOCCCCC - Valid: True

 70%|███████   | 246/350 [18:17<07:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(C(=C1F)F)F)O)C)NCC2=CC=C(C=C2)F - Valid: True

 71%|███████   | 247/350 [18:21<07:39,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC2=C(C=C1)C=C(C=C2)OC(=O)C=C - Valid: True

 71%|███████   | 248/350 [18:26<07:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1CCC2C(C1)O2 - Valid: True

 71%|███████   | 249/350 [18:30<07:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)OC(C)(C)CC2=CC=C(C=C2)F)Cl - Valid: True

 71%|███████▏  | 250/350 [18:35<07:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)O)CC(C(C(F)(F)F)(C(F)(F)F)F)C=CC=CSF - Valid: True

 72%|███████▏  | 251/350 [18:39<07:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC=C(C1=C(C(=CC=C1)C)N=[N+1]=[N-1])CCC=O - Valid: True

 72%|███████▏  | 252/350 [18:44<07:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1=CC=CC=C1CCO[C@H1]2[C@@H1]([C@H1]([C@@H1]([C@H1](O2)CO)O)O)O - Valid: True

 72%|███████▏  | 253/350 [18:48<07:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)O)OC2=C(C=C(C=C2)Cl)Cl - Valid: True

 73%|███████▎  | 254/350 [18:52<07:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C(=C1)C)C2=CC=CC=C2C(=O)OC(C)(C)C)C=CC(=O)OC(C)(C)CCC - Valid: True

 73%|███████▎  | 255/350 [18:57<07:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC1=C(C(=CC(=C1)/C=C/C(=O)OC)Cl)OCC2=C(C=C(C=C2)F)Cl - Valid: True

 73%|███████▎  | 256/350 [19:01<06:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N(N=C1)C)CNC2=CC=CC=C2C(F)(F)F - Valid: True

 73%|███████▎  | 257/350 [19:06<06:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C=C1)C(C)C)OC(=O)C=C - Valid: True

 74%|███████▎  | 258/350 [19:10<06:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)OC(=O)C=C - Valid: True

 74%|███████▍  | 259/350 [19:15<06:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OC1CCN(CC1)COC(=O)C=C - Valid: True

 74%|███████▍  | 260/350 [19:19<06:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N=CC=C1)CCCC2=CC3=CC=C2S(=O)(=O)C=CCC=CC=C3 - Valid: True

 75%|███████▍  | 261/350 [19:24<06:37,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(C=C23)CCCCC3 - Valid: True

 75%|███████▍  | 262/350 [19:28<06:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)O.CC(=C)C(=O)OC.C=CC1=CC=CC=C1 - Valid: True

 75%|███████▌  | 263/350 [19:33<06:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(N=C(C(=C1NC(=O)N(C=O)C=C)C2=C=CN=C2)SC)C(C)C=CCCC3C=CCC=C3F - Valid: True

 75%|███████▌  | 264/350 [19:37<06:23,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)C(F)F)F - Valid: True

 76%|███████▌  | 265/350 [19:41<06:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C[C@]1C2CCC(=O)C=C2CC[C@@H1]1C(=O)C(=C)C3=CC=C(C=C3)C=CC(=O)OC - Valid: True

 76%|███████▌  | 266/350 [19:46<06:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1=CC=C(C=C1)OC(=O)C=C - Valid: True

 76%|███████▋  | 267/350 [19:50<06:10,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)N/C(=C/C1=C(C=C(C=C1)OC)OCC(=O)OC/C=C/C=CC=CCC(=O)C)CCF - Valid: True

 77%|███████▋  | 268/350 [19:55<06:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C2C(=CC=C1)C(=O)N(C2=O)C3=CC(=CC=C3)C=COC=CC4C=CCC=C4 - Valid: True

 77%|███████▋  | 269/350 [19:59<06:01,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1/C=C/C(=O)OCC(=O)NC2=CC3=C)C=C2OCO3 - Valid: True

 77%|███████▋  | 270/350 [20:04<05:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

malformed SELFIES string, hanging '[' bracket

 77%|███████▋  | 271/350 [20:08<05:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC1=CC=C(C=C1)[N+1](=O)[O-1] - Valid: True

 78%|███████▊  | 272/350 [20:13<05:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC1=C(C=CC=C1)F - Valid: True

 78%|███████▊  | 273/350 [20:17<05:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)[N+1](=O)[O-1])NC(=O)C2=CC=CC=C2 - Valid: True

 78%|███████▊  | 274/350 [20:22<05:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1=CC(=C(C=C1C(F)(F)F)OO)C)C=C2CC=CC=C2/C=C=CF - Valid: True

 79%|███████▊  | 275/350 [20:26<05:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C2C(=CC=C1)C3=C(N2)N=CC(=C3)CN - Valid: True

 79%|███████▉  | 276/350 [20:31<05:30,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C2=C(C=CC(=C2)Cl)Cl - Valid: True

 79%|███████▉  | 277/350 [20:35<05:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=CC=C1)C(=O)C(=C)C(=O)OC(C)(C)CC(=O)OC - Valid: True

 79%|███████▉  | 278/350 [20:39<05:21,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CCC1=C2C=CC=C1OC(O2)C3=CC=C(C=C3)C - Valid: True

 80%|███████▉  | 279/350 [20:44<05:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=C(C=C1)C(=O)C2=CC=CC=C2)C(C)(F)F - Valid: True

 80%|████████  | 280/350 [20:48<05:12,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=CN=C1NC2=CC=CC=C2 - Valid: True

 80%|████████  | 281/350 [20:53<05:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C2=NC=CN=C2 - Valid: True

 81%|████████  | 282/350 [20:57<05:03,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CN(C)C1=CC=C(C=C1)C2=CC=C(C=C2)COC(=O)C=C - Valid: True

 81%|████████  | 283/350 [21:02<04:59,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)P(=O)(OC)OCC - Valid: True

 81%|████████  | 284/350 [21:06<04:54,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)CN2C(=O)C3=CC=CC=C3C=N2 - Valid: True

 81%|████████▏ | 285/350 [21:11<04:50,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CCC1=CC=CC=C1.C=CC(=O)OCCO - Valid: True

 82%|████████▏ | 286/350 [21:15<04:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C(=C)C(=O)OCC(C)C)CC - Valid: True

 82%|████████▏ | 287/350 [21:20<04:41,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C(F)(F)F - Valid: True

 82%|████████▏ | 288/350 [21:24<04:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CP(=O)(OCC)OCC - Valid: True

 83%|████████▎ | 289/350 [21:29<04:32,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

invalid symbol '[1311]'
	SELFIES: [C][C][=C][C][=Branch1][=Branch2][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O][C][=Branch1][C][=O][C][=C][1311]

 83%|████████▎ | 290/350 [21:33<04:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1CC(C(C(C1(F)F)(F)F)(F)F)(F)F - Valid: True

 83%|████████▎ | 291/350 [21:38<04:23,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC(C(C(C(C(F)(F)F)(C(F)(F)F)F)F)F)F - Valid: True

 83%|████████▎ | 292/350 [21:42<04:19,  4.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCC1(C(C(C(C(C1(F)F)(F)F)(F)F)(F)F)OC=O)NN(C=C2C(C)NCC)NNNCC(C)CCCS2CCC - Valid: True

 84%|████████▎ | 293/350 [21:46<04:14,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(SC(=C1)Br)[N+1](=O)[O-1] - Valid: True

 84%|████████▍ | 294/350 [21:51<04:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCC(CCCCCCC)OC(=O)C=C.C=CC(=O)O - Valid: True

 84%|████████▍ | 295/350 [21:55<04:05,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)OC(C)(C)CC - Valid: True

 85%|████████▍ | 296/350 [22:00<04:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC1(CCCCC1)CCOC(=O)/C=C/C2=CC=C(C=C2)OC - Valid: True

 85%|████████▍ | 297/350 [22:04<03:56,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC(=C(C2=C1C=CC(=C2)C(F)(F)F)O)C=CCC(C)OOC - Valid: True

 85%|████████▌ | 298/350 [22:09<03:52,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OC1=CC=C(C=C1)C(=O)C2=CC=CC=C2 - Valid: True

 85%|████████▌ | 299/350 [22:13<03:47,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)NC(=CC1=C(C=C(C=C1)Cl)NF)CCOC(=O)C=C - Valid: True

 86%|████████▌ | 300/350 [22:18<03:43,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CC(=C(C(=C1F)OC(F)(F)Cl)F)N)C[N+1]=O)[O-1] - Valid: True

 86%|████████▌ | 301/350 [22:22<03:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCCCC(CCCCCCC)CCOC(=O)C=C.CC(=C)C(=O)OCCO.C=CC(=O)O - Valid: True

[07:32:26] Conflicting single bond directions around double bond at index 5.
[07:32:26]   BondStereo set to STEREONONE and single bond directions set to NONE.
 86%|████████▋ | 302/350 [22:27<03:34,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C(/C1CC1)/OS(=O)(=O)C(F)(F)F - Valid: True

 87%|████████▋ | 303/350 [22:31<03:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CC1=CC=C(C=C1)OC2CCCO2 - Valid: True

 87%|████████▋ | 304/350 [22:36<03:25,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCC(CC)COC(=O)C=C - Valid: True

 87%|████████▋ | 305/350 [22:40<03:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=C(C=C1)C(F)(F)F - Valid: True

 87%|████████▋ | 306/350 [22:44<03:16,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)N=C(S)CC2=CC=CC=N2 - Valid: True

 88%|████████▊ | 307/350 [22:49<03:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)OC2=CC=CC=C2 - Valid: True

 88%|████████▊ | 308/350 [22:53<03:07,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)OC.C=CC(=O)OCCO.C=CC1=CC=CC=C1 - Valid: True

 88%|████████▊ | 309/350 [22:58<03:02,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=C(C=C1)O)C2=C(C=C(C=C2)Cl)Cl - Valid: True

 89%|████████▊ | 310/350 [23:02<02:58,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCOCC(CC(C(C(C(C(C(C(CCC=O)CF)F)F)(C)O)COC=O)CC)(C)C)C(=C)C - Valid: True

 89%|████████▉ | 311/350 [23:07<02:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C(C1=CN=C(C(=C1Cl)Cl)Cl)O)C=NC(CC2CCC2)CF - Valid: True

 89%|████████▉ | 312/350 [23:11<02:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C1C(C)(C)OC(=O)NC(=CC2=NN=C(O2)C=CC(=O)OCC3=CC=C)C=C31 - Valid: True

 89%|████████▉ | 313/350 [23:16<02:45,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC(=CC=C1)C(=O)NC - Valid: True

 90%|████████▉ | 314/350 [23:20<02:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=C1C(=O)N(C(=S)S1)C=CC(=O)OC(=O)C=C - Valid: True

 90%|█████████ | 315/350 [23:25<02:36,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(C=C1)N - Valid: True

 90%|█████████ | 316/350 [23:29<02:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CN=C(C=C1)C(F)(F)F - Valid: True

 91%|█████████ | 317/350 [23:33<02:27,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=C(C=C1)O)CC2=CC=CC=C2OCC3=CC=CC=C3OC - Valid: True

 91%|█████████ | 318/350 [23:38<02:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)OCC=CC3=CC=CC=C3 - Valid: True

 91%|█████████ | 319/350 [23:42<02:18,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=C(C=C1)Br)[N+1](=O)[O-1] - Valid: True

 91%|█████████▏| 320/350 [23:47<02:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)OC.C=CC1=CC=CC2=C1.C=CC(=O)OC2=O - Valid: True

 92%|█████████▏| 321/350 [23:51<02:09,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.CC(=C)C(=O)OC.CC(=C)C(=O)OCCOC(=O)CC(=C)C(=O)OC.C=CCC=CCC(C)CC(=O)CCCC - Valid: True

 92%|█████████▏| 322/350 [23:56<02:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)N - Valid: True

 92%|█████████▏| 323/350 [24:00<02:00,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(=C)C(=O)OCCCOC(=O)C(=C)C.CC(=C)C(=O)OC1=CC=CC=C1 - Valid: True

 93%|█████████▎| 324/350 [24:05<01:55,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C2C(=CC=C1)N=C(S2)C - Valid: True

 93%|█████████▎| 325/350 [24:09<01:51,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)N(C)CC#N - Valid: True

 93%|█████████▎| 326/350 [24:14<01:46,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CN=CC=C1 - Valid: True

 93%|█████████▎| 327/350 [24:18<01:42,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC2=C(C=C1)N=C(N2C)C3(CCC3)NC(=O)C4=CC=CC=C4 - Valid: True

 94%|█████████▎| 328/350 [24:23<01:38,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=CC1=CC=C(C=C1)NC(=O)NC2=CC=CC3=C2C=C)C=C3C#N - Valid: True

 94%|█████████▍| 329/350 [24:27<01:33,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C2=CC=CC=C2N1C)C(=CNS(=O)(=O)C=C3CC=CC=C3)S(=O)CC=CCC(C)C=O - Valid: True

 94%|█████████▍| 330/350 [24:31<01:29,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCC(COC1=CC=C(C=C1)C(C2=CC=CC=C2)OC3=CC=CC=C3OC=CCC=C)C(CCC)=CCCC=CCC=CCCC - Valid: True

 95%|█████████▍| 331/350 [24:36<01:24,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC2=C(C=C1)C=C(C=C2)C(=O)N(CC3=CC=C(C=C3)C=CC(=O)OOCCC=CCCC)C(=CCNN=CCCS)COCC/C=C/C/C/C/C(/C)CCCCC=O - Valid: True

 95%|█████████▍| 332/350 [24:40<01:20,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=CC=C1C=CC(=O)OCCO - Valid: True

 95%|█████████▌| 333/350 [24:45<01:15,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=C.C=CC(=O)OC1=CC=CC=C1.C=CC(=O)O - Valid: True

 95%|█████████▌| 334/350 [24:49<01:11,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C(=C)CC1=CC=CC2=C1NC=C2 - Valid: True

 96%|█████████▌| 335/350 [24:54<01:06,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC(C)(C)OC(=O)C(=C)C(C1=CC=CC=C1)OCOC - Valid: True

 96%|█████████▌| 336/350 [24:58<01:02,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)NC(=O)C2(CCCC2)NC(=O)OC=C(C=CC=CCCCF)F - Valid: True

 96%|█████████▋| 337/350 [25:03<00:57,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)C=CC1=CC=C(C=C1)OCCO - Valid: True

 97%|█████████▋| 338/350 [25:07<00:53,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=C(C=CN=C1C=C)NC - Valid: True

[07:35:11] Conflicting single bond directions around double bond at index 17.
[07:35:11]   BondStereo set to STEREONONE and single bond directions set to NONE.
 97%|█████████▋| 339/350 [25:12<00:49,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)S(=O)(=O)NC2=C(C=NC=C2)/C=C(/C#N)/C(=O)OC - Valid: True

 97%|█████████▋| 340/350 [25:16<00:44,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)/C=C/C1=CC=C(C=C1)F - Valid: True

 97%|█████████▋| 341/350 [25:20<00:40,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC=C(C1=CC(=C(C(=C1)C)OC(=O)NC2=CCS=C2CCF)C=CC(C)CCC=CC(C)C=CC3CC=CC=C3C)CC4=C=C4C=CC=O - Valid: True

 98%|█████████▊| 342/350 [25:25<00:35,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC=C(S1)Br - Valid: True

 98%|█████████▊| 343/350 [25:29<00:31,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCCCOC(=O)C=C.C=CC(=O)O - Valid: True

 98%|█████████▊| 344/350 [25:34<00:26,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

C=CC(=O)OCCCCCCOC1=CC=C(C=C1)C2=CC=C(C=C2)C3CCC(CC3)C=CCC(CC4CCCC)O4 - Valid: True

 99%|█████████▊| 345/350 [25:38<00:22,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=CC(=C(C=C1)OC)C=CC2=CC=C(C=C2)OCC=CCC=CC=CCC=C - Valid: True

 99%|█████████▉| 346/350 [25:43<00:17,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCOC(=O)C=CC1=C(C=CC(=C1[N+1])C=O)NC(=O)N(C)C2=CC=C(C=C2)C=N - Valid: True

 99%|█████████▉| 347/350 [25:47<00:13,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

COC(=O)/C=C/C1=CC(=CC=C1)O - Valid: True

 99%|█████████▉| 348/350 [25:52<00:08,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CC1=CC=C(C=C1)C(C(=C)C(=O)OC)OC(=O)C - Valid: True

100%|█████████▉| 349/350 [25:56<00:04,  4.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

CCC(COC(=O)C=C)OC(=O)C=C - Valid: True

100%|██████████| 350/350 [26:01<00:00,  4.46s/it]

C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)COC(C)OC)CC(CCC=CC)CC(C)CCCCCCCCC - Valid: True

In [10]:
smiles_test_df

                                                smiles  static_polarizability
0                                            C=CC(=O)O               0.000000
1                                C=CC(=O)[O-1].[NH4+1]               0.000889
2                                  C=CC(=O)[O-1].[K+1]               0.001779
3                                         C=CC(=O)OCCN               0.003557
4                                         C=CC(=O)OCCN               0.004446
..                                                 ...                    ...
328  CCOC(=O)C=CC1=C(C=CC(=C1[N+1])C=O)NC(=O)N(C)C2...               0.306800
329                         COC(=O)/C=C/C1=CC(=CC=C1)O               0.307689
330               CC1=CC=C(C=C1)C(C(=C)C(=O)OC)OC(=O)C               0.308578
331                           CCC(COC(=O)C=C)OC(=O)C=C               0.309468
332  C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)CO...               0.310357

[333 rows x 2 columns]

In [11]:
acrylate_smarts = "C=C[C](=O)O"
acrylate_mol = Chem.MolFromSmarts(acrylate_smarts)

def is_mixed_neutral_smiles(smiles: str) -> bool:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False  # or True if you want to discard invalid SMILES
    
    fragments = Chem.GetMolFrags(mol, asMols=True)
    
    if len(fragments) == 1:
        return False  # single molecule, keep
    
    all_neutral = all(sum(atom.GetFormalCharge() for atom in frag.GetAtoms()) == 0 for frag in fragments)
    
    return all_neutral  # True → multiple neutral fragments → discard

def is_acrylate(smi):
    mol = Chem.MolFromSmiles(smi)
    return mol.HasSubstructMatch(acrylate_mol) if mol else False

df_filtered = smiles_test_df[~smiles_test_df["smiles"].apply(is_mixed_neutral_smiles)].reset_index(drop=True)
df_filtered["is_acrylate"] = df_filtered["smiles"].apply(is_acrylate)

[12:47:53] Conflicting single bond directions around double bond at index 17.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 19.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 15.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 14.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 5.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 17.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 17.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 19.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 15.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 14.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 13.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 5.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.
[12:47:53] Conflicting single bond directions around double bond at index 17.
[12:47:53]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [12]:
(1 - df_filtered['smiles'].isin(df_polarizability['smiles_A']).sum()/len(df_filtered))*100

np.float64(79.80456026058633)

In [13]:
df_filtered = df_filtered.rename(columns={'smiles': 'smiles_A'})
df_filtered['chain_size'] = 0
df_filtered['id_A'] = df_filtered.index
df_filtered.to_csv('gpt_generation.csv', index=False)

# Predict

In [1]:
import torch
import pandas as pd

import sys
sys.path.append("/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy")
from polygraphpy.gnn.pre_processing import PreProcess

# Setup
preprocess = PreProcess(
    input_csv='../polygraphpy/data/polarizability_data.csv',
    train_input_data_path='prediction_test',
    polymer_type='monomer',
    target='static_polarizability',
    gnn_output_path='./'
)

atoms_list, bonds_list = preprocess.extract_atoms_and_bonds_features_from_monomer_smiles()
atom_encoder = preprocess.make_encoder(pd.DataFrame(atoms_list).drop_duplicates().reset_index(drop=True))
bond_encoder = preprocess.make_encoder(pd.DataFrame(bonds_list).drop_duplicates().reset_index(drop=True))

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = torch.load('../polygraphpy/data/gnn_output/model_gcn.pt', weights_only=False)
model = model.to(device)
print(model)

/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_geometric/typing.py:68: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/libpyg.so: undefined symbol: _ZN2at4_ops11multinomial4callERKNS_6TensorElbSt8optionalINS_9GeneratorEE
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/torch_sparse/_hgt_sample_cuda.so: undefined symbol: _ZN2at4_ops11multinomial4callERKNS_6TensorElbSt8optionalINS_9GeneratorEE
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
/home/jgduarte/Documents/RA/Projects/3M/PolyGraphPy/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Reading GNN input file.
Extracting unique features from atoms and bonds.

100%|██████████| 26582/26582 [00:07<00:00, 3387.27it/s]

Making feature encoder.
Making feature encoder.
GraphUNetModel(
  (unet): GraphUNet(68, 150, 150, depth=5, pool_ratios=[0.5, 0.5, 0.5, 0.5, 0.5])
  (lin1): Linear(in_features=150, out_features=150, bias=True)
  (lin2): Linear(in_features=150, out_features=150, bias=True)
  (lin3): Linear(in_features=150, out_features=150, bias=True)
  (output): Linear(in_features=150, out_features=1, bias=True)
)

In [4]:
from rdkit import Chem
from torch_geometric.data import Data

def mol_to_data(smiles):
    atoms = []
    bonds = []
    m1 = Chem.MolFromSmiles(smiles, sanitize=True)
    if m1 is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    m1 = Chem.AddHs(m1)
    
    atoms = preprocess.get_nodes_information(m1, [], chain_size=0)

    if not atoms:
        print(f"No atoms extracted for SMILES: {smiles}")
        return None
    
    df_nodes = pd.DataFrame(atoms)
    nodes_features = pd.DataFrame(atom_encoder.transform(df_nodes.drop(['idx'], axis=1)).toarray())
    x = torch.tensor(nodes_features.astype('float32').values)
    
    bonds = preprocess.get_bonds_information(m1, [])
    if not bonds:
        print(f"No bonds extracted for SMILES: {smiles}")
        return None
    df_bonds = pd.DataFrame(bonds)
    edge_index = torch.tensor([
        df_bonds.begin_idx.to_list() + df_bonds.end_idx.to_list(),
        df_bonds.end_idx.to_list() + df_bonds.begin_idx.to_list()
    ])
    
    edge_attrs = df_bonds[['type', 'is_conjugated', 'is_aromatic']]
    edge_attrs = pd.concat([edge_attrs, edge_attrs.sort_index(ascending=False)])
    edge_attr = torch.tensor(bond_encoder.transform(edge_attrs).toarray())
    
    edge_weight = torch.tensor([1.0] * edge_index.shape[1], dtype=torch.float32)
    
    mol_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, edge_weight=edge_weight)
    mol_data.validate()

    return mol_data
    
df_results = pd.DataFrame()
df_filtered = pd.read_csv('gpt_generation.csv')

for i in df_filtered.itertuples():
    mol_data = mol_to_data(i.smiles_A).to(device)

    with torch.no_grad():
        batch = torch.zeros(mol_data.x.size(0), dtype=torch.long).to(device)
        pred = model(mol_data.x, mol_data.edge_index, mol_data.edge_weight, batch)

    df_results = pd.concat([df_results, pd.DataFrame({'smiles_A': i.smiles_A, 'y': i.static_polarizability, 'pred': pred.cpu().numpy()[0][0]}, index=[0])]).reset_index(drop=True)

[13:03:40] Conflicting single bond directions around double bond at index 17.
[13:03:40]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:40] Conflicting single bond directions around double bond at index 19.
[13:03:40]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 15.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 13.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 13.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 14.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 13.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 13.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:41] Conflicting single bond directions around double bond at index 13.
[13:03:41]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:43] Conflicting single bond directions around double bond at index 5.
[13:03:43]   BondStereo set to STEREONONE and single bond directions set to NONE.
[13:03:43] Conflicting single bond directions around double bond at index 17.
[13:03:43]   BondStereo set to STEREONONE and single bond directions set to NONE.

In [5]:
df_results['error'] = abs(df_results['y'] - df_results['pred'])/(df_results['y'] + 1e-12)

In [6]:
df_results

,smiles_A,y,pred,error
0,C=CC(=O)O,0.000000,0.030379,3.037924e+10
1,C=CC(=O)[O-1].[NH4+1],0.000889,0.049763,5.495915e+01
2,C=CC(=O)[O-1].[K+1],0.001779,0.045486,2.457501e+01
3,C=CC(=O)OCCN,0.003557,0.042586,1.097218e+01
4,C=CC(=O)OCCN,0.004446,0.055071,1.138559e+01
...,...,...,...,...
302,CCOC(=O)C=CC1=C(C=CC(=C1[N+1])C=O)NC(=O)N(C)C2...,0.306800,0.229768,2.510804e-01
303,COC(=O)/C=C/C1=CC(=CC=C1)O,0.307689,0.127558,5.854334e-01
304,CC1=CC=C(C=C1)C(C(=C)C(=O)OC)OC(=O)C,0.308578,0.114297,6.296021e-01
305,CCC(COC(=O)C=C)OC(=O)C=C,0.309468,0.036461,8.821804e-01
306,C=CC(=O)OCC(CO)(COCC(COC(=O)C=C)(COC(=O)C=C)CO...,0.310357,0.099259,6.801792e-01

In [7]:
df_results.to_csv('predict_results_from_gpt.csv', index=False)